import React from 'react';
import {
  AppstoreOutlined,
  AuditOutlined,
  BulbOutlined,
  CalendarOutlined,
  CarOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  DollarOutlined,
  DislikeOutlined,
  ExclamationCircleOutlined,
  EyeOutlined,
  FileTextOutlined,
  FlagOutlined,
  HourglassOutlined,
  InboxOutlined,
  LikeOutlined,
  LockOutlined,
  MailOutlined,
  PauseCircleOutlined,
  PhoneOutlined,
  PlayCircleOutlined,
  QuestionCircleOutlined,
  SafetyCertificateOutlined,
  SendOutlined,
  ShoppingCartOutlined,
  StopOutlined,
  SyncOutlined,
  TeamOutlined,
  ToolOutlined,
  UnlockOutlined,
  UserOutlined,
} from '@ant-design/icons';

export const TASK_STATUS_DEFAULT_ICON_KEY = 'circle';

export const TASK_STATUS_ICON_COMPONENTS: Record<string, React.ReactNode> = {
  circle: <span className="block h-2.5 w-2.5 rounded-full bg-current" />,
  app: <AppstoreOutlined />,
  approve: <CheckCircleOutlined />,
  audit: <AuditOutlined />,
  calendar: <CalendarOutlined />,
  cancel: <CloseCircleOutlined />,
  car: <CarOutlined />,
  carry: <CarryOutOutlined />,
  check: <CheckOutlined />,
  clock: <ClockCircleOutlined />,
  close: <CloseCircleOutlined />,
  delivery: <CarOutlined />,
  dislike: <DislikeOutlined />,
  dollar: <DollarOutlined />,
  eye: <EyeOutlined />,
  file: <FileTextOutlined />,
  flag: <FlagOutlined />,
  hourglass: <HourglassOutlined />,
  idea: <BulbOutlined />,
  inbox: <InboxOutlined />,
  like: <LikeOutlined />,
  lock: <LockOutlined />,
  mail: <MailOutlined />,
  pause: <PauseCircleOutlined />,
  phone: <PhoneOutlined />,
  play: <PlayCircleOutlined />,
  question: <QuestionCircleOutlined />,
  safety: <SafetyCertificateOutlined />,
  send: <SendOutlined />,
  shopping: <ShoppingCartOutlined />,
  stop: <StopOutlined />,
  sync: <SyncOutlined />,
  team: <TeamOutlined />,
  tool: <ToolOutlined />,
  unlock: <UnlockOutlined />,
  user: <UserOutlined />,
  warning: <ExclamationCircleOutlined />,
};

export const TaskStatusIcon = ({ iconKey }: { iconKey?: string | null }) => {
  const key = String(iconKey || TASK_STATUS_DEFAULT_ICON_KEY).trim().toLowerCase();
  return <>{TASK_STATUS_ICON_COMPONENTS[key] || TASK_STATUS_ICON_COMPONENTS[TASK_STATUS_DEFAULT_ICON_KEY]}</>;
};

export default TaskStatusIcon;
