import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const accountingEventRulesConfig: ModuleDefinition = {
  id: 'accounting_event_rules',
  titles: { fa: 'قواعد صدور خودکار سند', en: 'Accounting Event Rules' },
  nature: ModuleNature.FINANCE,
  table: 'accounting_event_rules',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'event_key',
      labels: { fa: 'کلید رویداد', en: 'Event Key' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isTableColumn: true,
      isKey: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'title',
      labels: { fa: 'عنوان', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'rule_mode',
      labels: { fa: 'حالت قاعده', en: 'Rule Mode' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      options: [
        { label: 'ساده', value: 'simple' },
        { label: 'الگویی', value: 'template' },
      ],
    },
    {
      key: 'debit_account_id',
      labels: { fa: 'حساب بدهکار', en: 'Debit Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'accounts',
      order: 1,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'credit_account_id',
      labels: { fa: 'حساب بستانکار', en: 'Credit Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'accounts',
      order: 2,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'vat_account_id',
      labels: { fa: 'حساب مالیات', en: 'VAT Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'accounts',
      order: 3,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'receivable_account_id',
      labels: { fa: 'حساب دریافتنی', en: 'Receivable Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'accounts',
      order: 4,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'payable_account_id',
      labels: { fa: 'حساب پرداختنی', en: 'Payable Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'accounts',
      order: 5,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Is Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'base',
      titles: { fa: 'مشخصات قاعده', en: 'Rule Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'SettingOutlined',
    },
    {
      id: 'accounts',
      titles: { fa: 'نگاشت حساب ها', en: 'Account Mapping' },
      type: BlockType.FIELD_GROUP,
      order: 2,
      icon: 'SwapOutlined',
    },
  ],
  relatedTabs: [],
};
