import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from "../types";

export const attendanceLogsModule: ModuleDefinition = {
  id: "attendance_logs",
  titles: { fa: "تردد", faSingular: "رکورد تردد", en: "Attendance Logs" },
  nature: ModuleNature.STANDARD,
  table: "attendance_logs",
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: "log_type",
      labels: { fa: "نوع ثبت", en: "Log Type" },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1,
      defaultValue: "check_in",
      options: [
        { label: "ورود", value: "check_in", color: "green" },
        { label: "خروج", value: "check_out", color: "red" },
        { label: "مرخصی", value: "leave", color: "orange" },
        { label: "ماموریت", value: "mission", color: "blue" },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "occurred_at",
      labels: { fa: "زمان ثبت سیستمی", en: "System Recorded At" },
      type: FieldType.DATETIME,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "source_type",
      labels: { fa: "منبع ثبت", en: "Source" },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: "manual",
      options: [
        { label: "دستی", value: "manual" },
        { label: "وب فرم", value: "web_form" },
        { label: "QR", value: "qr" },
        { label: "سیستم", value: "system" },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "actual_check_in_time",
      labels: { fa: "ساعت ورود واقعی", en: "Actual Check In Time" },
      type: FieldType.TIME,
      location: FieldLocation.BLOCK,
      blockId: "base",
      order: 1,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: "actual_check_out_time",
      labels: { fa: "ساعت خروج واقعی", en: "Actual Check Out Time" },
      type: FieldType.TIME,
      location: FieldLocation.BLOCK,
      blockId: "base",
      order: 2,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: "manual_check_in_time",
      labels: { fa: "زمان ورود", en: "Manual Check In Time" },
      type: FieldType.TIME,
      location: FieldLocation.BLOCK,
      blockId: "base",
      order: 3,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: "manual_check_out_time",
      labels: { fa: "زمان خروج", en: "Manual Check Out Time" },
      type: FieldType.TIME,
      location: FieldLocation.BLOCK,
      blockId: "base",
      order: 4,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: "location_text",
      labels: { fa: "موقعیت / آدرس", en: "Location" },
      type: FieldType.LOCATION,
      location: FieldLocation.BLOCK,
      blockId: "base",
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: "notes",
      labels: { fa: "یادداشت", en: "Notes" },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: "base",
      order: 6,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: "base",
      titles: { fa: "اطلاعات ثبت تردد", en: "Attendance Info" },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
