import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from "../types";

export const attendanceLogsModule: ModuleDefinition = {
  id: "attendance_logs",
  titles: { fa: "تردد", faSingular: "رکورد تردد", en: "Attendance Logs" },
  nature: ModuleNature.STANDARD,
  table: "attendance_logs",
  dashboard: {
    recentListFields: ["system_code", "employee_id", "log_type", "attendance_date", "source_type"],
  },
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: "employee_id",
      labels: { fa: "نام کارمند", en: "Employee Name" },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 0.5,
      relationConfig: { targetModule: "employees", targetField: "full_name" },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "system_code",
      labels: { fa: "شماره تردد", en: "Attendance No." },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 0.6,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "log_type",
      labels: { fa: "نوع تردد", en: "Log Type" },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1,
      defaultValue: "check_in",
      options: [
        { label: "ورود", value: "check_in", color: "green" },
        { label: "خروج", value: "check_out", color: "red" },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "occurred_at",
      labels: { fa: "زمان ثبت سیستمی", en: "System Recorded At" },
      type: FieldType.DATETIME,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      hideInCreateForm: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "source_type",
      labels: { fa: "منبع", en: "Source" },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: "manual",
      options: [
        { label: "دستی", value: "manual" },
        { label: "وب فرم", value: "web_form" },
        { label: "QR", value: "qr" },
        { label: "سیستم", value: "system" },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "tags",
      labels: { fa: "برچسب‌ها", en: "Tags" },
      type: FieldType.TAGS,
      location: FieldLocation.HEADER,
      order: 3.1,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: "attendance_date",
      labels: { fa: "تاریخ", en: "Attendance Date" },
      type: FieldType.DATE,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 1,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "check_in_time",
      labels: { fa: "ساعت ورود", en: "Check In Time" },
      type: FieldType.TIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 2,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "check_out_time",
      labels: { fa: "ساعت خروج", en: "Check Out Time" },
      type: FieldType.TIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 3,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "presence_minutes",
      labels: { fa: "مجموع حضور (دقیقه)", en: "Presence Minutes" },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 1,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "presence_hours",
      labels: { fa: "مجموع حضور (ساعت)", en: "Presence Hours" },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 2,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "manager_approved",
      labels: { fa: "تایید مدیر", en: "Manager Approved" },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 6,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "related_employee_label",
      labels: { fa: "کارمند مرتبط", en: "Related Employee" },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 1,
      hideInCreateForm: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "linked_check_in_label",
      labels: { fa: "ورود مرتبط", en: "Linked Check In" },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 2,
      hideInCreateForm: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "payroll_reference_label",
      labels: { fa: "جدول حقوق مرتبط", en: "Related Payroll" },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 3,
      hideInCreateForm: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "updated_by_label",
      labels: { fa: "آخرین ویرایش انجام شده به وسیله", en: "Updated By Label" },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 4,
      hideInCreateForm: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "updated_at",
      labels: { fa: "زمان ویرایش", en: "Updated At" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 5,
      readonly: true,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "reference_label",
      labels: { fa: "ارجاع به", en: "Reference" },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 6,
      hideInCreateForm: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "created_by_label",
      labels: { fa: "ایجاد کننده", en: "Created By Label" },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 7,
      hideInCreateForm: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "created_at",
      labels: { fa: "زمان ایجاد", en: "Created At" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 8,
      readonly: true,
      hideInCreateForm: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "closure_status",
      labels: { fa: "وضعیت بسته", en: "Closure Status" },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_hidden",
      order: 9,
      hideInCreateForm: true,
      isTableColumn: false,
      nature: FieldNature.STANDARD,
    },
    {
      key: "actual_check_in_time",
      labels: { fa: "زمان ورود واقعی", en: "Actual Check In Time" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: "actual_check_out_time",
      labels: { fa: "زمان خروج واقعی", en: "Actual Check Out Time" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 4,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: "manual_check_in_time",
      labels: { fa: "زمان ورود دستی", en: "Manual Check In Time" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 5,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: "manual_check_out_time",
      labels: { fa: "زمان خروج دستی", en: "Manual Check Out Time" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 6,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: "location_text",
      labels: { fa: "موقعیت / آدرس", en: "Location" },
      type: FieldType.LOCATION,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 7,
      nature: FieldNature.STANDARD,
    },
    {
      key: "notes",
      labels: { fa: "یادداشت", en: "Notes" },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: "attendance_info",
      order: 8,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: "attendance_info",
      titles: { fa: "اطلاعات تردد", en: "Attendance Info" },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
