import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const automationExecutionReportsConfig: ModuleDefinition = {
  id: 'automation_execution_reports',
  titles: { fa: 'گزارشات فرآیند و اتوماسیون', faSingular: 'گزارش فرآیند و اتوماسیون', en: 'Process & Automation Reports' },
  nature: ModuleNature.STANDARD,
  table: 'automation_execution_reports',
  systemManaged: true,
  disableCreate: true,
  disableDetailView: true,
  hideFullRecordAction: true,
  listPreviewMode: 'modal',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'report_category',
      labels: { fa: 'دسته گزارش', en: 'Report Category' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      options: [
        { label: 'فرآیند شرطی', value: 'process_conditional', color: 'blue' },
        { label: 'فرآیند زماندار', value: 'process_scheduled', color: 'cyan' },
        { label: 'اتوماسیون شرطی', value: 'automation_conditional', color: 'green' },
        { label: 'اتوماسیون زماندار', value: 'automation_scheduled', color: 'orange' },
      ],
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'automation_name',
      labels: { fa: 'نام فرآیند / اتوماسیون', en: 'Automation Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'نتیجه اجرا', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      options: [
        { label: 'موفق', value: 'success', color: 'green' },
        { label: 'ناموفق', value: 'failed', color: 'red' },
      ],
      nature: FieldNature.SYSTEM,
    },
    { key: 'trigger_type', labels: { fa: 'نوع محرک', en: 'Trigger Type' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 4, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'module_id', labels: { fa: 'ماژول مرتبط', en: 'Module' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 5, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'record_id', labels: { fa: 'شناسه رکورد', en: 'Record ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 1, nature: FieldNature.SYSTEM },
    { key: 'message', labels: { fa: 'پیام اجرا', en: 'Message' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 2, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'execution_mode', labels: { fa: 'حالت اجرا', en: 'Execution Mode' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 3, nature: FieldNature.SYSTEM },
    { key: 'details', labels: { fa: 'جزئیات سیستمی', en: 'Details' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'details', order: 4, nature: FieldNature.SYSTEM },
    { key: 'created_at', labels: { fa: 'زمان اجرا', en: 'Run Time' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 6, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 7, isTableColumn: true, nature: FieldNature.STANDARD },
  ],
  blocks: [
    {
      id: 'details',
      titles: { fa: 'جزئیات گزارش', en: 'Report Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
};
