import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const bankAccountsConfig: ModuleDefinition = {
  id: 'bank_accounts',
  titles: { fa: 'حساب های بانکی', en: 'Bank Accounts' },
  nature: ModuleNature.FINANCE,
  table: 'bank_accounts',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'code',
      labels: { fa: 'کد حساب', en: 'Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'bank_name',
      labels: { fa: 'نام بانک', en: 'Bank Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'account_number',
      labels: { fa: 'شماره حساب', en: 'Account Number' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 3,
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'shaba',
      labels: { fa: 'شماره شبا', en: 'Shaba' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'card_number',
      labels: { fa: 'شماره کارت', en: 'Card Number' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'account_holder_name',
      labels: { fa: 'نام صاحب حساب', en: 'Holder Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 3,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'opening_balance',
      labels: { fa: 'موجودی اول دوره', en: 'Opening Balance' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'account_id',
      labels: { fa: 'حساب متناظر', en: 'Ledger Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 5,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Is Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 6,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'base',
      titles: { fa: 'اطلاعات حساب بانکی', en: 'Bank Account Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'BankOutlined',
    },
  ],
  relatedTabs: [],
};
