import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const bartersConfig: ModuleDefinition = {
  id: 'barters',
  titles: { fa: 'تهاترها', faSingular: 'تهاتر', en: 'Barters' },
  nature: ModuleNature.FINANCE,
  table: 'barters',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'name',
      labels: { fa: 'عنوان تهاتر', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      isKey: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'system_code',
      labels: { fa: 'کد سیستمی', en: 'System Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'barter_date',
      labels: { fa: 'تاریخ تهاتر', en: 'Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'barter_type',
      labels: { fa: 'نوع تهاتر', en: 'Type' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      options: [
        { label: 'دریافتی', value: 'incoming', color: 'blue' },
        { label: 'پرداختی', value: 'outgoing', color: 'orange' },
      ],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      options: [
        { label: 'باز', value: 'open', color: 'green' },
        { label: 'مصرف‌شده جزئی', value: 'partial', color: 'orange' },
        { label: 'بسته', value: 'closed', color: 'default' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
      ],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 5.1, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'initial_amount',
      labels: { fa: 'مبلغ اولیه', en: 'Initial Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 1,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'spent_amount',
      labels: { fa: 'مبلغ مصرف‌شده', en: 'Spent Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 2,
      isTableColumn: true,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'remaining_amount',
      labels: { fa: 'مانده', en: 'Remaining Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 3,
      isTableColumn: true,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'customer_id',
      labels: { fa: 'طرف حساب مشتری', en: 'Customer' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 1,
      relationConfig: { targetModule: 'customers', targetField: 'business_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'supplier_id',
      labels: { fa: 'طرف حساب تامین‌کننده', en: 'Supplier' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 2,
      relationConfig: { targetModule: 'suppliers', targetField: 'business_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'employee_id',
      labels: { fa: 'کارکن/دریافت‌کننده', en: 'Employee' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 3,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'source_invoice_id',
      labels: { fa: 'فاکتور فروش مبدا', en: 'Source Sales Invoice' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 4,
      relationConfig: { targetModule: 'invoices', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'source_purchase_invoice_id',
      labels: { fa: 'فاکتور خرید مبدا', en: 'Source Purchase Invoice' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 5,
      relationConfig: { targetModule: 'purchase_invoices', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'توضیحات', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'attachment_url',
      labels: { fa: 'پیوست', en: 'Attachment' },
      type: FieldType.LINK,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 5,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'financial',
      titles: { fa: 'اطلاعات مالی', en: 'Financial' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'DollarOutlined',
    },
    {
      id: 'relations',
      titles: { fa: 'ارتباطات', en: 'Relations' },
      type: BlockType.FIELD_GROUP,
      order: 2,
      icon: 'LinkOutlined',
    },
    {
      id: 'allocations',
      titles: { fa: 'جدول مصرف/واگذاری تهاتر', en: 'Allocations' },
      type: BlockType.TABLE,
      order: 3,
      icon: 'TableOutlined',
      tableColumns: [
        { key: 'date', title: 'تاریخ', type: FieldType.DATE, width: 120 },
        {
          key: 'operation_type',
          title: 'نوع عملیات',
          type: FieldType.SELECT,
          width: 130,
          options: [
            { label: 'دریافت', value: 'receipt' },
            { label: 'پرداخت', value: 'payment' },
          ],
        } as any,
        {
          key: 'status',
          title: 'وضعیت',
          type: FieldType.SELECT,
          width: 130,
          options: [
            { label: 'در انتظار', value: 'pending' },
            { label: 'انجام شده', value: 'received' },
            { label: 'برگشت', value: 'returned' },
            { label: 'لغو', value: 'canceled' },
          ],
        } as any,
        {
          key: 'employee_id',
          title: 'کارکن',
          type: FieldType.RELATION,
          width: 160,
          relationConfig: { targetModule: 'profiles', targetField: 'full_name' } as any,
        },
        {
          key: 'customer_id',
          title: 'مشتری مرتبط',
          type: FieldType.RELATION,
          width: 170,
          relationConfig: { targetModule: 'customers', targetField: 'business_name' } as any,
        } as any,
        {
          key: 'supplier_id',
          title: 'تامین‌کننده مرتبط',
          type: FieldType.RELATION,
          width: 170,
          relationConfig: { targetModule: 'suppliers', targetField: 'business_name' } as any,
        },
        {
          key: 'expense_account_id',
          title: 'حساب هزینه',
          type: FieldType.RELATION,
          width: 170,
          relationConfig: { targetModule: 'chart_of_accounts', targetField: 'code' } as any,
        } as any,
        { key: 'amount', title: 'مبلغ', type: FieldType.PRICE, width: 150, showTotal: true },
        { key: 'description', title: 'توضیحات', type: FieldType.LONG_TEXT, width: 220 },
      ],
    },
  ],
  relatedTabs: [],
};
