import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const calculationFormulasModule: ModuleDefinition = {
  id: 'calculation_formulas',
  titles: { fa: 'فرمول‌های محاسباتی', en: 'Calculation Formulas' },
  nature: ModuleNature.STANDARD,
  table: 'calculation_formulas',
  supportedViewModes: [ViewMode.LIST],
  defaultViewMode: ViewMode.LIST,
  fields: [
    { key: 'name', labels: { fa: 'نام فرمول', en: 'Name' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, isKey: true, validation: { required: true }, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'scope',
      labels: { fa: 'دامنه استفاده', en: 'Scope' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 1.2,
      defaultValue: 'general',
      isTableColumn: true,
      options: [
        { label: 'عمومی', value: 'general' },
        { label: 'عملکرد فعالیت', value: 'activity_performance' },
        { label: 'پاداش هدف', value: 'goal_reward' },
        { label: 'پورسانت', value: 'commission' },
        { label: 'فیش حقوقی', value: 'payroll' },
        { label: 'گردش کار', value: 'workflow' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'context_type',
      labels: { fa: 'نوع زمینه', en: 'Context Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 1.3,
      defaultValue: 'generic',
      isTableColumn: true,
      options: [
        { label: 'عمومی', value: 'generic' },
        { label: 'فعالیت', value: 'task' },
        { label: 'هدف', value: 'goal' },
        { label: 'فاکتور', value: 'invoice' },
        { label: 'کارمند', value: 'employee' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'output_type',
      labels: { fa: 'نوع خروجی', en: 'Output Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 1.4,
      defaultValue: 'number',
      isTableColumn: true,
      options: [
        { label: 'عدد', value: 'number' },
        { label: 'مبلغ', value: 'money' },
        { label: 'امتیاز', value: 'score' },
        { label: 'درصد', value: 'percentage' },
      ],
      nature: FieldNature.STANDARD,
    },
    { key: 'is_active', labels: { fa: 'فعال', en: 'Active' }, type: FieldType.CHECKBOX, location: FieldLocation.HEADER, order: 1.5, defaultValue: true, isTableColumn: true, nature: FieldNature.STANDARD },
    
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 1.6, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'formula', labels: { fa: 'نمایش فرمول', en: 'Formula' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'base', order: 2, validation: { required: true }, nature: FieldNature.STANDARD },
    { key: 'expression_config', labels: { fa: 'ساختار فرمول', en: 'Expression Config' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'base', order: 2.2, nature: FieldNature.STANDARD },
    { key: 'config', labels: { fa: 'تنظیمات', en: 'Config' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'base', order: 2.4, nature: FieldNature.STANDARD },
    { key: 'description', labels: { fa: 'توضیحات', en: 'Description' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'base', order: 3, nature: FieldNature.STANDARD },
  ],
  blocks: [
    { id: 'base', titles: { fa: 'اطلاعات فرمول', en: 'Formula Info' }, type: BlockType.FIELD_GROUP, order: 1 },
  ],
  relatedTabs: [],
};
