import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const cashBankOperationsConfig: ModuleDefinition = {
  id: 'cash_bank_operations',
  titles: { fa: 'عملیات نقد و بانک', en: 'Cash & Bank Operations' },
  nature: ModuleNature.FINANCE,
  table: 'cash_bank_operations',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'operation_type',
      labels: { fa: 'نوع عملیات', en: 'Operation Type' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      options: [
        { label: 'دریافت', value: 'receipt', color: 'green' },
        { label: 'پرداخت', value: 'payment', color: 'red' },
      ],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      options: [
        { label: 'در انتظار', value: 'pending', color: 'orange' },
        { label: 'انجام شده', value: 'received', color: 'green' },
        { label: 'برگشت', value: 'returned', color: 'red' },
        { label: 'لغو شده', value: 'canceled', color: 'default' },
      ],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'operation_date',
      labels: { fa: 'تاریخ', en: 'Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'amount',
      labels: { fa: 'مبلغ', en: 'Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'payment_type',
      labels: { fa: 'روش', en: 'Method' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      options: [
        { label: 'نقد', value: 'cash' },
        { label: 'کارت', value: 'card' },
        { label: 'انتقال', value: 'transfer' },
        { label: 'چک', value: 'cheque' },
        { label: 'آنلاین', value: 'online' },
      ],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'bank_account_id',
      labels: { fa: 'حساب بانکی', en: 'Bank Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 1,
      relationConfig: { targetModule: 'bank_accounts', targetField: 'bank_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'sales_invoice_id',
      labels: { fa: 'فاکتور فروش مرتبط', en: 'Sales Invoice' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 2,
      relationConfig: { targetModule: 'invoices', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'purchase_invoice_id',
      labels: { fa: 'فاکتور خرید مرتبط', en: 'Purchase Invoice' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 3,
      relationConfig: { targetModule: 'purchase_invoices', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'customer_id',
      labels: { fa: 'مشتری مرتبط', en: 'Customer' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 4,
      relationConfig: { targetModule: 'customers', targetField: 'last_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'supplier_id',
      labels: { fa: 'تامین‌کننده مرتبط', en: 'Supplier' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 5,
      relationConfig: { targetModule: 'suppliers', targetField: 'business_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'employee_id',
      labels: { fa: 'کارکن مرتبط', en: 'Employee' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 6,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'cheque_id',
      labels: { fa: 'چک مرتبط', en: 'Cheque' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 7,
      relationConfig: { targetModule: 'cheques', targetField: 'serial_no' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'description',
      labels: { fa: 'توضیحات', en: 'Description' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 8,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'attachment_url',
      labels: { fa: 'پیوست', en: 'Attachment' },
      type: FieldType.LINK,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 9,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'relations',
      titles: { fa: 'ارتباطات و جزئیات', en: 'Relations & Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'LinkOutlined',
    },
  ],
  relatedTabs: [],
};
