import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature, LogicOperator } from '../types';
import {
  CASH_BANK_OPERATION_STATUS_OPTIONS,
  CASH_BANK_PAYMENT_TYPE_OPTIONS,
  CASH_BANK_RESPONSIBLE_LABEL_FA,
} from '../utils/cashBankFieldCatalog';

export const cashBankOperationsConfig: ModuleDefinition = {
  id: 'cash_bank_operations',
  titles: { fa: 'نقد و بانک', faSingular: 'رکورد نقد و بانک', en: 'Cash & Bank Operations' },
  nature: ModuleNature.FINANCE,
  table: 'cash_bank_operations',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'image_url',
      labels: { fa: 'تصویر اصلی', en: 'Main Image' },
      type: FieldType.IMAGE,
      location: FieldLocation.HEADER,
      order: 0,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'operation_type',
      labels: { fa: 'نوع عملیات', en: 'Operation Type' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      options: [
        { label: 'دریافت', value: 'receipt', color: 'green' },
        { label: 'پرداخت', value: 'payment', color: 'red' },
        { label: 'انتقال', value: 'transfer', color: 'blue' },
      ],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      options: [...CASH_BANK_OPERATION_STATUS_OPTIONS],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'operation_date',
      labels: { fa: 'تاریخ', en: 'Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'amount',
      labels: { fa: 'مبلغ', en: 'Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'payment_type',
      labels: { fa: 'روش پرداخت', en: 'Payment Method' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      options: [...CASH_BANK_PAYMENT_TYPE_OPTIONS],
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'transfer_fee',
      labels: { fa: 'کارمزد انتقال', en: 'Transfer Fee' },
      type: FieldType.PRICE,
      location: FieldLocation.HEADER,
      order: 5.05,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.EQUALS,
          value: 'payment',
        },
      },
    },
    
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 5.1, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'payment_account_id',
      labels: { fa: 'حساب پرداخت', en: 'Payment Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 1.25,
      relationConfig: {
        targetModule: 'bank_accounts',
        targetField: 'bank_name',
        filter: { is_active: true },
        sourceModules: [
          { targetModule: 'bank_accounts', targetField: 'bank_name', filter: { is_active: true }, tagLabel: 'بانک', tagColor: 'cyan' },
          { targetModule: 'cash_boxes', targetField: 'name', filter: { is_active: true }, tagLabel: 'صندوق', tagColor: 'gold' },
          { targetModule: 'petty_funds', targetField: 'name', filter: { is_active: true }, tagLabel: 'تنخواه', tagColor: 'magenta' },
        ],
      },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'receipt',
        },
      },
    },
    {
      key: 'receipt_account_id',
      labels: { fa: 'حساب دریافت', en: 'Receipt Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 1.75,
      relationConfig: {
        targetModule: 'bank_accounts',
        targetField: 'bank_name',
        filter: { is_active: true },
        sourceModules: [
          { targetModule: 'bank_accounts', targetField: 'bank_name', filter: { is_active: true }, tagLabel: 'بانک', tagColor: 'cyan' },
          { targetModule: 'cash_boxes', targetField: 'name', filter: { is_active: true }, tagLabel: 'صندوق', tagColor: 'gold' },
          { targetModule: 'petty_funds', targetField: 'name', filter: { is_active: true }, tagLabel: 'تنخواه', tagColor: 'magenta' },
        ],
      },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'payment',
        },
      },
    },
    {
      key: 'sales_invoice_id',
      labels: { fa: 'فاکتور فروش مرتبط', en: 'Sales Invoice' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 2,
      relationConfig: { targetModule: 'invoices', targetField: 'name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'purchase_invoice_id',
      labels: { fa: 'فاکتور خرید مرتبط', en: 'Purchase Invoice' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 3,
      relationConfig: { targetModule: 'purchase_invoices', targetField: 'name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'customer_id',
      labels: { fa: 'مشتری مرتبط', en: 'Customer' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 4,
      relationConfig: { targetModule: 'customers', targetField: 'business_name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'expense_document_id',
      labels: { fa: 'هزینه مرتبط', en: 'Expense Document' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 4.5,
      relationConfig: { targetModule: 'expense_documents', targetField: 'name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'supplier_id',
      labels: { fa: 'تامین‌کننده مرتبط', en: 'Supplier' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 5,
      relationConfig: { targetModule: 'suppliers', targetField: 'business_name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'employee_advance_id',
      labels: { fa: 'مساعده مرتبط', en: 'Employee Advance' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 5.5,
      relationConfig: { targetModule: 'employee_advances', targetField: 'name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'assignee_id',
      labels: { fa: CASH_BANK_RESPONSIBLE_LABEL_FA, en: 'Assignee' },
      type: FieldType.USER,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 6,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'payroll_slip_id',
      labels: { fa: 'فیش حقوقی مرتبط', en: 'Payroll Slip' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 6.5,
      relationConfig: { targetModule: 'payroll_slips', targetField: 'name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'cheque_id',
      labels: { fa: 'چک مرتبط', en: 'Cheque' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 7,
      relationConfig: {
        targetModule: 'cheques',
        targetField: 'serial_no',
        quickCreateFieldKeys: ['serial_no', 'sayad_id', 'issue_date', 'due_date', 'amount', 'payee_name', 'account_holder_name', 'bank_name', 'image_url'],
      },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'barter_id',
      labels: { fa: 'تهاتر مرتبط', en: 'Barter' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 8,
      relationConfig: { targetModule: 'barters', targetField: 'name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      logic: {
        visibleIf: {
          field: 'operation_type',
          operator: LogicOperator.NOT_EQUALS,
          value: 'transfer',
        },
      },
    },
    {
      key: 'description',
      labels: { fa: 'توضیحات', en: 'Description' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 9,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'attachment_url',
      labels: { fa: 'پیوست', en: 'Attachment' },
      type: FieldType.IMAGE,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 10,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'relations',
      titles: { fa: 'ارتباطات و جزئیات', en: 'Relations & Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'LinkOutlined',
    },
  ],
  relatedTabs: [],
  actionButtons: [{ id: 'create_journal_entry', label: 'صدور سند دستی', placement: 'header', variant: 'primary' }],
};
