import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const cashBoxesConfig: ModuleDefinition = {
  id: 'cash_boxes',
  titles: { fa: 'صندوق ها', en: 'Cash Boxes' },
  nature: ModuleNature.FINANCE,
  table: 'cash_boxes',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'code',
      labels: { fa: 'کد صندوق', en: 'Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'name',
      labels: { fa: 'نام صندوق', en: 'Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      isKey: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'account_id',
      labels: { fa: 'حساب متناظر', en: 'Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 1,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'responsible_id',
      labels: { fa: 'مسئول صندوق', en: 'Responsible' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 2,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
    },
    {
      key: 'opening_balance',
      labels: { fa: 'موجودی اول دوره', en: 'Opening Balance' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Is Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'base',
      titles: { fa: 'اطلاعات صندوق', en: 'Cash Box Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'WalletOutlined',
    },
  ],
  relatedTabs: [],
};
