import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const chartOfAccountsConfig: ModuleDefinition = {
  id: 'chart_of_accounts',
  titles: { fa: 'جدول حساب ها', en: 'Chart Of Accounts' },
  nature: ModuleNature.FINANCE,
  table: 'chart_of_accounts',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'code',
      labels: { fa: 'کد حساب', en: 'Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isTableColumn: true,
      isKey: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'name',
      labels: { fa: 'نام حساب', en: 'Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'account_type',
      labels: { fa: 'نوع حساب', en: 'Account Type' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
      options: [
        { label: 'دارایی', value: 'asset', color: 'blue' },
        { label: 'بدهی', value: 'liability', color: 'orange' },
        { label: 'سرمایه', value: 'equity', color: 'purple' },
        { label: 'درآمد', value: 'income', color: 'green' },
        { label: 'هزینه', value: 'expense', color: 'red' },
      ],
    },
    {
      key: 'account_level',
      labels: { fa: 'سطح حساب', en: 'Level' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'structure',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      options: [
        { label: 'گروه', value: 'group' },
        { label: 'کل', value: 'general' },
        { label: 'معین', value: 'subsidiary' },
        { label: 'تفصیلی', value: 'detail' },
      ],
    },
    {
      key: 'nature',
      labels: { fa: 'ماهیت', en: 'Nature' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'structure',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      options: [
        { label: 'بدهکار', value: 'debit' },
        { label: 'بستانکار', value: 'credit' },
        { label: 'خنثی', value: 'none' },
      ],
    },
    {
      key: 'parent_id',
      labels: { fa: 'حساب والد', en: 'Parent Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'structure',
      order: 3,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'is_leaf',
      labels: { fa: 'حساب نهایی', en: 'Is Leaf' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'status',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Is Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'status',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_system',
      labels: { fa: 'سیستمی', en: 'Is System' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'status',
      order: 3,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: 'structure',
      titles: { fa: 'ساختار حساب', en: 'Structure' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'NodeIndexOutlined',
    },
    {
      id: 'status',
      titles: { fa: 'وضعیت', en: 'Status' },
      type: BlockType.FIELD_GROUP,
      order: 2,
      icon: 'CheckCircleOutlined',
    },
  ],
  relatedTabs: [],
};
