import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const chequesConfig: ModuleDefinition = {
  id: 'cheques',
  titles: { fa: 'چک ها', en: 'Cheques' },
  nature: ModuleNature.FINANCE,
  table: 'cheques',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'cheque_type',
      labels: { fa: 'نوع چک', en: 'Type' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
      options: [
        { label: 'دریافتی', value: 'received', color: 'blue' },
        { label: 'پرداختی', value: 'issued', color: 'orange' },
      ],
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
      options: [
        { label: 'جدید', value: 'new', color: 'blue' },
        { label: 'در بانک', value: 'in_bank', color: 'orange' },
        { label: 'وصول شده', value: 'cleared', color: 'green' },
        { label: 'برگشتی', value: 'bounced', color: 'red' },
        { label: 'عودت شده', value: 'returned', color: 'purple' },
        { label: 'ابطال شده', value: 'canceled', color: 'default' },
      ],
    },
    {
      key: 'serial_no',
      labels: { fa: 'شماره چک', en: 'Cheque Number' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      validation: { required: true },
    },
    {
      key: 'sayad_id',
      labels: { fa: 'شناسه صیادی', en: 'Sayad ID' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 4,
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      validation: { required: true },
    },
    {
      key: 'issue_date',
      labels: { fa: 'تاریخ چک', en: 'Cheque Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      validation: { required: true },
    },
    {
      key: 'amount',
      labels: { fa: 'مبلغ', en: 'Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
      validation: { required: true },
    },
    {
      key: 'payee_name',
      labels: { fa: 'در وجه', en: 'Payee Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      validation: { required: true },
    },
    {
      key: 'payee_identifier',
      labels: { fa: 'کد ملی / شناسه ملی', en: 'National ID' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 3,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'bank_name',
      labels: { fa: 'نام بانک', en: 'Bank Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      validation: { required: true },
    },
    {
      key: 'branch_name',
      labels: { fa: 'نام شعبه', en: 'Branch Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'branch_code',
      labels: { fa: 'کد شعبه', en: 'Branch Code' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 6,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'account_holder_name',
      labels: { fa: 'نام صاحب حساب', en: 'Account Holder' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 7,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'توضیحات', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 8,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'image_url',
      labels: { fa: 'تصویر چک', en: 'Cheque Image' },
      type: FieldType.IMAGE,
      location: FieldLocation.BLOCK,
      blockId: 'issuance',
      order: 9,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'issuance',
      titles: { fa: 'اطلاعات ثابت چک', en: 'Cheque Core Fields' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'CreditCardOutlined',
    },
  ],
  relatedTabs: [],
};
