import { BlockType, FieldLocation, FieldNature, FieldType, LogicOperator, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const counterpartyBotGroupsConfig: ModuleDefinition = {
  id: 'counterparty_bot_groups',
  titles: { fa: 'گروه‌های بات طرف‌حساب', faSingular: 'گروه بات طرف‌حساب', en: 'Counterparty Bot Groups' },
  nature: ModuleNature.CRM,
  table: 'counterparty_bot_groups',
  supportedViewModes: [ViewMode.LIST, ViewMode.KANBAN],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: '{{group_title}} - {{channel_type}}',
    searchFields: ['target_type', 'group_title', 'group_join_link', 'group_platform_id', 'bot_chat_id', 'status', 'id'],
  },
  fields: [
    {
      key: 'target_type',
      labels: { fa: 'نوع طرف‌حساب', en: 'Counterparty Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      options: [
        { label: 'مشتری', value: 'customers' },
        { label: 'تامین‌کننده', value: 'suppliers' },
      ],
      defaultValue: 'customers',
      validation: { required: true },
    },
    {
      key: 'customer_id',
      labels: { fa: 'مشتری', en: 'Customer' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1.1,
      isTableColumn: true,
      relationConfig: {
        targetModule: 'customers',
        targetField: 'full_name',
      },
      logic: { visibleIf: { field: 'target_type', operator: LogicOperator.EQUALS, value: 'customers' } },
    },
    {
      key: 'supplier_id',
      labels: { fa: 'تامین‌کننده', en: 'Supplier' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1.15,
      isTableColumn: true,
      relationConfig: {
        targetModule: 'suppliers',
        targetField: 'business_name',
      },
      logic: { visibleIf: { field: 'target_type', operator: LogicOperator.EQUALS, value: 'suppliers' } },
    },
    {
      key: 'channel_type',
      labels: { fa: 'پلتفرم بات', en: 'Channel' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1.2,
      isTableColumn: true,
      options: [
        { label: 'روبیکا', value: 'rubika', color: 'orange' },
        { label: 'تلگرام', value: 'telegram', color: 'blue' },
        { label: 'بله', value: 'bale', color: 'green' },
      ],
      defaultValue: 'rubika',
      validation: { required: true },
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت اتصال', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1.3,
      isTableColumn: true,
      options: [
        { label: 'در انتظار لینک', value: 'pending_join_link', color: 'gold' },
        { label: 'در انتظار عضویت', value: 'pending_join', color: 'orange' },
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'غیرفعال', value: 'disabled', color: 'gray' },
        { label: 'خطا', value: 'error', color: 'red' },
      ],
      defaultValue: 'pending_join_link',
    },
    {
      key: 'group_join_link',
      labels: { fa: 'لینک جوین گروه', en: 'Join Link' },
      type: FieldType.LINK,
      blockId: 'connection_info',
      order: 2,
      isTableColumn: true,
    },
    {
      key: 'group_platform_id',
      labels: { fa: 'شناسه گروه پلتفرم', en: 'Platform Group Id' },
      type: FieldType.TEXT,
      blockId: 'connection_info',
      order: 2.1,
      isTableColumn: true,
    },
    {
      key: 'bot_chat_id',
      labels: { fa: 'چت‌آیدی/گیرنده بات', en: 'Bot Chat Id' },
      type: FieldType.TEXT,
      blockId: 'connection_info',
      order: 2.2,
      isTableColumn: true,
    },
    {
      key: 'group_title',
      labels: { fa: 'عنوان گروه', en: 'Group Title' },
      type: FieldType.TEXT,
      blockId: 'connection_info',
      order: 2.3,
      isTableColumn: true,
    },
    {
      key: 'last_inbound_at',
      labels: { fa: 'آخرین پیام ورودی', en: 'Last Inbound' },
      type: FieldType.DATETIME,
      blockId: 'telemetry',
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'last_outbound_at',
      labels: { fa: 'آخرین پیام خروجی', en: 'Last Outbound' },
      type: FieldType.DATETIME,
      blockId: 'telemetry',
      order: 3.1,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'last_error',
      labels: { fa: 'آخرین خطا', en: 'Last Error' },
      type: FieldType.LONG_TEXT,
      blockId: 'telemetry',
      order: 3.2,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'metadata',
      labels: { fa: 'فراداده', en: 'Metadata' },
      type: FieldType.JSON,
      blockId: 'telemetry',
      order: 3.3,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 1.4, nature: FieldNature.STANDARD, isTableColumn: true },
],
  blocks: [
    {
      id: 'connection_info',
      titles: { fa: 'اطلاعات اتصال', en: 'Connection' },
      type: BlockType.FIELD_GROUP,
      order: 0,
    },
    {
      id: 'telemetry',
      titles: { fa: 'پایش', en: 'Telemetry' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
};
