import { BlockType, FieldLocation, FieldNature, FieldType, LogicOperator, ModuleDefinition, ModuleNature, ViewMode } from '../types';

const RELATED_MODULE_OPTIONS = [
  { label: 'تردد کالاها', value: 'stock_transfers' },
  { label: 'دبیرخانه', value: 'secretariat_documents' },
  { label: 'فاکتور فروش', value: 'invoices' },
  { label: 'فاکتور خرید', value: 'purchase_invoices' },
  { label: 'پروژه‌ها', value: 'projects' },
  { label: 'فعالیت ها', value: 'tasks' },
  { label: 'کارکنان', value: 'employees' },
  { label: 'اموال', value: 'assets' },
];

export const deliveryFormsConfig: ModuleDefinition = {
  id: 'delivery_forms',
  titles: { fa: 'فرم‌های تحویل', faSingular: 'فرم تحویل', en: 'Delivery Forms' },
  nature: ModuleNature.STANDARD,
  table: 'delivery_forms',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: '{{system_code}} - {{name}}',
    searchFields: ['name', 'system_code', 'location_text'],
  },
  fields: [
    { key: 'name', labels: { fa: 'عنوان فرم', en: 'Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'شماره فرم', en: 'Form No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'public_link', labels: { fa: 'لینک تحویل آنلاین', en: 'Online Delivery Link' }, type: FieldType.LINK, location: FieldLocation.BLOCK, blockId: 'onlineDelivery', order: 1, readonly: true, nature: FieldNature.STANDARD, hideInCreateForm: true },
    {
      key: 'form_type',
      labels: { fa: 'نوع فرم', en: 'Form Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'goods_delivery',
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
      options: [
        { label: 'تحویل کالا', value: 'goods_delivery' },
        { label: 'رسید کالا', value: 'goods_receipt' },
        { label: 'تحویل سند', value: 'document_delivery' },
        { label: 'رسید سند', value: 'document_receipt' },
        { label: 'تحویل دارایی', value: 'asset_delivery' },
        { label: 'سایر', value: 'other' },
      ],
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 'draft',
      validation: { required: true },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'در انتظار امضا', value: 'pending_signature', color: 'orange' },
        { label: 'امضا شده', value: 'signed', color: 'blue' },
        { label: 'تایید شده', value: 'confirmed', color: 'green' },
        { label: 'بایگانی', value: 'archived', color: 'gray' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
      ],
    },
    { key: 'delivery_date', labels: { fa: 'زمان تحویل', en: 'Delivery Time' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 5, validation: { required: true }, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'delivered_by_type',
      labels: { fa: 'نوع تحویل‌دهنده', en: 'Delivered By Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 6,
      defaultValue: 'internal',
      options: [
        { label: 'داخلی', value: 'internal' },
        { label: 'مشتری', value: 'customer' },
        { label: 'تامین‌کننده', value: 'supplier' },
        { label: 'سایر (بیرونی)', value: 'other' },
      ],
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    { key: 'delivered_by_employee_id', labels: { fa: 'تحویل‌دهنده', en: 'Delivered By' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 6.1, relationConfig: { targetModule: 'employees', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true, logic: { visibleIf: { field: 'delivered_by_type', operator: LogicOperator.EQUALS, value: 'internal' } } },
    { key: 'delivered_by_customer_id', labels: { fa: 'تحویل‌دهنده', en: 'Delivered By' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 6.2, relationConfig: { targetModule: 'customers', targetField: 'full_name' }, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'delivered_by_type', operator: LogicOperator.EQUALS, value: 'customer' } } },
    { key: 'delivered_by_supplier_id', labels: { fa: 'تحویل‌دهنده', en: 'Delivered By' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 6.3, relationConfig: { targetModule: 'suppliers', targetField: 'business_name' }, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'delivered_by_type', operator: LogicOperator.EQUALS, value: 'supplier' } } },
    { key: 'external_delivered_by', labels: { fa: 'تحویل‌دهنده', en: 'External Delivered By' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 6.4, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'delivered_by_type', operator: LogicOperator.EQUALS, value: 'other' } } },
    { key: 'external_delivered_by_phone', labels: { fa: 'موبایل تحویل‌دهنده', en: 'Delivered By Mobile' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 6.5, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'delivered_by_type', operator: LogicOperator.EQUALS, value: 'other' } } },
    {
      key: 'received_by_type',
      labels: { fa: 'نوع تحویل‌گیرنده', en: 'Received By Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 7,
      defaultValue: 'internal',
      options: [
        { label: 'داخلی', value: 'internal' },
        { label: 'مشتری', value: 'customer' },
        { label: 'تامین‌کننده', value: 'supplier' },
        { label: 'سایر (بیرونی)', value: 'other' },
      ],
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    { key: 'received_by_employee_id', labels: { fa: 'تحویل‌گیرنده', en: 'Received By' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 7.1, relationConfig: { targetModule: 'employees', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true, logic: { visibleIf: { field: 'received_by_type', operator: LogicOperator.EQUALS, value: 'internal' } } },
    { key: 'received_by_customer_id', labels: { fa: 'تحویل‌گیرنده', en: 'Received By' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 7.2, relationConfig: { targetModule: 'customers', targetField: 'full_name' }, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'received_by_type', operator: LogicOperator.EQUALS, value: 'customer' } } },
    { key: 'received_by_supplier_id', labels: { fa: 'تحویل‌گیرنده', en: 'Received By' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 7.3, relationConfig: { targetModule: 'suppliers', targetField: 'business_name' }, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'received_by_type', operator: LogicOperator.EQUALS, value: 'supplier' } } },
    { key: 'external_received_by', labels: { fa: 'تحویل‌گیرنده', en: 'External Received By' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 7.4, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'received_by_type', operator: LogicOperator.EQUALS, value: 'other' } } },
    { key: 'external_received_by_phone', labels: { fa: 'موبایل تحویل‌گیرنده', en: 'Received By Mobile' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 7.5, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'received_by_type', operator: LogicOperator.EQUALS, value: 'other' } } },
    { key: 'assignee_id', labels: { fa: 'مسئول پیگیری', en: 'Assignee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 8, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'delivered_by_id', labels: { fa: 'تحویل‌دهنده داخلی قدیمی', en: 'Legacy Delivered By' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'details', order: 0.1, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, hideInCreateForm: true },
    { key: 'received_by_id', labels: { fa: 'تحویل‌گیرنده داخلی قدیمی', en: 'Legacy Received By' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'details', order: 0.2, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, hideInCreateForm: true },
    { key: 'location_text', labels: { fa: 'محل تحویل', en: 'Location' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 3, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'storage_location', labels: { fa: 'محل نگهداری', en: 'Storage Location' }, type: FieldType.SELECT, dynamicOptionsCategory: 'asset_storage_location', location: FieldLocation.BLOCK, blockId: 'details', order: 3.1, nature: FieldNature.STANDARD, logic: { visibleIf: { field: 'form_type', operator: LogicOperator.EQUALS, value: 'asset_delivery' } } },
    { key: 'related_module_id', labels: { fa: 'مرتبط با بخش', en: 'Related Module' }, type: FieldType.SELECT, location: FieldLocation.BLOCK, blockId: 'details', order: 4, options: RELATED_MODULE_OPTIONS, nature: FieldNature.STANDARD },
    { key: 'related_record_id', labels: { fa: 'رکورد مرتبط', en: 'Related Record' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'details', order: 5, relationConfig: { targetModule: '', dependsOn: 'related_module_id' }, nature: FieldNature.STANDARD },
    { key: 'notes', labels: { fa: 'یادداشت‌ها و شرایط تحویل', en: 'Notes' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'notes', order: 1, nature: FieldNature.STANDARD },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 2, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
    { key: 'delivered_by_confirmed_at', labels: { fa: 'زمان تایید تحویل‌دهنده', en: 'Delivered By Confirmed At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'onlineDelivery', order: 2, readonly: true, nature: FieldNature.STANDARD, hideInCreateForm: true },
    { key: 'delivered_by_confirmer_name', labels: { fa: 'تاییدکننده تحویل‌دهنده', en: 'Delivered By Confirmer' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'onlineDelivery', order: 3, readonly: true, nature: FieldNature.STANDARD, hideInCreateForm: true },
    { key: 'received_by_confirmed_at', labels: { fa: 'زمان تایید تحویل‌گیرنده', en: 'Received By Confirmed At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'onlineDelivery', order: 4, readonly: true, nature: FieldNature.STANDARD, hideInCreateForm: true },
    { key: 'received_by_confirmer_name', labels: { fa: 'تاییدکننده تحویل‌گیرنده', en: 'Received By Confirmer' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'onlineDelivery', order: 5, readonly: true, nature: FieldNature.STANDARD, hideInCreateForm: true },
  ],
  blocks: [
    { id: 'details', titles: { fa: 'جزئیات تحویل', en: 'Delivery Details' }, type: BlockType.FIELD_GROUP, order: 1, icon: 'ProfileOutlined' },
    {
      id: 'items',
      titles: { fa: 'اقلام تحویل', en: 'Delivery Items' },
      type: BlockType.TABLE,
      order: 2,
      icon: 'AppstoreOutlined',
      tableColumns: [
        { key: 'asset_id', title: 'مال', type: FieldType.RELATION, width: 220, relationConfig: { targetModule: 'assets', targetField: 'name' } },
        { key: 'product_id', title: 'کالا/خدمت', type: FieldType.RELATION, width: 220, relationConfig: { targetModule: 'products', targetField: 'name' } },
        { key: 'title', title: 'شرح قلم', type: FieldType.TEXT, width: 220 },
        { key: 'quantity', title: 'تعداد/مقدار', type: FieldType.NUMBER, width: 120 },
        { key: 'unit', title: 'واحد', type: FieldType.TEXT, width: 100 },
        { key: 'serial_no', title: 'شماره/سریال', type: FieldType.TEXT, width: 150 },
        { key: 'description', title: 'توضیحات', type: FieldType.LONG_TEXT, width: 240 },
      ],
    },
    { id: 'notes', titles: { fa: 'یادداشت‌ها', en: 'Notes' }, type: BlockType.FIELD_GROUP, order: 3, icon: 'FileTextOutlined' },
    { id: 'process', titles: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: BlockType.FIELD_GROUP, order: 4, icon: 'DeploymentUnitOutlined' },
    { id: 'onlineDelivery', titles: { fa: 'تحویل آنلاین', en: 'Online Delivery' }, type: BlockType.FIELD_GROUP, order: 5, icon: 'LinkOutlined' },
  ],
  relatedTabs: [
    {
      id: 'delivery_form_stock_transfers',
      title: 'تردد کالاها',
      icon: 'SwapOutlined',
      targetModule: 'stock_transfers',
      foreignKey: 'delivery_form_id',
    },
  ],
};
