import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  LogicOperator,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';
import {
  DEFAULT_SALARY_TYPE,
  COMMISSION_SALARY_TYPE_VALUES,
  FIXED_BASE_SALARY_TYPE_VALUES,
  PERFORMANCE_SALARY_TYPE_VALUES,
  PROFIT_SHARE_SALARY_TYPE_VALUES,
  SALARY_TYPE_OPTIONS,
} from '../utils/payrollSalaryType';
import { createWebFormTemplateRecordSaver } from '../utils/webFormTemplateFormAdapter';
import { JOB_DESCRIPTION_POPULATE_FIELDS } from './jobDescriptionsConfig';

const saveEmployeeRecord = createWebFormTemplateRecordSaver({
  moduleId: 'employees',
  table: 'employees',
});

export const employeesModule: ModuleDefinition = {
  id: 'employees',
  titles: { fa: 'کارکنان', faSingular: 'کارمند', en: 'Employees' },
  nature: ModuleNature.STANDARD,
  relationDisplay: {
    labelTemplate: '{{prefix}} {{first_name}} {{last_name}} - {{legacy_system_code}}',
    searchFields: ['full_name', 'first_name', 'last_name', 'legacy_system_code', 'system_code', 'national_code', 'mobile_1', 'phone', 'id'],
  },
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  table: 'employees',
  formAdapter: {
    save: saveEmployeeRecord,
  },
  fields: [
    { key: 'image_url', labels: { fa: 'تصویر', en: 'Image' }, type: FieldType.IMAGE, location: FieldLocation.HEADER, order: 0.8 },
    { key: 'prefix', labels: { fa: 'پیشوند', en: 'Prefix' }, type: FieldType.SELECT, location: FieldLocation.HEADER, order: 1, options: [{ label: 'آقای', value: 'آقای' }, { label: 'خانم', value: 'خانم' }, { label: 'آقای دکتر', value: 'آقای دکتر' }, { label: 'خانم دکتر', value: 'خانم دکتر' }, { label: 'آقای مهندس', value: 'آقای مهندس' }, { label: 'خانم مهندس', value: 'خانم مهندس' }] },
    { key: 'first_name', labels: { fa: 'نام', en: 'First Name' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1.1, isTableColumn: true, isKey: true },
    { key: 'last_name', labels: { fa: 'نام خانوادگی', en: 'Last Name' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1.2, isTableColumn: true },
    { key: 'legacy_system_code', labels: { fa: 'کد سیستم قبلی', en: 'Legacy System Code' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1.3, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'کد پرسنلی', en: 'Employee Code' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1.4, isTableColumn: true },
    {
      key: 'employment_status',
      labels: { fa: 'وضعیت همکاری', en: 'Employment Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1.5,
      isTableColumn: true,
      defaultValue: 'active',
      options: [
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'غیرفعال', value: 'inactive', color: 'default' },
        { label: 'تعلیق', value: 'suspended', color: 'orange' },
        { label: 'قطع همکاری', value: 'terminated', color: 'red' },
      ],
    },
    { key: 'job_title', labels: { fa: 'عنوان شغلی', en: 'Job Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1.6, isTableColumn: true },
    {
      key: 'persona_id',
      labels: { fa: 'پرسونا', en: 'Persona' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1.65,
      relationConfig: {
        targetModule: 'personas',
        targetField: 'display_name',
        filter: { persona_type: 'employee' },
      },
      isTableColumn: true,
    },
    { key: 'mobile_1', labels: { fa: 'موبایل', en: 'Mobile' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 1.7, isTableColumn: true },
    {
      key: 'survey_template_id',
      labels: { fa: 'قالب وب‌فرم', en: 'Web Form Template' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1.71,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      relationConfig: {
        targetModule: 'web_forms',
        filter: {
          target_module_id: 'employees',
          is_active: true,
        },
      },
    },

    {
      key: 'related_profile_id',
      labels: { fa: 'کاربر مرتبط', en: 'Related User' },
      type: FieldType.RELATION,
      blockId: 'identity_info',
      order: 2,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
    },
    { key: 'is_customer', labels: { fa: 'این کارمند مشتری هم هست', en: 'Also Customer' }, type: FieldType.CHECKBOX, blockId: 'identity_info', order: 2.02 },
    {
      key: 'linked_customer_id',
      labels: { fa: 'مشتری مرتبط', en: 'Related Customer' },
      type: FieldType.RELATION,
      blockId: 'identity_info',
      order: 2.03,
      relationConfig: { targetModule: 'customers', targetField: 'full_name' },
      logic: { visibleIf: { field: 'is_customer', operator: LogicOperator.IS_TRUE } },
    },
    { key: 'is_supplier', labels: { fa: 'این کارمند تامین‌کننده هم هست', en: 'Also Supplier' }, type: FieldType.CHECKBOX, blockId: 'identity_info', order: 2.04 },
    {
      key: 'linked_supplier_id',
      labels: { fa: 'تامین‌کننده مرتبط', en: 'Related Supplier' },
      type: FieldType.RELATION,
      blockId: 'identity_info',
      order: 2.05,
      relationConfig: { targetModule: 'suppliers', targetField: 'business_name' },
      logic: { visibleIf: { field: 'is_supplier', operator: LogicOperator.IS_TRUE } },
    },
    {
      key: 'employment_type',
      labels: { fa: 'نوع همکاری', en: 'Employment Type' },
      type: FieldType.SELECT,
      blockId: 'identity_info',
      order: 2.1,
      isTableColumn: true,
      options: [
        { label: 'تمام وقت', value: 'full_time' },
        { label: 'پاره وقت', value: 'part_time' },
        { label: 'پروژه‌ای', value: 'project_based' },
        { label: 'ساعتی', value: 'hourly' },
        { label: 'پورسانتی', value: 'commission' },
      ],
    },
    { key: 'department', labels: { fa: 'واحد سازمانی', en: 'Department' }, type: FieldType.SELECT, blockId: 'identity_info', order: 2.2, dynamicOptionsCategory: 'employee_departments', isTableColumn: true },
    { key: 'team', labels: { fa: 'تیم', en: 'Team' }, type: FieldType.SELECT, blockId: 'identity_info', order: 2.3, dynamicOptionsCategory: 'employee_teams' },
    { key: 'hire_date', labels: { fa: 'تاریخ شروع همکاری', en: 'Hire Date' }, type: FieldType.DATE, blockId: 'identity_info', order: 2.4, isTableColumn: true },
    { key: 'termination_date', labels: { fa: 'تاریخ پایان همکاری', en: 'Termination Date' }, type: FieldType.DATE, blockId: 'identity_info', order: 2.5, logic: { visibleIf: { field: 'employment_status', operator: LogicOperator.EQUALS, value: 'terminated' } } },

    { key: 'national_code', labels: { fa: 'کد ملی', en: 'National Code' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3 },
    { key: 'birth_date', labels: { fa: 'تاریخ تولد', en: 'Birth Date' }, type: FieldType.DATE, blockId: 'legal_info', order: 3.1 },
    { key: 'issued_from', labels: { fa: 'صادره از', en: 'Issued From' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3.15 },
    {
      key: 'gender',
      labels: { fa: 'جنسیت', en: 'Gender' },
      type: FieldType.SELECT,
      blockId: 'legal_info',
      order: 3.2,
      options: [
        { label: 'مرد', value: 'male' },
        { label: 'زن', value: 'female' },
      ],
    },
    { key: 'father_name', labels: { fa: 'نام پدر', en: 'Father Name' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3.3 },
    { key: 'birth_certificate_number', labels: { fa: 'شماره شناسنامه', en: 'Birth Certificate No.' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3.4 },
    {
      key: 'marital_status',
      labels: { fa: 'وضعیت تاهل', en: 'Marital Status' },
      type: FieldType.SELECT,
      blockId: 'legal_info',
      order: 3.5,
      options: [
        { label: 'مجرد', value: 'single' },
        { label: 'متاهل', value: 'married' },
      ],
    },
    { key: 'children_count', labels: { fa: 'تعداد فرزند', en: 'Children Count' }, type: FieldType.NUMBER, blockId: 'legal_info', order: 3.6, defaultValue: 0 },
    {
      key: 'military_service_status',
      labels: { fa: 'وضعیت نظام وظیفه', en: 'Military Service Status' },
      type: FieldType.SELECT,
      blockId: 'legal_info',
      order: 3.7,
      options: [
        { label: 'مشمول نیست', value: 'not_applicable' },
        { label: 'پایان خدمت', value: 'completed' },
        { label: 'معافیت دائم', value: 'permanent_exemption' },
        { label: 'معافیت موقت', value: 'temporary_exemption' },
        { label: 'در حال خدمت', value: 'serving' },
        { label: 'مشمول', value: 'eligible' },
      ],
    },
    { key: 'insurance_number', labels: { fa: 'شماره بیمه', en: 'Insurance No.' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3.8 },

    { key: 'mobile_2', labels: { fa: 'موبایل دوم', en: 'Mobile 2' }, type: FieldType.PHONE, blockId: 'contact_info', order: 4 },
    { key: 'phone', labels: { fa: 'تلفن ثابت', en: 'Phone' }, type: FieldType.PHONE, blockId: 'contact_info', order: 4.1 },
    { key: 'email', labels: { fa: 'ایمیل', en: 'Email' }, type: FieldType.TEXT, blockId: 'contact_info', order: 4.2 },
    { key: 'province', labels: { fa: 'استان', en: 'Province' }, type: FieldType.SELECT, blockId: 'contact_info', order: 4.3, dynamicOptionsCategory: 'provinces' },
    { key: 'city', labels: { fa: 'شهر', en: 'City' }, type: FieldType.SELECT, blockId: 'contact_info', order: 4.4, dynamicOptionsCategory: 'cities' },
    { key: 'address', labels: { fa: 'آدرس', en: 'Address' }, type: FieldType.LONG_TEXT, blockId: 'contact_info', order: 4.5 },
    { key: 'family_contact_name', labels: { fa: 'نام یکی از اعضای خانواده', en: 'Family Contact Name' }, type: FieldType.TEXT, blockId: 'contact_info', order: 4.6 },
    { key: 'family_contact_phone', labels: { fa: 'تلفن یکی از اعضای خانواده', en: 'Family Contact Phone' }, type: FieldType.PHONE, blockId: 'contact_info', order: 4.7 },
    { key: 'acquaintance_contact_name', labels: { fa: 'نام یکی از آشنایان', en: 'Acquaintance Contact Name' }, type: FieldType.TEXT, blockId: 'contact_info', order: 4.8 },
    { key: 'acquaintance_contact_phone', labels: { fa: 'تلفن یکی از آشنایان', en: 'Acquaintance Contact Phone' }, type: FieldType.PHONE, blockId: 'contact_info', order: 4.9 },
    { key: 'telegram_chat_id', labels: { fa: 'شناسه چت تلگرام', en: 'Telegram Chat Id' }, type: FieldType.TEXT, blockId: 'bot_info', order: 4.91, botSettingsOnly: true },
    { key: 'bale_chat_id', labels: { fa: 'شناسه چت بله', en: 'Bale Chat Id' }, type: FieldType.TEXT, blockId: 'bot_info', order: 4.92, botSettingsOnly: true },
    { key: 'rubika_chat_id', labels: { fa: 'شناسه چت روبیکا', en: 'Rubika Chat Id' }, type: FieldType.TEXT, blockId: 'bot_info', order: 4.93, botSettingsOnly: true },
    {
      key: 'bot_default_channel',
      labels: { fa: 'پلتفرم اصلی بات', en: 'Bot Default Channel' },
      type: FieldType.SELECT,
      blockId: 'bot_info',
      order: 4.94,
      botSettingsOnly: true,
      virtualBotField: true,
      options: [
        { label: 'روبیکا', value: 'rubika' },
        { label: 'تلگرام', value: 'telegram' },
        { label: 'بله', value: 'bale' },
        { label: 'بدون بات', value: 'none' },
      ],
      defaultValue: 'none',
    },
    { key: 'telegram_group_join_link', labels: { fa: 'لینک گروه تلگرام', en: 'Telegram Group Join Link' }, type: FieldType.LINK, blockId: 'bot_info', order: 4.95, botSettingsOnly: true, virtualBotField: true },
    { key: 'bale_group_join_link', labels: { fa: 'لینک گروه بله', en: 'Bale Group Join Link' }, type: FieldType.LINK, blockId: 'bot_info', order: 4.96, botSettingsOnly: true, virtualBotField: true },
    { key: 'rubika_group_join_link', labels: { fa: 'لینک گروه روبیکا', en: 'Rubika Group Join Link' }, type: FieldType.LINK, blockId: 'bot_info', order: 4.97, botSettingsOnly: true, virtualBotField: true },
    {
      key: 'telegram_group_status',
      labels: { fa: 'وضعیت گروه تلگرام', en: 'Telegram Group Status' },
      type: FieldType.STATUS,
      blockId: 'bot_info',
      order: 4.971,
      botSettingsOnly: true,
      virtualBotField: true,
      options: [
        { label: 'در انتظار پیام', value: 'pending_join', color: 'orange' },
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'غیرفعال', value: 'disabled', color: 'gray' },
        { label: 'خطا', value: 'error', color: 'red' },
      ],
    },
    {
      key: 'bale_group_status',
      labels: { fa: 'وضعیت گروه بله', en: 'Bale Group Status' },
      type: FieldType.STATUS,
      blockId: 'bot_info',
      order: 4.972,
      botSettingsOnly: true,
      virtualBotField: true,
      options: [
        { label: 'در انتظار پیام', value: 'pending_join', color: 'orange' },
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'غیرفعال', value: 'disabled', color: 'gray' },
        { label: 'خطا', value: 'error', color: 'red' },
      ],
    },
    {
      key: 'rubika_group_status',
      labels: { fa: 'وضعیت گروه روبیکا', en: 'Rubika Group Status' },
      type: FieldType.STATUS,
      blockId: 'bot_info',
      order: 4.973,
      botSettingsOnly: true,
      virtualBotField: true,
      options: [
        { label: 'در انتظار پیام', value: 'pending_join', color: 'orange' },
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'غیرفعال', value: 'disabled', color: 'gray' },
        { label: 'خطا', value: 'error', color: 'red' },
      ],
    },
    { key: 'telegram_group_title', labels: { fa: 'عنوان گروه تلگرام', en: 'Telegram Group Title' }, type: FieldType.TEXT, blockId: 'bot_info', order: 4.974, botSettingsOnly: true, virtualBotField: true },
    { key: 'bale_group_title', labels: { fa: 'عنوان گروه بله', en: 'Bale Group Title' }, type: FieldType.TEXT, blockId: 'bot_info', order: 4.975, botSettingsOnly: true, virtualBotField: true },
    { key: 'rubika_group_title', labels: { fa: 'عنوان گروه روبیکا', en: 'Rubika Group Title' }, type: FieldType.TEXT, blockId: 'bot_info', order: 4.976, botSettingsOnly: true, virtualBotField: true },
    {
      key: 'default_work_schedule_id',
      labels: { fa: 'برنامه حضور پیش‌فرض', en: 'Default Work Schedule' },
      type: FieldType.RELATION,
      blockId: 'attendance_policy_info',
      order: 5,
      relationConfig: { targetModule: 'work_schedules', targetField: 'title' },
    },
    { key: 'has_flexible_hours', labels: { fa: 'ساعت کاری شناور', en: 'Flexible Hours' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5.1, defaultValue: false },
    { key: 'works_on_official_holidays', labels: { fa: 'کار در روزهای تعطیل', en: 'Works on Official Holidays' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5.2, defaultValue: false },
    { key: 'expected_daily_minutes', labels: { fa: 'دقایق کار روزانه', en: 'Expected Daily Minutes' }, type: FieldType.NUMBER, blockId: 'attendance_policy_info', order: 5.3, defaultValue: 480 },
    { key: 'grace_minutes_for_late', labels: { fa: 'تلورانس تاخیر (دقیقه)', en: 'Late Grace Minutes' }, type: FieldType.NUMBER, blockId: 'attendance_policy_info', order: 5.4, defaultValue: 0 },
    { key: 'overtime_auto_approve', labels: { fa: 'اضافه‌کاری بدون نیاز به تایید', en: 'Auto Approve Overtime' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5.5, defaultValue: false },
    { key: 'leave_auto_approve', labels: { fa: 'مرخصی بدون نیاز به تایید', en: 'Auto Approve Leave' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5.6, defaultValue: false },
    { key: 'mission_auto_approve', labels: { fa: 'ماموریت بدون نیاز به تایید', en: 'Auto Approve Mission' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5.7, defaultValue: false },

    {
      key: 'salary_type',
      labels: { fa: 'نوع محاسبه حقوق', en: 'Salary Type' },
      type: FieldType.SELECT,
      blockId: 'payroll_info',
      order: 6,
      defaultValue: DEFAULT_SALARY_TYPE,
      options: [...SALARY_TYPE_OPTIONS],
      isTableColumn: true,
    },
    {
      key: 'base_salary',
      labels: { fa: 'حقوق پایه (ثابت)', en: 'Base Salary (Fixed)' },
      type: FieldType.PRICE,
      blockId: 'payroll_info',
      order: 6.1,
      defaultValue: 0,
      logic: { visibleIf: { field: 'salary_type', operator: LogicOperator.IN, value: [...FIXED_BASE_SALARY_TYPE_VALUES] } },
    },
    {
      key: 'hourly_rate',
      labels: { fa: 'دستمزد ساعتی', en: 'Hourly Wage' },
      type: FieldType.PRICE,
      blockId: 'payroll_info',
      order: 6.2,
      defaultValue: 0,
      isTableColumn: true,
    },
    { key: 'overtime_rate', labels: { fa: 'نرخ اضافه‌کار', en: 'Overtime Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.3, defaultValue: 0 },
    { key: 'late_penalty_rate', labels: { fa: 'نرخ جریمه دیرکرد', en: 'Late Penalty Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.4, defaultValue: 0 },
    { key: 'early_bonus_rate', labels: { fa: 'نرخ پاداش تعجیل', en: 'Early Bonus Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.5, defaultValue: 0 },
    {
      key: 'production_bonus_rate',
      labels: { fa: 'نرخ پاداش عملکرد', en: 'Performance Bonus Rate' },
      type: FieldType.PRICE,
      blockId: 'payroll_info',
      order: 6.6,
      defaultValue: 0,
      logic: { visibleIf: { field: 'salary_type', operator: LogicOperator.IN, value: [...PERFORMANCE_SALARY_TYPE_VALUES] } },
    },
    {
      key: 'commission_percentage',
      labels: { fa: 'درصد پورسانت پیش‌فرض', en: 'Default Commission Percentage' },
      type: FieldType.PERCENTAGE,
      blockId: 'payroll_info',
      order: 6.7,
      defaultValue: 0,
      logic: { visibleIf: { field: 'salary_type', operator: LogicOperator.IN, value: [...COMMISSION_SALARY_TYPE_VALUES] } },
    },
    {
      key: 'profit_share_percentage',
      labels: { fa: 'درصد سهم از سود', en: 'Profit Share Percentage' },
      type: FieldType.PERCENTAGE,
      blockId: 'payroll_info',
      order: 6.8,
      defaultValue: 0,
      logic: { visibleIf: { field: 'salary_type', operator: LogicOperator.IN, value: [...PROFIT_SHARE_SALARY_TYPE_VALUES] } },
    },
    {
      key: 'profit_share_basis',
      labels: { fa: 'مبنای محاسبه سهم سود', en: 'Profit Share Basis' },
      type: FieldType.SELECT,
      blockId: 'payroll_info',
      order: 6.9,
      defaultValue: 'net_profit',
      options: [
        { label: 'سود خالص مرکز هزینه', value: 'net_profit' },
        { label: 'سود ناخالص فروش', value: 'gross_profit' },
      ],
      logic: { visibleIf: { field: 'salary_type', operator: LogicOperator.IN, value: [...PROFIT_SHARE_SALARY_TYPE_VALUES] } },
    },
    {
      key: 'profit_share_cost_center_id',
      labels: { fa: 'مرکز هزینه سهم سود', en: 'Profit Share Cost Center' },
      type: FieldType.RELATION,
      blockId: 'payroll_info',
      order: 7,
      relationConfig: { targetModule: 'cost_centers', targetField: 'name' },
      logic: { visibleIf: { field: 'salary_type', operator: LogicOperator.IN, value: [...PROFIT_SHARE_SALARY_TYPE_VALUES] } },
    },
    { key: 'monthly_paid_leave_hours', labels: { fa: 'سقف مرخصی با حقوق (ساعت/ماه)', en: 'Monthly Paid Leave Hours' }, type: FieldType.NUMBER, blockId: 'payroll_info', order: 7.05, defaultValue: 0 },
    {
      key: 'seniority_mode',
      labels: { fa: 'فرمول سنوات', en: 'Seniority Formula' },
      type: FieldType.SELECT,
      blockId: 'payroll_info',
      order: 7.1,
      defaultValue: 'manual',
      options: [
        { label: 'دستی (مبلغ ثابت)', value: 'manual' },
        { label: 'پایه سنوات - قانون کار ایران (خودکار)', value: 'labor_law' },
      ],
    },
    {
      key: 'seniority_base_amount',
      labels: { fa: 'مبلغ پایه سنوات (دستی)', en: 'Seniority Base Amount (Manual)' },
      type: FieldType.PRICE,
      blockId: 'payroll_info',
      order: 7.15,
      defaultValue: 0,
      logic: { visibleIf: { field: 'seniority_mode', operator: LogicOperator.EQUALS, value: 'manual' } },
    },
    { key: 'insurance_subject', labels: { fa: 'مشمول بیمه', en: 'Insurance Subject' }, type: FieldType.CHECKBOX, blockId: 'insurance_info', order: 8, defaultValue: true },
    { key: 'employee_insurance_rate', labels: { fa: 'نرخ بیمه سهم کارمند', en: 'Employee Insurance Rate' }, type: FieldType.PERCENTAGE, blockId: 'insurance_info', order: 8.1, defaultValue: 7 },
    { key: 'employer_insurance_rate', labels: { fa: 'نرخ بیمه سهم کارفرما', en: 'Employer Insurance Rate' }, type: FieldType.PERCENTAGE, blockId: 'insurance_info', order: 8.2, defaultValue: 23 },

    { key: 'bank_name', labels: { fa: 'نام بانک', en: 'Bank Name' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9 },
    { key: 'bank_account_number', labels: { fa: 'شماره حساب', en: 'Account Number' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9.1 },
    { key: 'bank_card_number', labels: { fa: 'شماره کارت', en: 'Card Number' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9.2 },
    { key: 'iban', labels: { fa: 'شماره شبا', en: 'IBAN' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9.3 },

    { key: 'previous_system_first_purchase_date', labels: { fa: 'تاریخ شروع سوابق سیستم قبلی', en: 'Previous System Start Date' }, type: FieldType.DATE, blockId: 'previous_system_info', order: 9.4 },
    { key: 'previous_system_invoice_total', labels: { fa: 'جمع تعهدهای پرداخت سیستم قبلی', en: 'Previous System Payable Total' }, type: FieldType.PRICE, blockId: 'previous_system_info', order: 9.5 },
    { key: 'previous_system_paid_total', labels: { fa: 'جمع پرداختی‌های سیستم قبلی', en: 'Previous System Paid Total' }, type: FieldType.PRICE, blockId: 'previous_system_info', order: 9.6 },
    { key: 'previous_system_balance_total', labels: { fa: 'مانده اول دوره سیستم قبلی', en: 'Previous System Opening Balance' }, type: FieldType.PRICE, blockId: 'previous_system_info', order: 9.7 },

    {
      key: 'job_description_id',
      labels: { fa: 'شرح شغل', en: 'Job Description' },
      type: FieldType.RELATION,
      blockId: 'job_description_info',
      order: 9.9,
      relationConfig: {
        targetModule: 'job_descriptions',
        targetField: 'name',
        populateFields: JOB_DESCRIPTION_POPULATE_FIELDS,
      },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    { key: 'job_goal', labels: { fa: 'هدف', en: 'Goal' }, type: FieldType.LONG_TEXT, blockId: 'job_description_info', order: 10 },
    { key: 'job_responsibilities', labels: { fa: 'مسئولیت ها', en: 'Responsibilities' }, type: FieldType.SUPER_LONG_TEXT, blockId: 'job_description_info', order: 10.1 },
    { key: 'job_duties', labels: { fa: 'شرح وظایف', en: 'Duties' }, type: FieldType.SUPER_LONG_TEXT, blockId: 'job_description_info', order: 10.2 },
    { key: 'job_requirements', labels: { fa: 'شرایط احراز', en: 'Requirements' }, type: FieldType.SUPER_LONG_TEXT, blockId: 'job_description_info', order: 10.3 },
    { key: 'behavioral_traits', labels: { fa: 'ویژگی های رفتاری', en: 'Behavioral Traits' }, type: FieldType.LONG_TEXT, blockId: 'job_description_info', order: 10.4 },
    { key: 'career_path', labels: { fa: 'مسیر ارتقا', en: 'Career Path' }, type: FieldType.LONG_TEXT, blockId: 'job_description_info', order: 10.5 },
    { key: 'performance_kpi', labels: { fa: 'ارزیابی عملکرد (KPI)', en: 'Performance Evaluation (KPI)' }, type: FieldType.SUPER_LONG_TEXT, blockId: 'job_description_info', order: 10.6 },
    { key: 'competency_ksa', labels: { fa: 'نظام شایستگی (KSA)', en: 'Competency System (KSA)' }, type: FieldType.SUPER_LONG_TEXT, blockId: 'job_description_info', order: 10.7 },
    { key: 'role_relationships', labels: { fa: 'ارتباط با سایر نقش ها', en: 'Role Relationships' }, type: FieldType.LONG_TEXT, blockId: 'job_description_info', order: 10.8 },
    { key: 'salary_calculation_notes', labels: { fa: 'محاسبه حقوق', en: 'Salary Calculation' }, type: FieldType.SUPER_LONG_TEXT, blockId: 'job_description_info', order: 10.9 },
    { key: 'job_description_notes', labels: { fa: 'توضیحات تکمیلی', en: 'Additional Notes' }, type: FieldType.LONG_TEXT, blockId: 'job_description_info', order: 11 },

    { key: 'notes', labels: { fa: 'توضیحات', en: 'Notes' }, type: FieldType.LONG_TEXT, blockId: 'notes_info', order: 12 },
    { key: 'template_field_values', labels: { fa: 'داده‌های قالب', en: 'Template Values' }, type: FieldType.JSON, blockId: 'notes_info', order: 90, readonly: true, hideInCreateForm: true, nature: FieldNature.SYSTEM },
    { key: 'template_schema_snapshot', labels: { fa: 'اسنپ‌شات قالب', en: 'Template Snapshot' }, type: FieldType.JSON, blockId: 'notes_info', order: 91, readonly: true, hideInCreateForm: true, nature: FieldNature.SYSTEM },

    {
      key: 'process_template_id',
      labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 1,
      relationConfig: { targetModule: 'process_templates', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'execution_process_draft',
      labels: { fa: 'فرآیند اجرا', en: 'Execution Process' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 2,
      nature: FieldNature.STANDARD,
    },
  
    { key: 'assignee_id', labels: { fa: 'مسئول پیگیری', en: 'Assignee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 1.75, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 1.8, nature: FieldNature.STANDARD, isTableColumn: true },
],
  blocks: [
    { id: 'identity_info', titles: { fa: 'اطلاعات پایه' }, type: BlockType.FIELD_GROUP, order: 1 },
    { id: 'legal_info', titles: { fa: 'اطلاعات هویتی' }, type: BlockType.FIELD_GROUP, order: 2 },
    { id: 'contact_info', titles: { fa: 'اطلاعات تماس' }, type: BlockType.FIELD_GROUP, order: 3 },
    { id: 'bot_info', titles: { fa: 'تنظیمات بات' }, type: BlockType.FIELD_GROUP, order: 3.5 },
    { id: 'attendance_policy_info', titles: { fa: 'برنامه حضور و سیاست تردد' }, type: BlockType.FIELD_GROUP, order: 4 },
    { id: 'payroll_info', titles: { fa: 'تنظیمات حقوق و دستمزد' }, type: BlockType.FIELD_GROUP, order: 5 },
    { id: 'insurance_info', titles: { fa: 'بیمه' }, type: BlockType.FIELD_GROUP, order: 6 },
    { id: 'banking_info', titles: { fa: 'اطلاعات بانکی' }, type: BlockType.FIELD_GROUP, order: 7 },
    { id: 'previous_system_info', titles: { fa: 'اطلاعات سیستم قبلی' }, type: BlockType.FIELD_GROUP, order: 7.5 },
    { id: 'financial_history', titles: { fa: 'اطلاعات مالی و سوابق' }, type: BlockType.FIELD_GROUP, order: 7.75 },
    { id: 'job_description_info', titles: { fa: 'شرح شغل' }, type: BlockType.FIELD_GROUP, order: 8 },
    { id: 'process', titles: { fa: 'فرآیند جذب و همکاری' }, type: BlockType.FIELD_GROUP, order: 8.5 },
    { id: 'notes_info', titles: { fa: 'یادداشت' }, type: BlockType.FIELD_GROUP, order: 9 },
  ],
  relatedTabs: [
    {
      id: 'employee_bot_groups',
      title: 'گروه‌های بات',
      icon: 'AppstoreOutlined',
      relationType: 'fk_from_field',
      targetModule: 'counterparty_bot_groups',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_attendance_logs',
      title: 'تردد',
      icon: 'ClockCircleOutlined',
      relationType: 'fk_from_field',
      targetModule: 'attendance_logs',
      sourceField: 'related_profile_id',
      foreignKey: 'assignee_id',
    },
    {
      id: 'employee_leave_requests',
      title: 'مرخصی',
      icon: 'CalendarOutlined',
      relationType: 'fk_from_field',
      targetModule: 'leave_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_overtime_requests',
      title: 'اضافه‌کاری',
      icon: 'ClockCircleOutlined',
      relationType: 'fk_from_field',
      targetModule: 'overtime_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_mission_requests',
      title: 'ماموریت',
      icon: 'CarOutlined',
      relationType: 'fk_from_field',
      targetModule: 'mission_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_sms_reports',
      title: 'پیامک‌ها',
      icon: 'MessageOutlined',
      relationType: 'phone_directory',
      targetModule: 'sms_delivery_reports',
      disableCreate: true,
    },
    {
      id: 'employee_voip_calls',
      title: 'تماس‌ها',
      icon: 'PhoneOutlined',
      relationType: 'phone_directory',
      targetModule: 'voip_call_reports',
      disableCreate: true,
    },
    {
      id: 'employee_financial_overview',
      title: 'وضعیت مالی',
      icon: 'WalletOutlined',
      relationType: 'operational_financial_overview',
      targetModule: 'employees',
      disableCreate: true,
    },
    {
      id: 'employee_advances',
      title: 'مساعده‌ها',
      icon: 'WalletOutlined',
      relationType: 'fk_from_field',
      targetModule: 'employee_advances',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_payroll_slips',
      title: 'فیش‌های حقوقی',
      icon: 'FileTextOutlined',
      relationType: 'fk_from_field',
      targetModule: 'payroll_slips',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_bonus_requests',
      title: 'پاداش‌ها',
      icon: 'GiftOutlined',
      relationType: 'fk_from_field',
      targetModule: 'employee_bonus_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_penalty_requests',
      title: 'جریمه‌ها',
      icon: 'WarningOutlined',
      relationType: 'fk_from_field',
      targetModule: 'employee_penalty_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_contracts',
      title: 'قراردادها',
      icon: 'FileDoneOutlined',
      relationType: 'fk_from_field',
      targetModule: 'employee_contracts',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
  ],
};
