import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, LogicOperator } from '../types';

export const employeesModule: ModuleDefinition = {
  id: 'employees',
  titles: { fa: 'کارکنان', faSingular: 'کارمند', en: 'Employees' },
  nature: ModuleNature.STANDARD,
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  table: 'employees',
  fields: [
    { key: 'image_url', labels: { fa: 'تصویر', en: 'Image' }, type: FieldType.IMAGE, location: FieldLocation.HEADER, order: 0.8 },
    { key: 'full_name', labels: { fa: 'نام و نام خانوادگی', en: 'Full Name' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, isTableColumn: true, isKey: true },
    { key: 'system_code', labels: { fa: 'کد پرسنلی', en: 'Employee Code' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1.1, isTableColumn: true },
    {
      key: 'employment_status',
      labels: { fa: 'وضعیت همکاری', en: 'Employment Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1.2,
      isTableColumn: true,
      defaultValue: 'active',
      options: [
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'غیرفعال', value: 'inactive', color: 'default' },
        { label: 'تعلیق', value: 'suspended', color: 'orange' },
        { label: 'قطع همکاری', value: 'terminated', color: 'red' },
      ],
    },
    { key: 'job_title', labels: { fa: 'عنوان شغلی', en: 'Job Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1.3, isTableColumn: true },
    { key: 'mobile_1', labels: { fa: 'موبایل', en: 'Mobile' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 1.4, isTableColumn: true },

    {
      key: 'related_profile_id',
      labels: { fa: 'کاربر مرتبط', en: 'Related User' },
      type: FieldType.RELATION,
      blockId: 'identity_info',
      order: 2,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
    },
    {
      key: 'employment_type',
      labels: { fa: 'نوع همکاری', en: 'Employment Type' },
      type: FieldType.SELECT,
      blockId: 'identity_info',
      order: 2.1,
      isTableColumn: true,
      options: [
        { label: 'تمام وقت', value: 'full_time' },
        { label: 'پاره وقت', value: 'part_time' },
        { label: 'پروژه‌ای', value: 'project_based' },
        { label: 'ساعتی', value: 'hourly' },
        { label: 'پورسانتی', value: 'commission' },
      ],
    },
    { key: 'department', labels: { fa: 'واحد سازمانی', en: 'Department' }, type: FieldType.SELECT, blockId: 'identity_info', order: 2.2, dynamicOptionsCategory: 'employee_departments', isTableColumn: true },
    { key: 'team', labels: { fa: 'تیم', en: 'Team' }, type: FieldType.SELECT, blockId: 'identity_info', order: 2.3, dynamicOptionsCategory: 'employee_teams' },
    { key: 'hire_date', labels: { fa: 'تاریخ شروع همکاری', en: 'Hire Date' }, type: FieldType.DATE, blockId: 'identity_info', order: 2.4, isTableColumn: true },
    { key: 'termination_date', labels: { fa: 'تاریخ پایان همکاری', en: 'Termination Date' }, type: FieldType.DATE, blockId: 'identity_info', order: 2.5, logic: { visibleIf: { field: 'employment_status', operator: LogicOperator.EQUALS, value: 'terminated' } } },

    { key: 'national_code', labels: { fa: 'کد ملی', en: 'National Code' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3 },
    { key: 'birth_date', labels: { fa: 'تاریخ تولد', en: 'Birth Date' }, type: FieldType.DATE, blockId: 'legal_info', order: 3.1 },
    {
      key: 'gender',
      labels: { fa: 'جنسیت', en: 'Gender' },
      type: FieldType.SELECT,
      blockId: 'legal_info',
      order: 3.2,
      options: [
        { label: 'مرد', value: 'male' },
        { label: 'زن', value: 'female' },
      ],
    },
    { key: 'father_name', labels: { fa: 'نام پدر', en: 'Father Name' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3.3 },
    { key: 'birth_certificate_number', labels: { fa: 'شماره شناسنامه', en: 'Birth Certificate No.' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3.4 },
    { key: 'insurance_number', labels: { fa: 'شماره بیمه', en: 'Insurance No.' }, type: FieldType.TEXT, blockId: 'legal_info', order: 3.5 },

    { key: 'mobile_2', labels: { fa: 'موبایل دوم', en: 'Mobile 2' }, type: FieldType.PHONE, blockId: 'contact_info', order: 4 },
    { key: 'phone', labels: { fa: 'تلفن ثابت', en: 'Phone' }, type: FieldType.PHONE, blockId: 'contact_info', order: 4.1 },
    { key: 'email', labels: { fa: 'ایمیل', en: 'Email' }, type: FieldType.TEXT, blockId: 'contact_info', order: 4.2 },
    { key: 'province', labels: { fa: 'استان', en: 'Province' }, type: FieldType.SELECT, blockId: 'contact_info', order: 4.3, dynamicOptionsCategory: 'provinces' },
    { key: 'city', labels: { fa: 'شهر', en: 'City' }, type: FieldType.SELECT, blockId: 'contact_info', order: 4.4, dynamicOptionsCategory: 'cities' },
    { key: 'address', labels: { fa: 'آدرس', en: 'Address' }, type: FieldType.LONG_TEXT, blockId: 'contact_info', order: 4.5 },
    {
      key: 'default_work_schedule_id',
      labels: { fa: 'برنامه حضور پیش‌فرض', en: 'Default Work Schedule' },
      type: FieldType.RELATION,
      blockId: 'attendance_policy_info',
      order: 4.6,
      relationConfig: { targetModule: 'work_schedules', targetField: 'title' },
    },
    { key: 'has_flexible_hours', labels: { fa: 'ساعت کاری شناور', en: 'Flexible Hours' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 4.7, defaultValue: false },
    { key: 'expected_daily_minutes', labels: { fa: 'دقایق کار روزانه', en: 'Expected Daily Minutes' }, type: FieldType.NUMBER, blockId: 'attendance_policy_info', order: 4.8, defaultValue: 480 },
    { key: 'grace_minutes_for_late', labels: { fa: 'تلورانس تاخیر (دقیقه)', en: 'Late Grace Minutes' }, type: FieldType.NUMBER, blockId: 'attendance_policy_info', order: 4.9, defaultValue: 0 },
    { key: 'overtime_auto_approve', labels: { fa: 'اضافه‌کاری بدون نیاز به تایید', en: 'Auto Approve Overtime' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5, defaultValue: false },
    { key: 'leave_auto_approve', labels: { fa: 'مرخصی بدون نیاز به تایید', en: 'Auto Approve Leave' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5.1, defaultValue: false },
    { key: 'mission_auto_approve', labels: { fa: 'ماموریت بدون نیاز به تایید', en: 'Auto Approve Mission' }, type: FieldType.CHECKBOX, blockId: 'attendance_policy_info', order: 5.2, defaultValue: false },

    {
      key: 'salary_type',
      labels: { fa: 'نوع محاسبه حقوق', en: 'Salary Type' },
      type: FieldType.SELECT,
      blockId: 'payroll_info',
      order: 6,
      defaultValue: 'performance',
      options: [
        { label: 'عملکردی', value: 'performance' },
        { label: 'ساعتی', value: 'hourly' },
        { label: 'پورسانتی', value: 'commission' },
        { label: 'درصد از سود', value: 'profit_share' },
        { label: 'ترکیبی', value: 'mixed' },
      ],
      isTableColumn: true,
    },
    { key: 'base_salary', labels: { fa: 'حقوق پایه', en: 'Base Salary' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.1, defaultValue: 0 },
    { key: 'hourly_rate', labels: { fa: 'نرخ ساعتی', en: 'Hourly Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.2, defaultValue: 0 },
    { key: 'overtime_rate', labels: { fa: 'نرخ اضافه‌کار', en: 'Overtime Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.3, defaultValue: 0 },
    { key: 'late_penalty_rate', labels: { fa: 'نرخ جریمه دیرکرد', en: 'Late Penalty Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.4, defaultValue: 0 },
    { key: 'early_bonus_rate', labels: { fa: 'نرخ پاداش تعجیل', en: 'Early Bonus Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.5, defaultValue: 0 },
    { key: 'production_bonus_rate', labels: { fa: 'نرخ پاداش عملکرد', en: 'Performance Bonus Rate' }, type: FieldType.PRICE, blockId: 'payroll_info', order: 6.6, defaultValue: 0 },
    { key: 'commission_percentage', labels: { fa: 'درصد پورسانت پیش‌فرض', en: 'Default Commission Percentage' }, type: FieldType.PERCENTAGE, blockId: 'payroll_info', order: 6.7, defaultValue: 0 },
    { key: 'profit_share_percentage', labels: { fa: 'درصد سهم از سود', en: 'Profit Share Percentage' }, type: FieldType.PERCENTAGE, blockId: 'payroll_info', order: 6.8, defaultValue: 0 },
    {
      key: 'profit_share_basis',
      labels: { fa: 'مبنای محاسبه سهم سود', en: 'Profit Share Basis' },
      type: FieldType.SELECT,
      blockId: 'payroll_info',
      order: 6.9,
      defaultValue: 'net_profit',
      options: [
        { label: 'سود خالص مرکز هزینه', value: 'net_profit' },
        { label: 'سود ناخالص فروش', value: 'gross_profit' },
      ],
    },
    {
      key: 'profit_share_cost_center_id',
      labels: { fa: 'مرکز هزینه سهم سود', en: 'Profit Share Cost Center' },
      type: FieldType.RELATION,
      blockId: 'payroll_info',
      order: 7,
      relationConfig: { targetModule: 'cost_centers', targetField: 'name' },
    },
    { key: 'insurance_subject', labels: { fa: 'مشمول بیمه', en: 'Insurance Subject' }, type: FieldType.CHECKBOX, blockId: 'insurance_info', order: 8, defaultValue: true },
    { key: 'employee_insurance_rate', labels: { fa: 'نرخ بیمه سهم کارمند', en: 'Employee Insurance Rate' }, type: FieldType.PERCENTAGE, blockId: 'insurance_info', order: 8.1, defaultValue: 7 },
    { key: 'employer_insurance_rate', labels: { fa: 'نرخ بیمه سهم کارفرما', en: 'Employer Insurance Rate' }, type: FieldType.PERCENTAGE, blockId: 'insurance_info', order: 8.2, defaultValue: 23 },

    { key: 'bank_name', labels: { fa: 'نام بانک', en: 'Bank Name' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9 },
    { key: 'bank_account_number', labels: { fa: 'شماره حساب', en: 'Account Number' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9.1 },
    { key: 'bank_card_number', labels: { fa: 'شماره کارت', en: 'Card Number' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9.2 },
    { key: 'iban', labels: { fa: 'شماره شبا', en: 'IBAN' }, type: FieldType.TEXT, blockId: 'banking_info', order: 9.3 },

    { key: 'notes', labels: { fa: 'توضیحات', en: 'Notes' }, type: FieldType.LONG_TEXT, blockId: 'notes_info', order: 10 },
  ],
  blocks: [
    { id: 'identity_info', titles: { fa: 'اطلاعات پایه' }, type: BlockType.FIELD_GROUP, order: 1 },
    { id: 'legal_info', titles: { fa: 'اطلاعات هویتی' }, type: BlockType.FIELD_GROUP, order: 2 },
    { id: 'contact_info', titles: { fa: 'اطلاعات تماس' }, type: BlockType.FIELD_GROUP, order: 3 },
    { id: 'attendance_policy_info', titles: { fa: 'برنامه حضور و سیاست تردد' }, type: BlockType.FIELD_GROUP, order: 4 },
    { id: 'payroll_info', titles: { fa: 'تنظیمات حقوق و دستمزد' }, type: BlockType.FIELD_GROUP, order: 5 },
    { id: 'insurance_info', titles: { fa: 'بیمه' }, type: BlockType.FIELD_GROUP, order: 6 },
    { id: 'banking_info', titles: { fa: 'اطلاعات بانکی' }, type: BlockType.FIELD_GROUP, order: 7 },
    { id: 'notes_info', titles: { fa: 'یادداشت' }, type: BlockType.FIELD_GROUP, order: 8 },
  ],
  relatedTabs: [
    {
      id: 'employee_attendance_logs',
      title: 'تردد',
      icon: 'ClockCircleOutlined',
      relationType: 'fk_from_field',
      targetModule: 'attendance_logs',
      sourceField: 'related_profile_id',
      foreignKey: 'assignee_id',
    },
    {
      id: 'employee_leave_requests',
      title: 'مرخصی',
      icon: 'CalendarOutlined',
      relationType: 'fk_from_field',
      targetModule: 'leave_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_overtime_requests',
      title: 'اضافه‌کاری',
      icon: 'ClockCircleOutlined',
      relationType: 'fk_from_field',
      targetModule: 'overtime_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
    {
      id: 'employee_mission_requests',
      title: 'ماموریت',
      icon: 'CarOutlined',
      relationType: 'fk_from_field',
      targetModule: 'mission_requests',
      sourceField: 'id',
      foreignKey: 'employee_id',
    },
  ],
};
