import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, RowCalculationType, SummaryCalculationType, ViewMode } from '../types';
import {
  CASH_BANK_OPERATION_STATUS_OPTIONS,
  CASH_BANK_PAYMENT_TYPE_OPTIONS,
  CASH_BANK_RESPONSIBLE_LABEL_FA,
} from '../utils/cashBankFieldCatalog';
import { getTodayLocalDateValue } from '../utils/defaultValues';

export const employeeAdvancesConfig: ModuleDefinition = {
  id: 'employee_advances',
  titles: { fa: 'مساعده‌ها', faSingular: 'مساعده', en: 'Employee Advances' },
  nature: ModuleNature.FINANCE,
  table: 'employee_advances',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: { labelTemplate: '{{system_code}} - {{name}}', searchFields: ['name', 'system_code', 'reason'] },
  fields: [
    { key: 'name', labels: { fa: 'عنوان درخواست', en: 'Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'شماره مساعده', en: 'Advance No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'employee_id', labels: { fa: 'درخواست‌دهنده مساعده', en: 'Employee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 3, validation: { required: true }, relationConfig: { targetModule: 'employees', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'request_date', labels: { fa: 'تاریخ درخواست', en: 'Request Date' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 4, defaultValue: getTodayLocalDateValue, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'amount', labels: { fa: 'مبلغ درخواستی', en: 'Amount' }, type: FieldType.PRICE, location: FieldLocation.HEADER, order: 5, validation: { required: true }, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 6,
      defaultValue: 'draft',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'درخواست شده', value: 'requested', color: 'orange' },
        { label: 'تایید شده', value: 'approved', color: 'blue' },
        { label: 'پرداخت شده', value: 'paid', color: 'green' },
        { label: 'تسویه شده', value: 'settled', color: 'purple' },
        { label: 'تکمیل شده', value: 'completed', color: 'green' },
        { label: 'سند شده', value: 'posted', color: 'cyan' },
        { label: 'رد شده', value: 'rejected', color: 'red' },
        { label: 'لغو شده', value: 'canceled', color: 'default' },
      ],
    },
    { key: 'due_date', labels: { fa: 'مهلت تسویه', en: 'Due Date' }, type: FieldType.DATE, location: FieldLocation.BLOCK, blockId: 'details', order: 1, nature: FieldNature.STANDARD },
    { key: 'assignee_id', labels: { fa: 'مسئول پرداخت/پیگیری', en: 'Assignee' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'details', order: 2, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'related_payroll_slip_id', labels: { fa: 'فیش حقوقی تسویه', en: 'Payroll Slip' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'details', order: 3, relationConfig: { targetModule: 'payroll_slips', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'reason', labels: { fa: 'شرح درخواست', en: 'Reason' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 4, nature: FieldNature.STANDARD },
    { key: 'paid_amount', labels: { fa: 'پرداخت شده', en: 'Paid Amount' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 1, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'remaining_amount', labels: { fa: 'مانده', en: 'Remaining' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 5, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
  ],
  blocks: [
    { id: 'details', titles: { fa: 'جزئیات مساعده', en: 'Details' }, type: BlockType.FIELD_GROUP, order: 1 },
    {
      id: 'payments',
      titles: { fa: 'جدول پرداخت‌ها', en: 'Payments' },
      type: BlockType.TABLE,
      order: 2,
      rowCalculationType: RowCalculationType.SIMPLE_MULTIPLY,
      tableColumns: [
        { key: 'attachment', title: 'پیوست', type: FieldType.IMAGE, width: 96 },
        { key: 'tags', title: 'برچسب‌ها', type: FieldType.TAGS, width: 150 },
        { key: 'payment_type', title: 'روش پرداخت', type: FieldType.SELECT, width: 140, options: [...CASH_BANK_PAYMENT_TYPE_OPTIONS] },
        {
          key: 'cheque_id',
          title: 'چک پرداختی',
          type: FieldType.RELATION,
          width: 180,
          relationConfig: {
            targetModule: 'cheques',
            targetField: 'serial_no',
            quickCreateFieldKeys: ['serial_no', 'sayad_id', 'issue_date', 'due_date', 'amount', 'payee_name', 'account_holder_name', 'bank_name', 'image_url'],
            quickCreateDefaults: { cheque_type: 'issued', status: 'new' },
          },
        },
        {
          key: 'cheque_status',
          title: 'وضعیت چک',
          type: FieldType.SELECT,
          width: 130,
          options: [
            { label: 'جدید', value: 'new', color: 'blue' },
            { label: 'در بانک', value: 'in_bank', color: 'orange' },
            { label: 'خرج شده', value: 'paid', color: 'yellow' },
            { label: 'وصول شده', value: 'cleared', color: 'green' },
            { label: 'برگشتی', value: 'bounced', color: 'red' },
            { label: 'عودت شده', value: 'returned', color: 'purple' },
            { label: 'ابطال شده', value: 'canceled', color: 'default' },
          ],
        },
        { key: 'use_existing_received_cheque', title: 'خرج چک', type: FieldType.CHECKBOX, width: 90 },
        {
          key: 'spent_cheque_id',
          title: 'چک دریافتی',
          type: FieldType.RELATION,
          width: 170,
          relationConfig: { targetModule: 'cheques', targetField: 'serial_no' },
        },
        {
          key: 'status',
          title: 'وضعیت',
          type: FieldType.SELECT,
          width: 120,
          defaultValue: 'received',
          options: [...CASH_BANK_OPERATION_STATUS_OPTIONS],
        },
        {
          key: 'source_account',
          title: 'حساب پرداخت',
          type: FieldType.RELATION,
          width: 220,
          relationConfig: {
            targetModule: 'bank_accounts',
            targetField: 'bank_name',
            filter: { is_active: true },
            sourceModules: [
              { targetModule: 'bank_accounts', targetField: 'bank_name', filter: { is_active: true }, tagLabel: 'بانک', tagColor: 'cyan' },
              { targetModule: 'cash_boxes', targetField: 'name', filter: { is_active: true }, tagLabel: 'صندوق', tagColor: 'gold' },
              { targetModule: 'petty_funds', targetField: 'name', filter: { is_active: true }, tagLabel: 'تنخواه', tagColor: 'magenta' },
            ],
          },
        },
        { key: 'responsible_id', title: CASH_BANK_RESPONSIBLE_LABEL_FA, type: FieldType.RELATION, width: 150, relationConfig: { targetModule: 'profiles', targetField: 'full_name' } },
        { key: 'date', title: 'تاریخ', type: FieldType.DATE, width: 130 },
        { key: 'amount', title: 'مبلغ', type: FieldType.PRICE, width: 160, showTotal: true },
        { key: 'transfer_fee', title: 'کارمزد انتقال', type: FieldType.PRICE, width: 150 },
        { key: 'description', title: 'توضیحات', type: FieldType.LONG_TEXT, width: 220 },
      ],
    },
    { id: 'summary', titles: { fa: 'خلاصه مالی', en: 'Summary' }, type: BlockType.FIELD_GROUP, order: 3, summaryConfig: { calculationType: SummaryCalculationType.INVOICE_FINANCIALS, fieldMapping: { total: 'amount', received: 'paid_amount', remaining: 'remaining_amount' }, labels: { total: 'مبلغ مساعده', received: 'پرداخت شده', remaining: 'مانده' } } },
    { id: 'process', titles: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: BlockType.FIELD_GROUP, order: 4 },
  ],
  relatedTabs: [],
  actionButtons: [{ id: 'create_journal_entry', label: 'صدور سند', placement: 'header', variant: 'primary' }],
};
