import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const employeeContractsConfig: ModuleDefinition = {
  id: 'employee_contracts',
  titles: { fa: 'قراردادهای کارکنان', faSingular: 'قرارداد کارمند', en: 'Employee Contracts' },
  nature: ModuleNature.STANDARD,
  table: 'employee_contracts',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: { labelTemplate: '{{system_code}} - {{name}}', searchFields: ['name', 'system_code', 'title'] },
  fields: [
    { key: 'name', labels: { fa: 'عنوان قرارداد', en: 'Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'شماره قرارداد', en: 'Contract No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'employee_id', labels: { fa: 'کارمند', en: 'Employee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 3, relationConfig: { targetModule: 'employees', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'applicant_id', labels: { fa: 'متقاضی استخدام', en: 'Applicant' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 4, relationConfig: { targetModule: 'recruitment_applicants', targetField: 'name' }, nature: FieldNature.STANDARD },
    {
      key: 'contract_type',
      labels: { fa: 'نوع قرارداد', en: 'Contract Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 5,
      defaultValue: 'employment',
      options: [
        { label: 'استخدام', value: 'employment' },
        { label: 'مشاوره', value: 'consulting' },
        { label: 'موقت', value: 'temporary' },
        { label: 'آزمایشی', value: 'probation' },
        { label: 'پیمانکاری', value: 'contractor' },
        { label: 'سایر', value: 'other' },
      ],
      isTableColumn: true,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 6,
      defaultValue: 'draft',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'در انتظار امضا', value: 'pending_signature', color: 'orange' },
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'منقضی', value: 'expired', color: 'gray' },
        { label: 'خاتمه یافته', value: 'terminated', color: 'red' },
        { label: 'لغو شده', value: 'canceled', color: 'default' },
      ],
    },
    { key: 'start_date', labels: { fa: 'تاریخ شروع', en: 'Start Date' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 7, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'end_date', labels: { fa: 'تاریخ پایان', en: 'End Date' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 8, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'base_salary', labels: { fa: 'مبلغ پایه قرارداد', en: 'Base Salary' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'terms', order: 1, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'work_location', labels: { fa: 'محل کار', en: 'Work Location' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'terms', order: 2, nature: FieldNature.STANDARD },
    { key: 'title', labels: { fa: 'سمت/عنوان شغلی', en: 'Job Title' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'terms', order: 3, nature: FieldNature.STANDARD },
    { key: 'body', labels: { fa: 'متن قرارداد', en: 'Contract Body' }, type: FieldType.SUPER_LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'content', order: 1, nature: FieldNature.STANDARD },
    { key: 'terms', labels: { fa: 'بندهای قرارداد', en: 'Terms' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'content', order: 2, nature: FieldNature.STANDARD },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 3, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
  ],
  blocks: [
    { id: 'terms', titles: { fa: 'شرایط اصلی', en: 'Main Terms' }, type: BlockType.FIELD_GROUP, order: 1 },
    { id: 'content', titles: { fa: 'متن و بندها', en: 'Content' }, type: BlockType.FIELD_GROUP, order: 2 },
    { id: 'process', titles: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: BlockType.FIELD_GROUP, order: 3 },
  ],
  relatedTabs: [],
};
