import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, RowCalculationType, SummaryCalculationType, ViewMode } from '../types';
import { getTodayLocalDateValue } from '../utils/defaultValues';

export const expenseDocumentsConfig: ModuleDefinition = {
  id: 'expense_documents',
  titles: { fa: 'هزینه‌ها', faSingular: 'هزینه', en: 'Expenses' },
  nature: ModuleNature.FINANCE,
  table: 'expense_documents',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: { labelTemplate: '{{system_code}} - {{name}}', searchFields: ['name', 'system_code', 'expense_type', 'notes'] },
  fields: [
    { key: 'image_url', labels: { fa: 'تصویر', en: 'Image' }, type: FieldType.IMAGE, location: FieldLocation.HEADER, order: 0, nature: FieldNature.PREDEFINED, isTableColumn: true },
    { key: 'name', labels: { fa: 'عنوان هزینه', en: 'Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'شماره هزینه', en: 'Expense No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'expense_date', labels: { fa: 'تاریخ هزینه', en: 'Expense Date' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 3, defaultValue: getTodayLocalDateValue, validation: { required: true }, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 'draft',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'در انتظار تایید', value: 'pending_approval', color: 'orange' },
        { label: 'تایید شده', value: 'approved', color: 'blue' },
        { label: 'پرداخت شده', value: 'paid', color: 'green' },
        { label: 'سند شده', value: 'posted', color: 'purple' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
      ],
    },
    { key: 'expense_type', labels: { fa: 'نوع هزینه', en: 'Expense Type' }, type: FieldType.SELECT, dynamicOptionsCategory: 'expense_type', location: FieldLocation.HEADER, order: 5, defaultValue: 'general', nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'estimated_expense_amount',
      labels: { fa: 'هزینه تقریبی', en: 'Estimated Expense Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.HEADER,
      order: 5.5,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    { key: 'assignee_id', labels: { fa: 'مسئول هزینه', en: 'Assignee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 6, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'counterparty_type',
      labels: { fa: 'طرف حساب', en: 'Counterparty Type' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 1,
      defaultValue: 'other',
      options: [
        { label: 'تامین‌کننده', value: 'supplier' },
        { label: 'مشتری', value: 'customer' },
        { label: 'کارمند', value: 'employee' },
        { label: 'سایر', value: 'other' },
      ],
    },
    { key: 'supplier_id', labels: { fa: 'تامین‌کننده', en: 'Supplier' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 2, relationConfig: { targetModule: 'suppliers', targetField: 'business_name' }, nature: FieldNature.STANDARD },
    { key: 'customer_id', labels: { fa: 'مشتری', en: 'Customer' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 3, relationConfig: { targetModule: 'customers', targetField: 'full_name' }, nature: FieldNature.STANDARD },
    { key: 'employee_id', labels: { fa: 'کارمند مرتبط', en: 'Employee' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 4, relationConfig: { targetModule: 'employees', targetField: 'full_name' }, nature: FieldNature.STANDARD },
    { key: 'total_amount', labels: { fa: 'مبلغ کل', en: 'Total Amount' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 1, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'paid_amount', labels: { fa: 'پرداخت شده', en: 'Paid Amount' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'remaining_amount', labels: { fa: 'مانده', en: 'Remaining' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 3, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'notes', labels: { fa: 'توضیحات', en: 'Notes' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'notes', order: 1, nature: FieldNature.STANDARD },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.BLOCK, blockId: 'notes', order: 2, nature: FieldNature.STANDARD },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
  ],
  blocks: [
    { id: 'relations', titles: { fa: 'طرف حساب', en: 'Relations' }, type: BlockType.FIELD_GROUP, order: 1, icon: 'LinkOutlined' },
    {
      id: 'items',
      titles: { fa: 'ردیف‌های هزینه', en: 'Expense Items' },
      type: BlockType.TABLE,
      order: 2,
      rowCalculationType: RowCalculationType.SIMPLE_MULTIPLY,
      tableColumns: [
        { key: 'description', title: 'شرح', type: FieldType.LONG_TEXT, width: 260 },
        { key: 'quantity', title: 'تعداد/مقدار', type: FieldType.NUMBER, width: 120 },
        { key: 'unit_price', title: 'مبلغ واحد', type: FieldType.PRICE, width: 150 },
        { key: 'total_price', title: 'جمع', type: FieldType.PRICE, width: 160, showTotal: true, readonly: true },
        { key: 'cost_center_id', title: 'مرکز هزینه', type: FieldType.RELATION, width: 180, relationConfig: { targetModule: 'cost_centers', targetField: 'name' } },
      ],
    },
    {
      id: 'payments',
      titles: { fa: 'پرداخت‌ها', en: 'Payments' },
      type: BlockType.TABLE,
      order: 3,
      rowCalculationType: RowCalculationType.SIMPLE_MULTIPLY,
      tableColumns: [
        { key: 'attachment', title: 'پیوست', type: FieldType.IMAGE, width: 96 },
        { key: 'payment_type', title: 'روش پرداخت', type: FieldType.SELECT, width: 140, options: [{ label: 'نقد', value: 'cash' }, { label: 'بانک', value: 'bank' }, { label: 'کارت', value: 'card' }, { label: 'چک', value: 'cheque' }] },
        {
          key: 'status',
          title: 'وضعیت',
          type: FieldType.SELECT,
          width: 120,
          defaultValue: 'received',
          options: [
            { label: 'در انتظار', value: 'pending', color: 'orange' },
            { label: 'پرداخت شده', value: 'received', color: 'green' },
            { label: 'برگشت خورده', value: 'returned', color: 'red' },
          ],
        },
        {
          key: 'source_account',
          title: 'حساب پرداخت',
          type: FieldType.RELATION,
          width: 220,
          relationConfig: {
            targetModule: 'bank_accounts',
            targetField: 'bank_name',
            filter: { is_active: true },
            sourceModules: [
              { targetModule: 'bank_accounts', targetField: 'bank_name', filter: { is_active: true }, tagLabel: 'بانک', tagColor: 'cyan' },
              { targetModule: 'cash_boxes', targetField: 'name', filter: { is_active: true }, tagLabel: 'صندوق', tagColor: 'gold' },
              { targetModule: 'petty_funds', targetField: 'name', filter: { is_active: true }, tagLabel: 'تنخواه', tagColor: 'magenta' },
            ],
          },
        },
        { key: 'responsible_id', title: 'مسئول پرداخت', type: FieldType.RELATION, width: 150, relationConfig: { targetModule: 'profiles', targetField: 'full_name' } },
        { key: 'date', title: 'تاریخ', type: FieldType.DATE, width: 130 },
        { key: 'amount', title: 'مبلغ', type: FieldType.PRICE, width: 160, showTotal: true },
        { key: 'description', title: 'توضیحات', type: FieldType.LONG_TEXT, width: 220 },
      ],
    },
    { id: 'summary', titles: { fa: 'خلاصه مالی', en: 'Summary' }, type: BlockType.FIELD_GROUP, order: 4, summaryConfig: { calculationType: SummaryCalculationType.INVOICE_FINANCIALS, fieldMapping: { total: 'total_amount', received: 'paid_amount', remaining: 'remaining_amount' } } },
    { id: 'notes', titles: { fa: 'یادداشت‌ها', en: 'Notes' }, type: BlockType.FIELD_GROUP, order: 5 },
    { id: 'process', titles: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: BlockType.FIELD_GROUP, order: 6 },
  ],
  relatedTabs: [],
  actionButtons: [{ id: 'create_journal_entry', label: 'صدور سند', placement: 'header', variant: 'primary' }],
};
