import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const fiscalYearsConfig: ModuleDefinition = {
  id: 'fiscal_years',
  titles: { fa: 'سال های مالی', en: 'Fiscal Years' },
  nature: ModuleNature.FINANCE,
  table: 'fiscal_years',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'title',
      labels: { fa: 'عنوان سال مالی', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isTableColumn: true,
      isKey: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'start_date',
      labels: { fa: 'تاریخ شروع', en: 'Start Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'end_date',
      labels: { fa: 'تاریخ پایان', en: 'End Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 3,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'is_active',
      labels: { fa: 'سال فعال', en: 'Is Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'status',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_closed',
      labels: { fa: 'بسته شده', en: 'Is Closed' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'status',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'closed_at',
      labels: { fa: 'تاریخ بستن', en: 'Closed At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'status',
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
  ],
  blocks: [
    {
      id: 'status',
      titles: { fa: 'وضعیت سال مالی', en: 'Status' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'CalendarOutlined',
    },
  ],
  relatedTabs: [],
};
