import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';
import { instructionStatusOptions } from '../utils/instructionSupport';

export const instructionsModule: ModuleDefinition = {
  id: 'instructions',
  titles: { fa: 'دستورالعمل‌ها', faSingular: 'دستورالعمل', en: 'Instructions' },
  nature: ModuleNature.STANDARD,
  table: 'instructions',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: '{{name}}',
    searchFields: ['name', 'system_code', 'department', 'goal', 'body', 'id'],
  },
  fields: [
    {
      key: 'image_url',
      labels: { fa: 'تصویر', en: 'Image' },
      type: FieldType.IMAGE,
      location: FieldLocation.HEADER,
      order: 0,
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
    },
    {
      key: 'name',
      labels: { fa: 'نام دستورالعمل', en: 'Instruction Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'system_code',
      labels: { fa: 'کد سیستمی', en: 'System Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      options: instructionStatusOptions,
      defaultValue: 'draft',
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'department',
      labels: { fa: 'دپارتمان', en: 'Department' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 4,
      dynamicOptionsCategory: 'department',
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'module_ids',
      labels: { fa: 'مرتبط به ماژول', en: 'Related Modules' },
      type: FieldType.MULTI_SELECT,
      mode: 'multiple',
      location: FieldLocation.HEADER,
      order: 5,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'visible_to_user_ids',
      labels: { fa: 'قابل مشاهده برای کاربران', en: 'Visible To Users' },
      type: FieldType.MULTI_SELECT,
      mode: 'multiple',
      location: FieldLocation.BLOCK,
      blockId: 'visibility',
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'visible_to_role_ids',
      labels: { fa: 'قابل مشاهده برای نقش‌ها', en: 'Visible To Roles' },
      type: FieldType.MULTI_SELECT,
      mode: 'multiple',
      location: FieldLocation.BLOCK,
      blockId: 'visibility',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'goal',
      labels: { fa: 'هدف', en: 'Goal' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'content',
      order: 1,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'body',
      labels: { fa: 'متن دستورالعمل', en: 'Instruction Body' },
      type: FieldType.SUPER_LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'content',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 3.5, nature: FieldNature.STANDARD, isTableColumn: true },
  ],
  blocks: [
    {
      id: 'content',
      titles: { fa: 'متن و توضیحات', en: 'Content' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
    {
      id: 'visibility',
      titles: { fa: 'دسترسی مشاهده', en: 'Visibility' },
      type: BlockType.FIELD_GROUP,
      order: 2,
    },
  ],
  relatedTabs: [
    {
      id: 'instruction_process_templates',
      title: 'الگوهای فرآیند',
      icon: 'NodeIndexOutlined',
      relationType: 'join_table',
      targetModule: 'process_templates',
      joinTable: 'process_template_stage_instructions',
      joinSourceKey: 'instruction_id',
      joinTargetKey: 'template_id',
      disableCreate: true,
    },
  ],
};
