import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const journalEntriesConfig: ModuleDefinition = {
  id: 'journal_entries',
  titles: { fa: 'اسناد حسابداری', en: 'Journal Entries' },
  nature: ModuleNature.FINANCE,
  table: 'journal_entries',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'entry_no',
      labels: { fa: 'شماره سند', en: 'Entry No' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      isKey: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'entry_date',
      labels: { fa: 'تاریخ سند', en: 'Entry Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت سند', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
      options: [
        { label: 'پیش نویس', value: 'draft', color: 'orange' },
        { label: 'ثبت شده', value: 'posted', color: 'green' },
        { label: 'برگشتی', value: 'reversed', color: 'red' },
      ],
    },
    {
      key: 'fiscal_year_id',
      labels: { fa: 'سال مالی', en: 'Fiscal Year' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 1,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'fiscal_years', targetField: 'title' },
    },
    {
      key: 'description',
      labels: { fa: 'شرح', en: 'Description' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 2,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'source_module',
      labels: { fa: 'ماژول مرجع', en: 'Source Module' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'source',
      order: 1,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: 'source_table',
      labels: { fa: 'جدول مرجع', en: 'Source Table' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'source',
      order: 2,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'total_debit',
      labels: { fa: 'جمع بدهکار', en: 'Total Debit' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'totals',
      order: 1,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: 'total_credit',
      labels: { fa: 'جمع بستانکار', en: 'Total Credit' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'totals',
      order: 2,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: 'posted_at',
      labels: { fa: 'زمان ثبت نهایی', en: 'Posted At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'totals',
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
  ],
  blocks: [
    {
      id: 'base',
      titles: { fa: 'اطلاعات سند', en: 'Entry Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'FileTextOutlined',
    },
    {
      id: 'totals',
      titles: { fa: 'جمع سند', en: 'Totals' },
      type: BlockType.FIELD_GROUP,
      order: 2,
      icon: 'CalculatorOutlined',
    },
    {
      id: 'source',
      titles: { fa: 'ردیابی مرجع', en: 'Source Tracking' },
      type: BlockType.FIELD_GROUP,
      order: 3,
      icon: 'LinkOutlined',
    },
  ],
  relatedTabs: [],
};
