import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const journalLinesConfig: ModuleDefinition = {
  id: 'journal_lines',
  titles: { fa: 'آرتیکل های سند', en: 'Journal Lines' },
  nature: ModuleNature.FINANCE,
  table: 'journal_lines',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'entry_id',
      labels: { fa: 'سند حسابداری', en: 'Journal Entry' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
      relationConfig: { targetModule: 'journal_entries', targetField: 'entry_no' },
    },
    {
      key: 'line_no',
      labels: { fa: 'ردیف', en: 'Line No' },
      type: FieldType.NUMBER,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      isKey: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'account_id',
      labels: { fa: 'حساب', en: 'Account' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 3,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
      relationConfig: { targetModule: 'chart_of_accounts', targetField: 'name' },
    },
    {
      key: 'description',
      labels: { fa: 'شرح', en: 'Description' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'debit',
      labels: { fa: 'بدهکار', en: 'Debit' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'amounts',
      order: 1,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'credit',
      labels: { fa: 'بستانکار', en: 'Credit' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'amounts',
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'cost_center_id',
      labels: { fa: 'مرکز هزینه', en: 'Cost Center' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'tracking',
      order: 1,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'cost_centers', targetField: 'name' },
    },
    {
      key: 'party_type',
      labels: { fa: 'نوع طرف حساب', en: 'Party Type' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'tracking',
      order: 2,
      nature: FieldNature.STANDARD,
      options: [
        { label: 'مشتری', value: 'customer' },
        { label: 'تامین کننده', value: 'supplier' },
        { label: 'کاربر', value: 'profile' },
        { label: 'سایر', value: 'other' },
      ],
    },
    {
      key: 'party_id',
      labels: { fa: 'شناسه طرف حساب', en: 'Party ID' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'tracking',
      order: 3,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
  ],
  blocks: [
    {
      id: 'base',
      titles: { fa: 'اطلاعات آرتیکل', en: 'Line Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'FileTextOutlined',
    },
    {
      id: 'amounts',
      titles: { fa: 'مبالغ', en: 'Amounts' },
      type: BlockType.FIELD_GROUP,
      order: 2,
      icon: 'CalculatorOutlined',
    },
    {
      id: 'tracking',
      titles: { fa: 'تفصیلی و پیگیری', en: 'Tracking' },
      type: BlockType.FIELD_GROUP,
      order: 3,
      icon: 'TeamOutlined',
    },
  ],
  relatedTabs: [],
};
