import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const leaveRequestsModule: ModuleDefinition = {
  id: 'leave_requests',
  titles: { fa: 'مرخصی‌ها', faSingular: 'درخواست مرخصی', en: 'Leave Requests' },
  nature: ModuleNature.STANDARD,
  table: 'leave_requests',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'employee_id',
      labels: { fa: 'کارمند', en: 'Employee' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      validation: { required: true },
      relationConfig: { targetModule: 'employees', targetField: 'full_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      defaultValue: 'pending',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'در انتظار', value: 'pending', color: 'orange' },
        { label: 'تایید شده', value: 'approved', color: 'green' },
        { label: 'رد شده', value: 'rejected', color: 'red' },
        { label: 'لغو شده', value: 'canceled', color: 'default' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'leave_type',
      labels: { fa: 'نوع مرخصی', en: 'Leave Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'daily',
      isTableColumn: true,
      options: [
        { label: 'روزانه', value: 'daily' },
        { label: 'ساعتی', value: 'hourly' },
        { label: 'استحقاقی', value: 'paid' },
        { label: 'بدون حقوق', value: 'unpaid' },
        { label: 'استعلاجی', value: 'medical' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'start_date',
      labels: { fa: 'از تاریخ', en: 'Start Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'end_date',
      labels: { fa: 'تا تاریخ', en: 'End Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'total_days',
      labels: { fa: 'جمع روز', en: 'Total Days' },
      type: FieldType.NUMBER,
      blockId: 'details',
      order: 6,
      defaultValue: 0,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'total_minutes',
      labels: { fa: 'جمع دقیقه', en: 'Total Minutes' },
      type: FieldType.NUMBER,
      blockId: 'details',
      order: 6.1,
      defaultValue: 0,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'توضیحات', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      blockId: 'details',
      order: 7,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'details',
      titles: { fa: 'جزئیات مرخصی', en: 'Leave Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
