import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  LogicOperator,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';
import { createWebFormTemplateRecordSaver } from '../utils/webFormTemplateFormAdapter';

const saveMarketingLeadRecord = createWebFormTemplateRecordSaver({
  moduleId: 'marketing_leads',
  table: 'marketing_leads',
});

export const marketingLeadsModule: ModuleDefinition = {
  id: 'marketing_leads',
  titles: { fa: 'لیدهای بازاریابی', en: 'Marketing Leads' },
  nature: ModuleNature.MARKETING,
  table: 'marketing_leads',
  supportedViewModes: [ViewMode.LIST, ViewMode.KANBAN, ViewMode.GRID],
  defaultViewMode: ViewMode.KANBAN,
  formAdapter: {
    save: saveMarketingLeadRecord,
  },
  fields: [
    {
      key: 'name',
      labels: { fa: 'عنوان لید', en: 'Lead Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'business_name',
      labels: { fa: 'نام کسب‌وکار', en: 'Business Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'sarnakh_code',
      labels: { fa: 'کد سیستم قبلی', en: 'Legacy System Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2.1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'new',
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'جدید', value: 'new', color: 'blue' },
        { label: 'در حال پیگیری', value: 'in_follow_up', color: 'orange' },
        { label: 'پیگیری معوق', value: 'overdue_follow_up', color: 'red' },
        { label: 'پیگیری در آینده', value: 'future_follow_up', color: 'cyan' },
        { label: 'برنده', value: 'won', color: 'green' },
        { label: 'از دست رفته', value: 'lost', color: 'default' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'lead_type',
      labels: { fa: 'نوع لید', en: 'Lead Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 'new_lead',
      isTableColumn: true,
      options: [
        { label: 'لید جدید', value: 'new_lead' },
        { label: 'مشتری قبلی', value: 'existing_customer' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'success_percentage',
      labels: { fa: 'درصد موفقیت', en: 'Success Percentage' },
      type: FieldType.PERCENTAGE,
      location: FieldLocation.HEADER,
      order: 5,
      defaultValue: 0,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'source',
      labels: { fa: 'منبع سرنخ', en: 'Lead Source' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 6,
      dynamicOptionsCategory: 'lead_source',
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'survey_template_id',
      labels: { fa: 'قالب وب‌فرم', en: 'Web Form Template' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 6.5,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      relationConfig: {
        targetModule: 'web_forms',
        filter: {
          target_module_id: 'marketing_leads',
          is_active: true,
        },
      },
    },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 7, nature: FieldNature.STANDARD, isTableColumn: true },
    //{
      //key: 'lead_source',
      //labels: { fa: 'منبع لید', en: 'Source Detail' },
      //type: FieldType.SELECT,
      //location: FieldLocation.HEADER,
      //order: 7,
      //dynamicOptionsCategory: 'lead_source',
      //nature: FieldNature.STANDARD,
    //},
    {
      key: 'customer_id',
      labels: { fa: 'مشتری مرتبط', en: 'Customer' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 0.9,
      relationConfig: { targetModule: 'customers', targetField: 'full_name' },
      logic: { visibleIf: { field: 'lead_type', operator: LogicOperator.EQUALS, value: 'existing_customer' } },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'persona_id',
      labels: { fa: 'پرسونا', en: 'Persona' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 0.95,
      relationConfig: {
        targetModule: 'personas',
        targetField: 'display_name',
        filter: { persona_type: 'customer' },
      },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'prefix',
      labels: { fa: 'پیشوند', en: 'Prefix' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 1,
      options: [
        { label: 'آقای', value: 'آقای' },
        { label: 'خانم', value: 'خانم' },
        { label: 'آقای دکتر', value: 'آقای دکتر' },
        { label: 'خانم دکتر', value: 'خانم دکتر' },
        { label: 'آقای مهندس', value: 'آقای مهندس' },
        { label: 'خانم مهندس', value: 'خانم مهندس' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'first_name',
      labels: { fa: 'نام مشتری', en: 'First Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'last_name',
      labels: { fa: 'نام خانوادگی مشتری', en: 'Last Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'industry',
      labels: { fa: 'صنعت', en: 'Industry' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 4,
      dynamicOptionsCategory: 'customer_industry',
      nature: FieldNature.STANDARD,
    },
    {
      key: 'customer_interests',
      labels: { fa: 'علاقمندی‌های مشتری', en: 'Customer Interests' },
      type: FieldType.MULTI_SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 4.1,
      dynamicOptionsCategory: 'customer_interests',
      nature: FieldNature.STANDARD,
    },
    {
      key: 'mobile',
      labels: { fa: 'شماره موبایل', en: 'Mobile' },
      type: FieldType.PHONE,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'mobile_2',
      labels: { fa: 'شماره موبایل 2', en: 'Mobile 2' },
      type: FieldType.PHONE,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'assistant_phone',
      labels: { fa: 'شماره دستیار', en: 'Assistant Phone' },
      type: FieldType.PHONE,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 3,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'email',
      labels: { fa: 'ایمیل', en: 'Email' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'province',
      labels: { fa: 'استان', en: 'Province' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 5,
      dynamicOptionsCategory: 'provinces',
      nature: FieldNature.STANDARD,
    },
    {
      key: 'city',
      labels: { fa: 'شهر', en: 'City' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 6,
      dynamicOptionsCategory: 'cities',
      nature: FieldNature.STANDARD,
    },
    {
      key: 'address',
      labels: { fa: 'آدرس', en: 'Address' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 7,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'location',
      labels: { fa: 'موقعیت', en: 'Location' },
      type: FieldType.LOCATION,
      location: FieldLocation.BLOCK,
      blockId: 'contact_info',
      order: 8,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'project_id',
      labels: { fa: 'پروژه مرتبط', en: 'Project' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 1,
      relationConfig: { targetModule: 'projects', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'process_template_id',
      labels: { fa: 'الگوی فرآیند بازاریابی', en: 'Marketing Template' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 1,
      relationConfig: { targetModule: 'process_templates', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'marketing_process_draft',
      labels: { fa: 'فرآیند بازاریابی', en: 'Marketing Process' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'یادداشت', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'notes',
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'template_field_values',
      labels: { fa: 'داده‌های قالب', en: 'Template Values' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'notes',
      order: 90,
      readonly: true,
      hideInCreateForm: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'template_schema_snapshot',
      labels: { fa: 'اسنپ‌شات قالب', en: 'Template Snapshot' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'notes',
      order: 91,
      readonly: true,
      hideInCreateForm: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: 'base_info',
      titles: { fa: 'اطلاعات پایه', en: 'Base Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
    {
      id: 'contact_info',
      titles: { fa: 'اطلاعات تماس', en: 'Contact Info' },
      type: BlockType.FIELD_GROUP,
      order: 2,
    },
    {
      id: 'relations',
      titles: { fa: 'ارتباطات', en: 'Relations' },
      type: BlockType.FIELD_GROUP,
      order: 3,
    },
    {
      id: 'process',
      titles: { fa: 'فرآیند بازاریابی', en: 'Marketing Process' },
      type: BlockType.FIELD_GROUP,
      order: 4,
    },
    {
      id: 'notes',
      titles: { fa: 'یادداشت‌ها', en: 'Notes' },
      type: BlockType.FIELD_GROUP,
      order: 5,
    },
  ],
  relatedTabs: [
    {
      id: 'lead_tasks',
      title: 'فعالیت ها',
      icon: 'CheckSquareOutlined',
      relationType: 'fk',
      targetModule: 'tasks',
      foreignKey: 'marketing_lead_id',
    },
    {
      id: 'lead_sms_reports',
      title: 'پیامک‌ها',
      icon: 'MessageOutlined',
      relationType: 'phone_directory',
      targetModule: 'sms_delivery_reports',
      disableCreate: true,
    },
    {
      id: 'lead_voip_calls',
      title: 'تماس‌ها',
      icon: 'PhoneOutlined',
      relationType: 'phone_directory',
      targetModule: 'voip_call_reports',
      disableCreate: true,
    },
    {
      id: 'lead_surveys',
      title: 'نظرسنجی‌ها',
      icon: 'CommentOutlined',
      relationType: 'fk',
      targetModule: 'surveys',
      foreignKey: 'related_record_id',
      filters: [{ field: 'related_module_id', value: 'marketing_leads' }],
    },
  ],
};
