import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const marketingLeadsModule: ModuleDefinition = {
  id: 'marketing_leads',
  titles: { fa: 'لیدهای بازاریابی', en: 'Marketing Leads' },
  nature: ModuleNature.MARKETING,
  table: 'marketing_leads',
  supportedViewModes: [ViewMode.LIST, ViewMode.KANBAN, ViewMode.GRID],
  defaultViewMode: ViewMode.KANBAN,
  fields: [
    {
      key: 'name',
      labels: { fa: 'نام لید', en: 'Lead Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'business_name',
      labels: { fa: 'نام کسب‌وکار', en: 'Business Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'new',
      options: [
        { label: 'جدید', value: 'new', color: 'blue' },
        { label: 'تماس گرفته شده', value: 'contacted', color: 'orange' },
        { label: 'واجد شرایط', value: 'qualified', color: 'cyan' },
        { label: 'پیشنهاد', value: 'proposal', color: 'purple' },
        { label: 'برنده', value: 'won', color: 'green' },
        { label: 'از دست رفته', value: 'lost', color: 'red' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'source',
      labels: { fa: 'منبع لید', en: 'Source' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 4,
      dynamicOptionsCategory: 'lead_sources',
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'score',
      labels: { fa: 'امتیاز', en: 'Score' },
      type: FieldType.NUMBER,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'mobile',
      labels: { fa: 'موبایل', en: 'Mobile' },
      type: FieldType.PHONE,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 1,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'email',
      labels: { fa: 'ایمیل', en: 'Email' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'owner_id',
      labels: { fa: 'مسئول لید', en: 'Owner' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 3,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'customer_id',
      labels: { fa: 'مشتری مرتبط', en: 'Customer' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 1,
      relationConfig: { targetModule: 'customers', targetField: 'last_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'project_id',
      labels: { fa: 'پروژه مرتبط', en: 'Project' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'relations',
      order: 2,
      relationConfig: { targetModule: 'projects', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'process_template_id',
      labels: { fa: 'الگوی فرآیند بازاریابی', en: 'Marketing Template' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 1,
      relationConfig: { targetModule: 'process_templates', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'marketing_process_draft',
      labels: { fa: 'فرآیند بازاریابی', en: 'Marketing Process' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'location',
      labels: { fa: 'موقعیت', en: 'Location' },
      type: FieldType.LOCATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'یادداشت', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 5,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'base_info',
      titles: { fa: 'اطلاعات پایه', en: 'Base Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
    {
      id: 'relations',
      titles: { fa: 'ارتباطات', en: 'Relations' },
      type: BlockType.FIELD_GROUP,
      order: 2,
    },
    {
      id: 'process',
      titles: { fa: 'فرآیند بازاریابی', en: 'Marketing Process' },
      type: BlockType.FIELD_GROUP,
      order: 3,
    },
  ],
  relatedTabs: [
    {
      id: 'lead_tasks',
      title: 'وظایف',
      icon: 'CheckSquareOutlined',
      relationType: 'fk',
      targetModule: 'tasks',
      foreignKey: 'marketing_lead_id',
    },
  ],
};

