import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const missionRequestsModule: ModuleDefinition = {
  id: 'mission_requests',
  titles: { fa: 'ماموریت‌ها', faSingular: 'درخواست ماموریت', en: 'Mission Requests' },
  nature: ModuleNature.STANDARD,
  table: 'mission_requests',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'employee_id',
      labels: { fa: 'کارمند', en: 'Employee' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      validation: { required: true },
      relationConfig: { targetModule: 'employees', targetField: 'full_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      defaultValue: 'pending',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'در انتظار', value: 'pending', color: 'orange' },
        { label: 'تایید شده', value: 'approved', color: 'green' },
        { label: 'رد شده', value: 'rejected', color: 'red' },
        { label: 'لغو شده', value: 'canceled', color: 'default' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'start_date',
      labels: { fa: 'از تاریخ', en: 'Start Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'end_date',
      labels: { fa: 'تا تاریخ', en: 'End Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'destination',
      labels: { fa: 'مقصد', en: 'Destination' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'توضیحات', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      blockId: 'details',
      order: 6,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'details',
      titles: { fa: 'جزئیات ماموریت', en: 'Mission Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
