import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const overtimeRequestsModule: ModuleDefinition = {
  id: 'overtime_requests',
  titles: { fa: 'اضافه‌کاری‌ها', faSingular: 'درخواست اضافه‌کاری', en: 'Overtime Requests' },
  nature: ModuleNature.STANDARD,
  table: 'overtime_requests',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'employee_id',
      labels: { fa: 'کارمند', en: 'Employee' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      validation: { required: true },
      relationConfig: { targetModule: 'employees', targetField: 'full_name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      defaultValue: 'pending',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'در انتظار', value: 'pending', color: 'orange' },
        { label: 'تایید شده', value: 'approved', color: 'green' },
        { label: 'رد شده', value: 'rejected', color: 'red' },
        { label: 'لغو شده', value: 'canceled', color: 'default' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'work_date',
      labels: { fa: 'تاریخ', en: 'Work Date' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'start_time',
      labels: { fa: 'از ساعت', en: 'Start Time' },
      type: FieldType.TIME,
      blockId: 'details',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'end_time',
      labels: { fa: 'تا ساعت', en: 'End Time' },
      type: FieldType.TIME,
      blockId: 'details',
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'total_minutes',
      labels: { fa: 'جمع دقیقه', en: 'Total Minutes' },
      type: FieldType.NUMBER,
      blockId: 'details',
      order: 6,
      defaultValue: 0,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'توضیحات', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      blockId: 'details',
      order: 7,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'details',
      titles: { fa: 'جزئیات اضافه‌کاری', en: 'Overtime Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
