import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, RowCalculationType, SummaryCalculationType, ViewMode } from '../types';

export const payrollSlipsConfig: ModuleDefinition = {
  id: 'payroll_slips',
  titles: { fa: 'فیش‌های حقوقی', faSingular: 'فیش حقوقی', en: 'Payroll Slips' },
  nature: ModuleNature.FINANCE,
  table: 'payroll_slips',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: { labelTemplate: '{{system_code}} - {{name}}', searchFields: ['name', 'system_code', 'notes'] },
  fields: [
    { key: 'name', labels: { fa: 'عنوان فیش', en: 'Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'شماره فیش', en: 'Slip No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'employee_id', labels: { fa: 'کارمند', en: 'Employee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 3, validation: { required: true }, relationConfig: { targetModule: 'employees', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'period_start', labels: { fa: 'از تاریخ', en: 'Period Start' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 4, validation: { required: true }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'period_end', labels: { fa: 'تا تاریخ', en: 'Period End' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 5, validation: { required: true }, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 6,
      defaultValue: 'draft',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'تایید شده', value: 'approved', color: 'blue' },
        { label: 'پرداخت شده', value: 'paid', color: 'green' },
        { label: 'سند شده', value: 'posted', color: 'purple' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
      ],
    },
    { key: 'assignee_id', labels: { fa: 'مسئول پرداخت', en: 'Assignee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 7, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 7.1, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'base_salary', labels: { fa: 'حقوق پایه', en: 'Base Salary' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 1, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'task_wage_total', labels: { fa: 'کارکرد', en: 'Task Wage' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 2, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'bonus_total', labels: { fa: 'مزایا', en: 'Bonuses' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 3, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'deduction_total', labels: { fa: 'کسورات', en: 'Deductions' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 4, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'insurance_employee_amount', labels: { fa: 'بیمه سهم کارمند', en: 'Employee Insurance' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 5, nature: FieldNature.STANDARD },
    { key: 'insurance_employer_amount', labels: { fa: 'بیمه سهم کارفرما', en: 'Employer Insurance' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 6, nature: FieldNature.STANDARD },
    { key: 'gross_amount', labels: { fa: 'ناخالص', en: 'Gross' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 7, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'net_amount', labels: { fa: 'خالص پرداختی', en: 'Net Amount' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 8, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'performance_snapshot', labels: { fa: 'اسنپ‌شات عملکرد', en: 'Performance Snapshot' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'tracking', order: 1, nature: FieldNature.STANDARD },
    { key: 'task_ids', labels: { fa: 'فعالیت‌های مبنا', en: 'Task IDs' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'tracking', order: 2, nature: FieldNature.STANDARD },
    { key: 'notes', labels: { fa: 'توضیحات', en: 'Notes' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'tracking', order: 3, nature: FieldNature.STANDARD },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
  ],
  blocks: [
    {
      id: 'lines',
      titles: { fa: 'ردیف‌های فیش حقوقی', en: 'Payroll Lines' },
      type: BlockType.TABLE,
      order: 1,
      rowCalculationType: RowCalculationType.SIMPLE_MULTIPLY,
      tableColumns: [
        { key: 'line_type', title: 'نوع ردیف', type: FieldType.SELECT, width: 140, options: [{ label: 'حقوق', value: 'earning' }, { label: 'مزایا', value: 'bonus' }, { label: 'کسورات', value: 'deduction' }] },
        { key: 'title', title: 'شرح', type: FieldType.TEXT, width: 220 },
        { key: 'amount', title: 'مبلغ', type: FieldType.PRICE, width: 160, showTotal: true },
        { key: 'description', title: 'توضیحات', type: FieldType.LONG_TEXT, width: 240 },
      ],
    },
    {
      id: 'payments',
      titles: { fa: 'جدول پرداخت‌ها', en: 'Payments' },
      type: BlockType.TABLE,
      order: 2,
      rowCalculationType: RowCalculationType.SIMPLE_MULTIPLY,
      tableColumns: [
        { key: 'payment_type', title: 'روش پرداخت', type: FieldType.SELECT, width: 140, options: [{ label: 'نقد', value: 'cash' }, { label: 'بانک', value: 'bank' }, { label: 'کارت', value: 'card' }] },
        {
          key: 'source_account',
          title: 'حساب پرداخت',
          type: FieldType.RELATION,
          width: 220,
          relationConfig: {
            targetModule: 'bank_accounts',
            targetField: 'bank_name',
            filter: { is_active: true },
            sourceModules: [
              { targetModule: 'bank_accounts', targetField: 'bank_name', filter: { is_active: true }, tagLabel: 'بانک', tagColor: 'cyan' },
              { targetModule: 'cash_boxes', targetField: 'name', filter: { is_active: true }, tagLabel: 'صندوق', tagColor: 'gold' },
              { targetModule: 'petty_funds', targetField: 'name', filter: { is_active: true }, tagLabel: 'تنخواه', tagColor: 'magenta' },
            ],
          },
        },
        { key: 'date', title: 'تاریخ', type: FieldType.DATE, width: 130 },
        { key: 'amount', title: 'مبلغ', type: FieldType.PRICE, width: 160, showTotal: true },
      ],
    },
    { id: 'summary', titles: { fa: 'خلاصه حقوق', en: 'Summary' }, type: BlockType.FIELD_GROUP, order: 3, summaryConfig: { calculationType: SummaryCalculationType.SUM_ALL_ROWS, fieldMapping: { total: 'gross_amount', remaining: 'net_amount' } } },
    { id: 'tracking', titles: { fa: 'ردیابی و توضیحات', en: 'Tracking' }, type: BlockType.FIELD_GROUP, order: 4 },
    { id: 'process', titles: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: BlockType.FIELD_GROUP, order: 5 },
  ],
  relatedTabs: [],
  actionButtons: [{ id: 'create_journal_entry', label: 'صدور سند', placement: 'header', variant: 'primary' }],
};
