import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const personasModule: ModuleDefinition = {
  id: 'personas',
  titles: { fa: 'پرسونا', faSingular: 'پرسونا', en: 'Personas' },
  nature: ModuleNature.MARKETING,
  table: 'personas',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID, ViewMode.KANBAN],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: '{{display_name}} - {{persona_type}}',
    searchFields: ['name', 'display_name', 'persona_type', 'financial_status', 'traits', 'preferences', 'pain_points', 'basket', 'id'],
  },
  fields: [
    {
      key: 'name',
      labels: { fa: 'پرسونا', en: 'Persona' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'display_name',
      labels: { fa: 'نام نمایشی', en: 'Display Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1.1,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'persona_type',
      labels: { fa: 'نوع پرسونا', en: 'Persona Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 1.2,
      isTableColumn: true,
      defaultValue: 'customer',
      options: [
        { label: 'مشتری', value: 'customer', color: 'blue' },
        { label: 'تامین‌کننده', value: 'supplier', color: 'orange' },
        { label: 'کارمند', value: 'employee', color: 'green' },
      ],
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'financial_status',
      labels: { fa: 'وضعیت مالی', en: 'Financial Status' },
      type: FieldType.LONG_TEXT,
      blockId: 'persona_profile',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'traits',
      labels: { fa: 'ویژگی‌ها', en: 'Traits' },
      type: FieldType.SUPER_LONG_TEXT,
      blockId: 'persona_profile',
      order: 2.1,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'preferences',
      labels: { fa: 'ترجیحات', en: 'Preferences' },
      type: FieldType.SUPER_LONG_TEXT,
      blockId: 'persona_profile',
      order: 2.2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'pain_points',
      labels: { fa: 'نقطه درد', en: 'Pain Points' },
      type: FieldType.SUPER_LONG_TEXT,
      blockId: 'persona_profile',
      order: 2.3,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'basket',
      labels: { fa: 'سبد خرید', en: 'Basket' },
      type: FieldType.SUPER_LONG_TEXT,
      blockId: 'persona_profile',
      order: 2.4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'image_url',
      labels: { fa: 'فایل/تصویر', en: 'Image/File' },
      type: FieldType.IMAGE,
      location: FieldLocation.HEADER,
      order: 0.8,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'created_at',
      labels: { fa: 'زمان ایجاد', en: 'Created At' },
      type: FieldType.DATETIME,
      blockId: 'system_info',
      order: 9,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'created_by',
      labels: { fa: 'ایجاد کننده', en: 'Created By' },
      type: FieldType.USER,
      blockId: 'system_info',
      order: 9.1,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'updated_at',
      labels: { fa: 'زمان ویرایش', en: 'Updated At' },
      type: FieldType.DATETIME,
      blockId: 'system_info',
      order: 9.2,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'updated_by',
      labels: { fa: 'ویرایش کننده', en: 'Updated By' },
      type: FieldType.USER,
      blockId: 'system_info',
      order: 9.3,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: 'persona_profile',
      titles: { fa: 'مشخصات پرسونا', en: 'Persona Profile' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
    {
      id: 'system_info',
      titles: { fa: 'اطلاعات سیستمی', en: 'System Info' },
      type: BlockType.FIELD_GROUP,
      order: 99,
    },
  ],
};
