import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature } from '../types';

export const pettyFundsConfig: ModuleDefinition = {
  id: 'petty_funds',
  titles: { fa: 'تنخواه گردان ها', en: 'Petty Funds' },
  nature: ModuleNature.FINANCE,
  table: 'petty_funds',
  relationDisplay: {
    labelTemplate: '{{name}} - {{code}}',
    searchFields: ['name', 'code'],
  },
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'code',
      labels: { fa: 'کد تنخواه', en: 'Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'name',
      labels: { fa: 'نام تنخواه', en: 'Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      isKey: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'account_id',
      labels: { fa: 'حساب متناظر', en: 'Account' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 1,
      nature: FieldNature.STANDARD,
      validation: { required: true },
      relationConfig: {
        targetModule: 'chart_of_accounts',
        targetField: 'name',
        chartScopeRootNames: ['وجوه نقد و بانک', 'تنخواه گردان ها', 'تنخواه‌گردان ها', 'تنخواه گردانها', 'تنخواه‌گردان‌ها'],
        requireLeaf: true,
        requireDetail: true,
      },
    },
    {
      key: 'responsible_id',
      labels: { fa: 'مسئول تنخواه', en: 'Responsible' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 2,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
    },
    {
      key: 'opening_balance',
      labels: { fa: 'موجودی اول دوره', en: 'Opening Balance' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Is Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'base',
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'base',
      titles: { fa: 'اطلاعات تنخواه', en: 'Petty Fund Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'WalletOutlined',
    },
  ],
  relatedTabs: [],
};
