import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const processRunsModule: ModuleDefinition = {
  id: 'process_runs',
  titles: { fa: 'اجرای فرآیندها', en: 'Process Runs' },
  nature: ModuleNature.STANDARD,
  table: 'process_runs',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'process_name',
      labels: { fa: 'نام فرآیند', en: 'Process Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'module_id',
      labels: { fa: 'ماژول', en: 'Module' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'record_id',
      labels: { fa: 'شناسه رکورد', en: 'Record ID' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 3,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'فعال', value: 'active', color: 'blue' },
        { label: 'تکمیل شده', value: 'completed', color: 'green' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'copied_mode',
      labels: { fa: 'نوع ایجاد', en: 'Copied Mode' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 5,
      options: [
        { label: 'دستی', value: 'manual', color: 'default' },
        { label: 'خودکار', value: 'auto', color: 'purple' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'template_id',
      labels: { fa: 'الگوی مرجع', en: 'Template' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 1,
      relationConfig: { targetModule: 'process_templates', targetField: 'name' },
      nature: FieldNature.STANDARD,
      readonly: true,
    },
    {
      key: 'started_at',
      labels: { fa: 'زمان شروع', en: 'Started At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 2,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: 'completed_at',
      labels: { fa: 'زمان تکمیل', en: 'Completed At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
  ],
  blocks: [
    {
      id: 'base_info',
      titles: { fa: 'اطلاعات اجرا', en: 'Run Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
