import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const processTemplatesModule: ModuleDefinition = {
  id: 'process_templates',
  titles: { fa: 'الگوهای فرآیند', en: 'Process Templates' },
  nature: ModuleNature.STANDARD,
  table: 'process_templates',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'image_url',
      labels: { fa: 'تصویر', en: 'Image' },
      type: FieldType.IMAGE,
      location: FieldLocation.HEADER,
      order: 0,
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
    },
    {
      key: 'name',
      labels: { fa: 'نام الگو', en: 'Template Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'module_ids',
      labels: { fa: 'ماژول‌های هدف', en: 'Target Modules' },
      type: FieldType.MULTI_SELECT,
      mode: 'multiple',
      location: FieldLocation.HEADER,
      order: 2,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'module_id',
      labels: { fa: 'ماژول اصلی', en: 'Primary Module' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      readonly: true,
      hideInCreateForm: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 4.1, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'description',
      labels: { fa: 'توضیحات', en: 'Description' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 7,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'template_stages_preview',
      labels: { fa: 'مراحل الگو', en: 'Template Stages' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 2,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: false,
    },
  ],
  blocks: [
    {
      id: 'base_info',
      titles: { fa: 'اطلاعات الگو', en: 'Template Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
