import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const processTemplatesModule: ModuleDefinition = {
  id: 'process_templates',
  titles: { fa: 'الگوهای فرآیند', en: 'Process Templates' },
  nature: ModuleNature.STANDARD,
  table: 'process_templates',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'name',
      labels: { fa: 'نام الگو', en: 'Template Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'module_id',
      labels: { fa: 'ماژول هدف', en: 'Target Module' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 2,
      options: [
        { label: 'سفارشات تولید', value: 'production_orders' },
        { label: 'پروژه‌ها', value: 'projects' },
        { label: 'لیدهای بازاریابی', value: 'marketing_leads' },
        { label: 'مشتریان', value: 'customers' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'process_kind',
      labels: { fa: 'نوع فرآیند', en: 'Process Kind' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'generic',
      options: [
        { label: 'عمومی', value: 'generic', color: 'default' },
        { label: 'تولید', value: 'production', color: 'blue' },
        { label: 'اجرا', value: 'execution', color: 'green' },
        { label: 'بازاریابی', value: 'marketing', color: 'orange' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'auto_copy_mode',
      labels: { fa: 'حالت کپی خودکار', en: 'Auto Copy Mode' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 'manual',
      options: [
        { label: 'دستی', value: 'manual', color: 'default' },
        { label: 'در ایجاد رکورد', value: 'on_create', color: 'blue' },
        { label: 'در تغییر وضعیت', value: 'on_status_change', color: 'purple' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.HEADER,
      order: 5,
      defaultValue: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'source_bom_id',
      labels: { fa: 'شناسنامه تولید مرجع', en: 'Source BOM' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 1,
      relationConfig: { targetModule: 'production_boms', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'description',
      labels: { fa: 'توضیحات', en: 'Description' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'template_stages_preview',
      labels: { fa: 'مراحل الگو', en: 'Template Stages' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: 'base_info',
      titles: { fa: 'اطلاعات الگو', en: 'Template Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};

