import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  RowCalculationType,
  ViewMode,
} from '../types';

const BLOCKS = {
  baseInfo: {
    id: 'baseInfo',
    titles: { fa: 'اطلاعات پایه', en: 'Basic Info' },
    icon: 'InfoCircleOutlined',
    order: 1,
    type: BlockType.FIELD_GROUP,
  },
  products: {
    id: 'products',
    titles: { fa: 'اقلام پکیج', en: 'Package Items' },
    icon: 'TableOutlined',
    order: 2,
    type: BlockType.TABLE,
    rowCalculationType: RowCalculationType.INVOICE_ROW,
    tableColumns: [
      {
        key: 'product_id',
        title: 'کالا / خدمت',
        type: FieldType.RELATION,
        width: 300,
        relationConfig: {
          targetModule: 'products',
          targetField: 'name',
          sourceModules: [
            { targetModule: 'products', targetField: 'name' },
            { targetModule: 'billboards', targetField: 'name', tagLabel: 'محیطی', tagColor: 'purple' },
          ],
        },
      },
      {
        key: 'quantity',
        title: 'تعداد / مقدار',
        type: FieldType.NUMBER,
        width: 130,
      },
      {
        key: 'main_unit',
        title: 'واحد',
        type: FieldType.TEXT,
        width: 120,
      },
      {
        key: 'unit_price',
        title: 'قیمت واحد',
        type: FieldType.PRICE,
        width: 150,
        readonly: true,
      },
      {
        key: 'discount',
        title: 'تخفیف پکیج',
        type: FieldType.PERCENTAGE_OR_AMOUNT,
        width: 140,
        showTotal: true,
      },
      {
        key: 'total_price',
        title: 'قیمت پکیج',
        type: FieldType.PRICE,
        width: 160,
        readonly: true,
        showTotal: true,
      },
    ],
  },
};

export const productBundlesConfig: ModuleDefinition = {
  id: 'product_bundles',
  titles: { fa: 'پکیج‌ها', faSingular: 'پکیج', en: 'Sales Packages' },
  nature: ModuleNature.PRODUCT,
  table: 'product_bundles',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'image_url',
      labels: { fa: 'تصویر / فایل', en: 'Image' },
      type: FieldType.IMAGE,
      location: FieldLocation.HEADER,
      order: 0,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'name',
      labels: { fa: 'نام پکیج', en: 'Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      defaultValue: 'active',
      isTableColumn: true,
      options: [
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'غیرفعال', value: 'draft', color: 'orange' },
      ],
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'notes',
      labels: { fa: 'توضیحات', en: 'Description' },
      type: FieldType.SUPER_LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'baseInfo',
      order: 3,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'created_at',
      labels: { fa: 'تاریخ ایجاد', en: 'Created At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'baseInfo',
      order: 10,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [BLOCKS.baseInfo, BLOCKS.products],
};
