import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const productionGroupOrdersModule: ModuleDefinition = {
  id: 'production_group_orders',
  titles: { fa: 'سفارشات گروهی تولید', en: 'Production Group Orders' },
  nature: ModuleNature.PRODUCTION,
  table: 'production_group_orders',
  supportedViewModes: [ViewMode.LIST],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'name',
      labels: { fa: 'عنوان سفارش گروهی', en: 'Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'system_code',
      labels: { fa: 'کد سیستمی', en: 'System Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'pending',
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'gray' },
        { label: 'در انتظار', value: 'pending', color: 'orange' },
        { label: 'در حال تولید', value: 'in_progress', color: 'blue' },
        { label: 'تکمیل شده', value: 'completed', color: 'green' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'production_order_ids',
      labels: { fa: 'سفارش‌های تولید مرتبط', en: 'Production Orders' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'orders',
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'started_at',
      labels: { fa: 'زمان شروع', en: 'Started At' },
      type: FieldType.DATETIME,
      location: FieldLocation.HEADER,
      order: 4,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: 'completed_at',
      labels: { fa: 'زمان تکمیل', en: 'Completed At' },
      type: FieldType.DATETIME,
      location: FieldLocation.HEADER,
      order: 5,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
  ],
  blocks: [
    {
      id: 'orders',
      titles: { fa: 'سفارش‌های گروه', en: 'Group Orders' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
