import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const projectsModule: ModuleDefinition = {
  id: 'projects',
  titles: { fa: 'پروژه‌ها', en: 'Projects' },
  nature: ModuleNature.STANDARD,
  table: 'projects',
  supportedViewModes: [ViewMode.LIST, ViewMode.KANBAN, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'name',
      labels: { fa: 'عنوان پروژه', en: 'Project Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: 'system_code',
      labels: { fa: 'کد سیستمی', en: 'System Code' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'draft',
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'gray' },
        { label: 'برنامه‌ریزی', value: 'planning', color: 'blue' },
        { label: 'در حال اجرا', value: 'in_progress', color: 'orange' },
        { label: 'متوقف', value: 'on_hold', color: 'red' },
        { label: 'تکمیل شده', value: 'completed', color: 'green' },
        { label: 'لغو شده', value: 'canceled', color: 'default' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'priority',
      labels: { fa: 'اولویت', en: 'Priority' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 'medium',
      options: [
        { label: 'کم', value: 'low', color: 'default' },
        { label: 'متوسط', value: 'medium', color: 'blue' },
        { label: 'بالا', value: 'high', color: 'orange' },
        { label: 'فوری', value: 'urgent', color: 'red' },
      ],
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'customer_id',
      labels: { fa: 'مشتری', en: 'Customer' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 1,
      relationConfig: { targetModule: 'customers', targetField: 'last_name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'owner_id',
      labels: { fa: 'مدیر پروژه', en: 'Owner' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 2,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'start_date',
      labels: { fa: 'تاریخ شروع', en: 'Start Date' },
      type: FieldType.DATE,
      location: FieldLocation.BLOCK,
      blockId: 'schedule',
      order: 1,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'due_date',
      labels: { fa: 'تاریخ پایان', en: 'Due Date' },
      type: FieldType.DATE,
      location: FieldLocation.BLOCK,
      blockId: 'schedule',
      order: 2,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'completed_at',
      labels: { fa: 'زمان تکمیل', en: 'Completed At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'schedule',
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: 'estimated_budget',
      labels: { fa: 'بودجه برآوردی', en: 'Estimated Budget' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'actual_cost',
      labels: { fa: 'هزینه واقعی', en: 'Actual Cost' },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 2,
      nature: FieldNature.STANDARD,
      readonly: true,
    },
    {
      key: 'progress_percent',
      labels: { fa: 'درصد پیشرفت', en: 'Progress %' },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: 'financial',
      order: 3,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'process_template_id',
      labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 1,
      relationConfig: { targetModule: 'process_templates', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'execution_process_draft',
      labels: { fa: 'فرآیند اجرا', en: 'Execution Process' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'location',
      labels: { fa: 'موقعیت', en: 'Location' },
      type: FieldType.LOCATION,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 3,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'description',
      labels: { fa: 'توضیحات', en: 'Description' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'base_info',
      order: 4,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    {
      id: 'base_info',
      titles: { fa: 'اطلاعات پایه', en: 'Base Info' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
    {
      id: 'schedule',
      titles: { fa: 'زمان‌بندی', en: 'Schedule' },
      type: BlockType.FIELD_GROUP,
      order: 2,
    },
    {
      id: 'financial',
      titles: { fa: 'مالی', en: 'Financial' },
      type: BlockType.FIELD_GROUP,
      order: 3,
    },
    {
      id: 'process',
      titles: { fa: 'فرآیند اجرا', en: 'Execution Process' },
      type: BlockType.FIELD_GROUP,
      order: 4,
    },
  ],
  relatedTabs: [
    {
      id: 'project_tasks',
      title: 'وظایف پروژه',
      icon: 'CheckSquareOutlined',
      relationType: 'fk',
      targetModule: 'tasks',
      foreignKey: 'project_id',
    },
    {
      id: 'project_sales_invoices',
      title: 'فاکتورهای فروش',
      icon: 'FileTextOutlined',
      relationType: 'fk',
      targetModule: 'invoices',
      foreignKey: 'project_id',
    },
    {
      id: 'project_purchase_invoices',
      title: 'فاکتورهای خرید',
      icon: 'FileTextOutlined',
      relationType: 'fk',
      targetModule: 'purchase_invoices',
      foreignKey: 'project_id',
    },
  ],
};

