import {
  ModuleDefinition,
  ModuleNature,
  ViewMode,
  FieldType,
  FieldLocation,
  BlockType,
  FieldNature,
  RowCalculationType,
  SummaryCalculationType,
} from '../types';
import { HARD_CODED_UNIT_OPTIONS } from '../utils/unitConversions';
import { getTodayLocalDateValue } from '../utils/defaultValues';

const BLOCKS = {
  baseInfo: {
    id: 'baseInfo',
    titles: { fa: 'اطلاعات فاکتور خرید', en: 'Purchase Invoice Info' },
    icon: 'FileTextOutlined',
    order: 1,
    type: BlockType.FIELD_GROUP,
  },

  legacyInfo: {
    id: 'legacyInfo',
    titles: { fa: 'اطلاعات سیستم قبلی', en: 'Legacy System Info' },
    icon: 'DatabaseOutlined',
    order: 1.1,
    type: BlockType.FIELD_GROUP,
    hideInCreateForm: true,
  },

  invoiceItems: {
    id: 'invoiceItems',
    titles: { fa: 'اقلام فاکتور خرید', en: 'Purchase Invoice Items' },
    icon: 'ShoppingOutlined',
    order: 2,
    type: BlockType.TABLE,
    rowCalculationType: RowCalculationType.INVOICE_ROW,
    tableColumns: [
      {
        key: 'product_id',
        title: 'نام محصول',
        type: FieldType.RELATION,
        width: 300,
        relationConfig: {
          targetModule: 'products',
          targetField: 'name',
          sourceModules: [
            { targetModule: 'products', targetField: 'name' },
            { targetModule: 'billboards', targetField: 'address', tagLabel: 'محیطی', tagColor: 'purple' },
          ],
        },
      },
      { key: 'use_dimensions', title: 'طول×عرض', type: FieldType.CHECKBOX, width: 140 },
      { key: 'quantity', title: 'تعداد/مقدار', type: FieldType.NUMBER, width: 120 },
      {
        key: 'main_unit',
        title: 'واحد اصلی',
        type: FieldType.SELECT,
        width: 110,
        options: HARD_CODED_UNIT_OPTIONS as any,
        dynamicOptionsCategory: 'main_unit',
        readonly: true,
      },
      {
        key: 'sub_quantity',
        title: 'مقدار واحد فرعی',
        type: FieldType.NUMBER,
        width: 130,
        readonly: true,
      },
      {
        key: 'sub_unit',
        title: 'واحد فرعی',
        type: FieldType.SELECT,
        width: 110,
        options: HARD_CODED_UNIT_OPTIONS as any,
        dynamicOptionsCategory: 'main_unit',
        readonly: true,
      },
      { key: 'unit_price', title: 'قیمت واحد', type: FieldType.PRICE, width: 150 },
      { key: 'discount', title: 'تخفیف', type: FieldType.PERCENTAGE_OR_AMOUNT, width: 130, showTotal: true },
      { key: 'vat', title: 'ارزش افزوده', type: FieldType.PERCENTAGE_OR_AMOUNT, width: 130, showTotal: true },
      { key: 'total_price', title: 'جمع کل', type: FieldType.PRICE, width: 160, showTotal: true, readonly: true },
      {
        key: 'source_shelf_id',
        title: 'محل ورود',
        type: FieldType.RELATION,
        width: 150,
        relationConfig: { targetModule: 'shelves', targetField: 'name' },
      },
      { key: 'description', title: 'توضیحات', type: FieldType.LONG_TEXT, width: 170 },
      { key: 'length', title: 'طول', type: FieldType.NUMBER, width: 108 },
      { key: 'width', title: 'عرض', type: FieldType.NUMBER, width: 108 },
    ],
  },

  payments: {
    id: 'payments',
    titles: { fa: 'جدول پرداخت‌ها', en: 'Payments' },
    icon: 'CreditCardOutlined',
    order: 3,
    type: BlockType.TABLE,
    rowCalculationType: RowCalculationType.SIMPLE_MULTIPLY,
    tableColumns: [
      { key: 'attachment', title: 'پیوست', type: FieldType.IMAGE, width: 96 },
      {
        key: 'payment_type',
        title: 'نوع پرداخت',
        type: FieldType.SELECT,
        width: 140,
        options: [
          { label: 'نقد', value: 'cash' },
          { label: 'کارت‌خوان', value: 'pos' },
          { label: 'کارت به کارت', value: 'card' },
          { label: 'انتقال حساب', value: 'transfer' },
          { label: 'چک', value: 'cheque' },
          { label: 'آنلاین', value: 'online' },
          { label: 'تهاتر', value: 'barter' },
          { label: 'اعتباری', value: 'credit' },
        ],
      },
      {
        key: 'cheque_id',
        title: 'چک',
        type: FieldType.RELATION,
        width: 180,
        relationConfig: {
          targetModule: 'cheques',
          targetField: 'serial_no',
          quickCreateFieldKeys: ['serial_no', 'sayad_id', 'issue_date', 'due_date', 'amount', 'payee_name', 'account_holder_name', 'bank_name', 'image_url'],
          quickCreateDefaults: { cheque_type: 'issued', status: 'new' },
        },
      },
      {
        key: 'barter_id',
        title: 'تهاتر',
        type: FieldType.RELATION,
        width: 180,
        relationConfig: {
          targetModule: 'barters',
          targetField: 'name',
        },
      },
      {
        key: 'status',
        title: 'وضعیت',
        type: FieldType.SELECT,
        width: 120,
        options: [
          { label: 'در انتظار', value: 'pending', color: 'orange' },
          { label: 'پرداخت شده', value: 'received', color: 'green' },
          { label: 'برگشت خورده', value: 'returned', color: 'red' },
        ],
      },
      {
        key: 'cheque_status',
        title: 'وضعیت چک',
        type: FieldType.SELECT,
        width: 130,
        options: [
          { label: 'جدید', value: 'new', color: 'blue' },
          { label: 'در بانک', value: 'in_bank', color: 'orange' },
          { label: 'وصول شده', value: 'cleared', color: 'green' },
          { label: 'برگشتی', value: 'bounced', color: 'red' },
          { label: 'عودت شده', value: 'returned', color: 'purple' },
          { label: 'ابطال شده', value: 'canceled', color: 'default' },
        ],
      },
      {
        key: 'source_account',
        title: 'حساب مبدا',
        type: FieldType.RELATION,
        width: 220,
        relationConfig: {
          targetModule: 'bank_accounts',
          targetField: 'bank_name',
          filter: { is_active: true },
           sourceModules: [
             { targetModule: 'bank_accounts', targetField: 'bank_name', filter: { is_active: true }, tagLabel: 'بانک', tagColor: 'cyan' },
             { targetModule: 'cash_boxes', targetField: 'name', filter: { is_active: true }, tagLabel: 'صندوق', tagColor: 'gold' },
             { targetModule: 'petty_funds', targetField: 'name', filter: { is_active: true }, tagLabel: 'تنخواه', tagColor: 'magenta' },
           ],
         },
       },
      { key: 'use_existing_received_cheque', title: 'خرج چک', type: FieldType.CHECKBOX, width: 90 },
      {
        key: 'spent_cheque_id',
        title: 'چک دریافتی',
        type: FieldType.RELATION,
        width: 170,
        relationConfig: { targetModule: 'cheques', targetField: 'serial_no' },
      },
      {
        key: 'responsible_id',
        title: 'مسئول پرداخت',
        type: FieldType.RELATION,
        width: 150,
        relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
      },
      { key: 'date', title: 'تاریخ', type: FieldType.DATE, width: 120 },
      { key: 'amount', title: 'مبلغ', type: FieldType.PRICE, width: 150, showTotal: true },
      { key: 'description', title: 'توضیحات', type: FieldType.LONG_TEXT, width: 220 },
    ],
  },

  summary: {
    id: 'summary',
    titles: { fa: 'خلاصه وضعیت مالی', en: 'Financial Summary' },
    icon: 'CalculatorOutlined',
    order: 4,
    type: BlockType.FIELD_GROUP,
    summaryConfig: {
      calculationType: SummaryCalculationType.INVOICE_FINANCIALS,
      fieldMapping: {
        total: 'total_invoice_amount',
        received: 'total_received_amount',
        remaining: 'remaining_balance',
      },
    },
  },

  process: {
    id: 'process',
    titles: { fa: 'فرآیند اجرا', en: 'Execution Process' },
    icon: 'DeploymentUnitOutlined',
    order: 3.5,
    type: BlockType.FIELD_GROUP,
  },
};

export const purchaseInvoicesConfig: ModuleDefinition = {
  id: 'purchase_invoices',
  titles: { fa: 'فاکتورهای خرید', faSingular: 'فاکتور خرید', en: 'Purchase Invoices' },
  nature: ModuleNature.INVOICE,
  table: 'purchase_invoices',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    { key: 'image_url', labels: { fa: 'تصویر', en: 'Image' }, type: FieldType.IMAGE, location: FieldLocation.HEADER, order: 0, nature: FieldNature.PREDEFINED, isTableColumn: true },
    { key: 'name', labels: { fa: 'عنوان فاکتور', en: 'Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isTableColumn: true },
    { key: 'invoice_date', labels: { fa: 'تاریخ', en: 'Date' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 2, validation: { required: true }, nature: FieldNature.PREDEFINED, defaultValue: getTodayLocalDateValue },
    { key: 'system_code', labels: { fa: 'کد سیستمی', en: 'Code' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 3, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      options: [
        { label: 'ایجاد شده', value: 'created', color: 'blue' },
        { label: 'پیش فاکتور', value: 'proforma', color: 'orange' },
        { label: 'فاکتور نهایی', value: 'final', color: 'green' },
        { label: 'تسویه شده', value: 'settled', color: 'purple' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
        { label: 'تکمیل شده', value: 'completed', color: 'gray' },
      ],
      validation: { required: true },
      defaultValue: 'created',
      isTableColumn: true,
    },

    {
      key: 'supplier_id',
      labels: { fa: 'تامین‌کننده', en: 'Supplier' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 5,
      relationConfig: { targetModule: 'suppliers', targetField: 'business_name' },
      validation: { required: true },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'purchase_source',
      labels: { fa: 'منبع خرید', en: 'Source' },
      type: FieldType.SELECT,
      dynamicOptionsCategory: 'purchase_source',
      location: FieldLocation.HEADER,
      order: 6,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'estimated_invoice_amount',
      labels: { fa: 'مبلغ تقریبی فاکتور', en: 'Estimated Invoice Amount' },
      type: FieldType.PRICE,
      location: FieldLocation.HEADER,
      order: 6.5,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'description',
      labels: { fa: '\u062A\u0648\u0636\u06CC\u062D\u0627\u062A \u0641\u0627\u06A9\u062A\u0648\u0631 \u062E\u0631\u06CC\u062F', en: 'Purchase Invoice Description' },
      type: FieldType.SUPER_LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'baseInfo',
      order: 7,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'legacy_invoice_number',
      labels: { fa: 'شماره فاکتور سیستم قبلی', en: 'Legacy Invoice Number' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'legacyInfo',
      order: 1,
      nature: FieldNature.STANDARD,
      hideInCreateForm: true,
    },
    {
      key: 'legacy_status',
      labels: { fa: 'وضعیت سیستم قبلی', en: 'Legacy Status' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'legacyInfo',
      order: 2,
      nature: FieldNature.STANDARD,
      hideInCreateForm: true,
    },
    {
      key: 'legacy_accounting_status',
      labels: { fa: 'وضعیت حسابداری قبلی', en: 'Legacy Accounting Status' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'legacyInfo',
      order: 3,
      nature: FieldNature.STANDARD,
      hideInCreateForm: true,
    },
    {
      key: 'legacy_source',
      labels: { fa: 'منبع سیستم قبلی', en: 'Legacy Source' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'legacyInfo',
      order: 4,
      nature: FieldNature.STANDARD,
      hideInCreateForm: true,
    },
    {
      key: 'legacy_ready_text',
      labels: { fa: 'متن آماده سیستم قبلی', en: 'Legacy Ready Text' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'legacyInfo',
      order: 5,
      nature: FieldNature.STANDARD,
      hideInCreateForm: true,
    },
    {
      key: 'process_template_id',
      labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 1,
      relationConfig: { targetModule: 'process_templates', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'execution_process_draft',
      labels: { fa: 'فرآیند اجرا', en: 'Execution Process' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'process',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    { key: 'total_invoice_amount', labels: { fa: 'مبلغ کل فاکتور', en: 'Total Amount' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 1, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'total_received_amount', labels: { fa: 'مبلغ پرداخت شده', en: 'Paid Amount' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'remaining_balance', labels: { fa: 'مانده بدهی', en: 'Remaining Balance' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'summary', order: 3, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
  ],
  blocks: [
    BLOCKS.baseInfo,
    BLOCKS.legacyInfo,
    BLOCKS.invoiceItems,
    BLOCKS.payments,
    BLOCKS.process,
    BLOCKS.summary,
  ],
  relatedTabs: [
    {
      id: 'purchase_invoice_journal_entries',
      title: 'اسناد حسابداری',
      icon: 'FileTextOutlined',
      targetModule: 'journal_entries',
      foreignKey: 'source_record_id',
      filters: [{ field: 'source_table', value: 'purchase_invoices' }],
      disableCreate: true,
    },
  ],
};
