import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const recruitmentApplicantsConfig: ModuleDefinition = {
  id: 'recruitment_applicants',
  titles: { fa: 'متقاضیان استخدام', faSingular: 'متقاضی استخدام', en: 'Recruitment Applicants' },
  nature: ModuleNature.STANDARD,
  table: 'recruitment_applicants',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID, ViewMode.KANBAN],
  defaultViewMode: ViewMode.KANBAN,
  relationDisplay: { labelTemplate: '{{system_code}} - {{name}}', searchFields: ['name', 'system_code', 'mobile', 'email', 'position_title'] },
  fields: [
    { key: 'name', labels: { fa: 'نام متقاضی', en: 'Name' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'کد متقاضی', en: 'Applicant No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'new',
      isTableColumn: true,
      options: [
        { label: 'جدید', value: 'new', color: 'blue' },
        { label: 'غربالگری', value: 'screening', color: 'orange' },
        { label: 'مصاحبه', value: 'interview', color: 'purple' },
        { label: 'پذیرفته شده', value: 'accepted', color: 'green' },
        { label: 'رد شده', value: 'rejected', color: 'red' },
        { label: 'استخدام شده', value: 'hired', color: 'cyan' },
        { label: 'بایگانی', value: 'archived', color: 'default' },
      ],
    },
    { key: 'position_title', labels: { fa: 'عنوان شغلی', en: 'Position' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 4, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'mobile', labels: { fa: 'موبایل', en: 'Mobile' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 5, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'department', labels: { fa: 'واحد سازمانی', en: 'Department' }, type: FieldType.SELECT, dynamicOptionsCategory: 'employee_departments', location: FieldLocation.BLOCK, blockId: 'details', order: 1, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'source', labels: { fa: 'منبع جذب', en: 'Source' }, type: FieldType.SELECT, dynamicOptionsCategory: 'recruitment_source', location: FieldLocation.BLOCK, blockId: 'details', order: 2, nature: FieldNature.STANDARD },
    { key: 'email', labels: { fa: 'ایمیل', en: 'Email' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 3, nature: FieldNature.STANDARD },
    { key: 'expected_salary', labels: { fa: 'حقوق مورد انتظار', en: 'Expected Salary' }, type: FieldType.PRICE, location: FieldLocation.BLOCK, blockId: 'details', order: 4, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'interview_at', labels: { fa: 'زمان مصاحبه', en: 'Interview At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'review', order: 1, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'score', labels: { fa: 'امتیاز ارزیابی', en: 'Score' }, type: FieldType.NUMBER, location: FieldLocation.BLOCK, blockId: 'review', order: 2, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'assigned_reviewer_id', labels: { fa: 'مسئول بررسی', en: 'Reviewer' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'review', order: 3, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'related_employee_id', labels: { fa: 'کارمند ایجادشده', en: 'Related Employee' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'review', order: 4, relationConfig: { targetModule: 'employees', targetField: 'full_name' }, nature: FieldNature.STANDARD },
    { key: 'resume_url', labels: { fa: 'رزومه', en: 'Resume' }, type: FieldType.LINK, location: FieldLocation.BLOCK, blockId: 'review', order: 5, nature: FieldNature.STANDARD },
    { key: 'notes', labels: { fa: 'یادداشت ارزیابی', en: 'Notes' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'review', order: 6, nature: FieldNature.STANDARD },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.BLOCK, blockId: 'review', order: 7, nature: FieldNature.STANDARD },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
  ],
  blocks: [
    { id: 'details', titles: { fa: 'اطلاعات متقاضی', en: 'Applicant Info' }, type: BlockType.FIELD_GROUP, order: 1 },
    { id: 'review', titles: { fa: 'ارزیابی و مصاحبه', en: 'Review' }, type: BlockType.FIELD_GROUP, order: 2 },
    { id: 'process', titles: { fa: 'فرآیند جذب', en: 'Recruitment Process' }, type: BlockType.FIELD_GROUP, order: 3 },
  ],
  relatedTabs: [
    {
      id: 'applicant_contracts',
      title: 'قراردادها',
      icon: 'FileTextOutlined',
      targetModule: 'employee_contracts',
      foreignKey: 'applicant_id',
    },
  ],
};
