import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  RowCalculationType,
  ViewMode,
} from "../types";

export const reservationResourcesConfig: ModuleDefinition = {
  id: "reservation_resources",
  titles: {
    fa: "منابع قابل رزرو",
    faSingular: "منبع قابل رزرو",
    en: "Reservation Resources",
  },
  nature: ModuleNature.STANDARD,
  table: "reservation_resources",
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: "{{system_code}} - {{name}}",
    searchFields: ["system_code", "name", "resource_type"],
  },
  fields: [
    {
      key: "name",
      labels: { fa: "نام منبع", en: "Name" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: "system_code",
      labels: { fa: "کد منبع", en: "Code" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "resource_type",
      labels: { fa: "نوع منبع", en: "Type" },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      options: [
        { label: "اتاق یا سوئیت", value: "accommodation" },
        { label: "میز", value: "table" },
        { label: "صندلی یا ایستگاه", value: "seat" },
        { label: "پرسنل", value: "staff" },
        { label: "سالن یا فضا", value: "venue" },
        { label: "خودرو یا تجهیزات", value: "equipment" },
        { label: "سایر", value: "other" },
      ],
    },
    {
      key: "status",
      labels: { fa: "وضعیت", en: "Status" },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: "active",
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      options: [
        { label: "فعال", value: "active", color: "green" },
        { label: "غیرفعال", value: "inactive", color: "default" },
        { label: "در تعمیرات", value: "maintenance", color: "orange" },
      ],
    },
    {
      key: "assignee_id",
      labels: { fa: "مسئول", en: "Assignee" },
      type: FieldType.USER,
      location: FieldLocation.HEADER,
      order: 4.1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "tags",
      labels: { fa: "برچسب‌ها", en: "Tags" },
      type: FieldType.TAGS,
      location: FieldLocation.HEADER,
      order: 4.2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "capacity",
      labels: { fa: "ظرفیت هم‌زمان", en: "Capacity" },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: "availability",
      order: 1,
      defaultValue: 1,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: "preparation_minutes",
      labels: {
        fa: "زمان آماده‌سازی پیش از رزرو (دقیقه)",
        en: "Preparation before",
      },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: "availability",
      order: 2,
      defaultValue: 0,
      nature: FieldNature.STANDARD,
    },
    {
      key: "cleanup_minutes",
      labels: {
        fa: "زمان آماده‌سازی پس از رزرو (دقیقه)",
        en: "Preparation after",
      },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: "availability",
      order: 3,
      defaultValue: 0,
      nature: FieldNature.STANDARD,
    },
    {
      key: "image_url",
      labels: { fa: "تصویر", en: "Image" },
      type: FieldType.IMAGE,
      location: FieldLocation.HEADER,
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: "description",
      labels: { fa: "توضیحات", en: "Description" },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: "details",
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: "created_by",
      labels: { fa: "ایجادکننده", en: "Created by" },
      type: FieldType.USER,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 90,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "created_at",
      labels: { fa: "زمان ایجاد", en: "Created at" },
      type: FieldType.DATETIME,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 91,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "updated_by",
      labels: { fa: "آخرین ویرایشگر", en: "Last editor" },
      type: FieldType.USER,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 92,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "updated_at",
      labels: { fa: "زمان آخرین ویرایش", en: "Updated at" },
      type: FieldType.DATETIME,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 93,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: "availability",
      titles: { fa: "ظرفیت و دسترس‌پذیری", en: "Availability" },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
    {
      id: "details",
      titles: { fa: "جزئیات", en: "Details" },
      type: BlockType.FIELD_GROUP,
      order: 2,
    },
  ],
};

export const reservationsConfig: ModuleDefinition = {
  id: "reservations",
  titles: { fa: "رزرواسیون‌ها", faSingular: "رزرو", en: "Reservations" },
  nature: ModuleNature.STANDARD,
  table: "reservations",
  supportedViewModes: [ViewMode.CALENDAR, ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.CALENDAR,
  calendar: { summaryFieldKeys: ["customer_id", "status"] },
  relationDisplay: {
    labelTemplate: "{{system_code}} - {{name}}",
    searchFields: ["system_code", "name"],
  },
  fields: [
    {
      key: "name",
      labels: { fa: "عنوان رزرو", en: "Reservation title" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      validation: { required: true },
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.PREDEFINED,
    },
    {
      key: "system_code",
      labels: { fa: "کد رزرو", en: "Reservation code" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "status",
      labels: { fa: "وضعیت رزرو", en: "Status" },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: "pending",
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      options: [
        { label: "پیش‌نویس", value: "draft", color: "default" },
        { label: "در انتظار تایید", value: "pending", color: "orange" },
        { label: "تاییدشده", value: "confirmed", color: "blue" },
        { label: "انجام‌شده", value: "completed", color: "green" },
        { label: "لغوشده", value: "canceled", color: "red" },
        { label: "عدم حضور", value: "no_show", color: "purple" },
      ],
    },
    {
      key: "customer_id",
      labels: { fa: "مشتری", en: "Customer" },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 4,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: "customers", targetField: "full_name" },
    },
    {
      key: "assignee_id",
      labels: { fa: "مسئول رزرو", en: "Assignee" },
      type: FieldType.USER,
      location: FieldLocation.HEADER,
      order: 4.1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "tags",
      labels: { fa: "برچسب‌ها", en: "Tags" },
      type: FieldType.TAGS,
      location: FieldLocation.HEADER,
      order: 4.2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "start_at",
      labels: { fa: "زمان شروع", en: "Start" },
      type: FieldType.DATETIME,
      location: FieldLocation.HEADER,
      order: 5,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "end_at",
      labels: { fa: "زمان پایان", en: "End" },
      type: FieldType.DATETIME,
      location: FieldLocation.HEADER,
      order: 6,
      validation: { required: true },
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "sales_invoice_id",
      labels: { fa: "فاکتور بیعانه/رزرو", en: "Deposit invoice" },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: "financial",
      order: 1,
      nature: FieldNature.STANDARD,
      relationConfig: { targetModule: "invoices", targetField: "name" },
    },
    {
      key: "deposit_amount",
      labels: { fa: "مبلغ بیعانه", en: "Deposit amount" },
      type: FieldType.PRICE,
      location: FieldLocation.BLOCK,
      blockId: "financial",
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: "notes",
      labels: { fa: "یادداشت", en: "Notes" },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: "details",
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: "process_template_id",
      labels: { fa: "الگوی فرآیند رزرو", en: "Reservation process template" },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: "process",
      order: 1,
      relationConfig: {
        targetModule: "process_templates",
        targetField: "name",
      },
      nature: FieldNature.STANDARD,
    },
    {
      key: "execution_process_draft",
      labels: { fa: "فرآیند رزرو", en: "Reservation process" },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: "process",
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: "created_by",
      labels: { fa: "ایجادکننده", en: "Created by" },
      type: FieldType.USER,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 90,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "created_at",
      labels: { fa: "زمان ایجاد", en: "Created at" },
      type: FieldType.DATETIME,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 91,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "updated_by",
      labels: { fa: "آخرین ویرایشگر", en: "Last editor" },
      type: FieldType.USER,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 92,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: "updated_at",
      labels: { fa: "زمان آخرین ویرایش", en: "Updated at" },
      type: FieldType.DATETIME,
      location: FieldLocation.SYSTEM_FOOTER,
      order: 93,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: "reservationItems",
      titles: {
        fa: "منابع و خدمات رزرو",
        en: "Reserved resources and services",
      },
      type: BlockType.TABLE,
      order: 1,
      rowCalculationType: RowCalculationType.SIMPLE_MULTIPLY,
      tableColumns: [
        {
          key: "resource_id",
          title: "منبع قابل رزرو",
          type: FieldType.RELATION,
          width: 220,
          relationConfig: {
            targetModule: "reservation_resources",
            targetField: "name",
          },
        },
        {
          key: "product_id",
          title: "خدمت یا کالا",
          type: FieldType.RELATION,
          width: 220,
          relationConfig: { targetModule: "products", targetField: "name" },
        },
        { key: "quantity", title: "تعداد", type: FieldType.NUMBER, width: 100 },
        {
          key: "unit_price",
          title: "مبلغ واحد",
          type: FieldType.PRICE,
          width: 150,
        },
        { key: "total_price", title: "جمع", type: FieldType.PRICE, width: 150 },
        {
          key: "description",
          title: "توضیحات",
          type: FieldType.LONG_TEXT,
          width: 220,
        },
      ],
    },
    {
      id: "financial",
      titles: { fa: "مالی و بیعانه", en: "Financial" },
      type: BlockType.FIELD_GROUP,
      order: 2,
    },
    {
      id: "details",
      titles: { fa: "جزئیات", en: "Details" },
      type: BlockType.FIELD_GROUP,
      order: 3,
    },
    {
      id: "process",
      titles: { fa: "فرآیند رزرو", en: "Reservation process" },
      type: BlockType.FIELD_GROUP,
      order: 4,
    },
  ],
  relatedTabs: [
    {
      id: "reservation_invoice",
      title: "فاکتور فروش",
      icon: "FileTextOutlined",
      relationType: "fk",
      targetModule: "invoices",
      foreignKey: "reservation_id",
    },
  ],
  actionButtons: [
    {
      id: "create_reservation_invoice",
      label: "ایجاد فاکتور و ثبت بیعانه",
      placement: "header",
      variant: "primary",
    },
    {
      id: "reservation_settings",
      label: "تنظیمات رزرواسیون",
      placement: "header",
      variant: "default",
    },
  ],
};
