import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

const announcementKindOptions = [
  { value: 'popup', label: 'پاپ‌آپ' },
  { value: 'header', label: 'نوار بالای هدر' },
];

const audienceScopeOptions = [
  { value: 'all', label: 'همه کاربران' },
  { value: 'demo_only', label: 'فقط کاربران دمو' },
  { value: 'non_demo_only', label: 'فقط کاربران غیر دمو' },
];

const mediaTypeOptions = [
  { value: 'image', label: 'تصویر' },
  { value: 'video', label: 'ویدیو' },
];

export const saasUserAnnouncementsConfig: ModuleDefinition = {
  id: 'saas_user_announcements',
  titles: { fa: 'اعلانات کاربران', faSingular: 'اعلان کاربر', en: 'User Announcements' },
  nature: ModuleNature.CRM,
  table: 'saas_user_announcements',
  systemManaged: true,
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: '{{title}}',
    searchFields: ['title', 'body', 'kind'],
  },
  fields: [
    {
      key: 'title',
      labels: { fa: 'عنوان داخلی اعلان', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'kind',
      labels: { fa: 'نوع اعلان', en: 'Kind' },
      type: FieldType.SELECT,
      options: announcementKindOptions,
      location: FieldLocation.HEADER,
      order: 2,
      defaultValue: 'header',
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_active',
      labels: { fa: 'فعال', en: 'Active' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: true,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'priority',
      labels: { fa: 'اولویت نمایش', en: 'Priority' },
      type: FieldType.NUMBER,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 100,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'body',
      labels: { fa: 'متن اعلان', en: 'Body' },
      type: FieldType.SUPER_LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'content',
      order: 1,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'allow_dismiss',
      labels: { fa: 'گزینه «دیگر نشان نده» فعال باشد', en: 'Allow Dismiss' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'content',
      order: 2,
      defaultValue: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'show_on_public_site',
      labels: { fa: 'نمایش در صفحه عمومی سایت', en: 'Show On Public Site' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'surfaces',
      order: 1,
      defaultValue: false,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'show_on_user_panel',
      labels: { fa: 'نمایش در پنل کاربران', en: 'Show On User Panel' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'surfaces',
      order: 2,
      defaultValue: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'show_on_login',
      labels: { fa: 'نمایش در صفحه لاگین', en: 'Show On Login' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'surfaces',
      order: 3,
      defaultValue: false,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'starts_at',
      labels: { fa: 'شروع نمایش', en: 'Starts At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'schedule',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'ends_at',
      labels: { fa: 'پایان نمایش', en: 'Ends At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'schedule',
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'audience_scope',
      labels: { fa: 'مخاطب دمو', en: 'Audience Scope' },
      type: FieldType.SELECT,
      options: audienceScopeOptions,
      location: FieldLocation.BLOCK,
      blockId: 'targeting',
      order: 1,
      defaultValue: 'all',
      nature: FieldNature.STANDARD,
    },
    {
      key: 'target_org_ids',
      labels: { fa: 'فقط این سازمان‌ها', en: 'Target Organizations' },
      type: FieldType.MULTI_RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'targeting',
      order: 2,
      multiRelationConfig: {
        targetModule: 'saas_orgs',
        targetField: 'org_name',
        filter: { source_kind: 'org' },
      },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'target_user_ids',
      labels: { fa: 'فقط این کاربران', en: 'Target Users' },
      type: FieldType.MULTI_RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'targeting',
      order: 3,
      multiRelationConfig: {
        targetModule: 'saas_users',
        targetField: 'full_name',
      },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'target_host_patterns',
      labels: { fa: 'الگوی هاست (مثال: *.tazesystem.ir)', en: 'Host Patterns' },
      type: FieldType.TAGS,
      location: FieldLocation.BLOCK,
      blockId: 'targeting',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'target_path_patterns',
      labels: { fa: 'الگوی مسیر (مثال: /pricing*)', en: 'Path Patterns' },
      type: FieldType.TAGS,
      location: FieldLocation.BLOCK,
      blockId: 'targeting',
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'conditions_all',
      labels: { fa: 'شرط‌های پیشرفته (همه برقرار باشند)', en: 'Conditions All' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'advanced',
      order: 1,
      nature: FieldNature.STANDARD,
      defaultValue: [],
    },
    {
      key: 'conditions_any',
      labels: { fa: 'شرط‌های پیشرفته (حداقل یکی برقرار باشد)', en: 'Conditions Any' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      blockId: 'advanced',
      order: 2,
      nature: FieldNature.STANDARD,
      defaultValue: [],
    },
    {
      key: 'created_at',
      labels: { fa: 'زمان ایجاد', en: 'Created At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'system',
      order: 1,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
    {
      key: 'updated_at',
      labels: { fa: 'آخرین بروزرسانی', en: 'Updated At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'system',
      order: 2,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: 'content',
      titles: { fa: 'محتوا', en: 'Content' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'NotificationOutlined',
    },
    {
      id: 'media_items',
      titles: { fa: 'رسانه‌های پاپ‌آپ (تصویر/ویدیو)', en: 'Popup Media' },
      type: BlockType.TABLE,
      order: 2,
      visibleIf: {
        field: 'kind',
        operator: 'eq',
        value: 'popup',
      },
      tableColumns: [
        {
          key: 'media_type',
          title: 'نوع',
          type: FieldType.SELECT,
          width: 120,
          defaultValue: 'image',
          options: mediaTypeOptions,
        },
        {
          key: 'attachment',
          title: 'تصویر',
          type: FieldType.IMAGE,
          width: 120,
        },
        {
          key: 'video_url',
          title: 'لینک ویدیو',
          type: FieldType.LINK,
          width: 240,
        },
        {
          key: 'caption',
          title: 'توضیح',
          type: FieldType.TEXT,
          width: 220,
        },
        {
          key: 'sort_order',
          title: 'ترتیب',
          type: FieldType.NUMBER,
          width: 110,
        },
      ],
    },
    {
      id: 'surfaces',
      titles: { fa: 'محل نمایش', en: 'Surfaces' },
      type: BlockType.FIELD_GROUP,
      order: 3,
      icon: 'MonitorOutlined',
    },
    {
      id: 'schedule',
      titles: { fa: 'زمان‌بندی', en: 'Schedule' },
      type: BlockType.FIELD_GROUP,
      order: 4,
      icon: 'CalendarOutlined',
    },
    {
      id: 'targeting',
      titles: { fa: 'شرط‌های هدف‌گذاری', en: 'Targeting' },
      type: BlockType.FIELD_GROUP,
      order: 5,
      icon: 'FilterOutlined',
    },
    {
      id: 'advanced',
      titles: { fa: 'شرط پیشرفته (اختیاری)', en: 'Advanced Conditions' },
      type: BlockType.FIELD_GROUP,
      order: 6,
      icon: 'CodeOutlined',
    },
    {
      id: 'system',
      titles: { fa: 'سیستمی', en: 'System' },
      type: BlockType.FIELD_GROUP,
      order: 7,
      icon: 'DatabaseOutlined',
    },
  ],
  relatedTabs: [],
};
