import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';
import { saasDemoRequestRecordActions, saveSaasDemoRequest } from '../utils/saasAdminModules';

const statusOptions = [
  { value: 'draft', label: 'draft' },
  { value: 'started', label: 'در حال پردازش' },
  { value: 'provisioned', label: 'پروویژن‌شده' },
  { value: 'failed', label: 'ناموفق' },
  { value: 'needs_admin_review', label: 'نیاز به بررسی' },
];

export const saasDemoRequestsConfig: ModuleDefinition = {
  id: 'saas_demo_requests',
  titles: { fa: 'درخواست‌های دمو', faSingular: 'درخواست دمو', en: 'SaaS Demo Requests' },
  nature: ModuleNature.CRM,
  table: 'saas_onboarding_requests',
  systemManaged: true,
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  // ویرایش inline از طریق __saas_admin.edit_requests کنترل می‌شود (ModuleShow.tsx)
  formAdapter: {
    save: saveSaasDemoRequest,
  },
  recordActions: saasDemoRequestRecordActions,
  fields: [
    {
      key: 'full_name',
      labels: { fa: 'نام متقاضی', en: 'Full Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'mobile',
      labels: { fa: 'موبایل', en: 'Mobile' },
      type: FieldType.PHONE,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'organization_name',
      labels: { fa: 'نام سازمان', en: 'Organization Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'requested_slug',
      labels: { fa: 'Slug درخواستی', en: 'Requested Slug' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      options: statusOptions,
      defaultValue: 'draft',
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_demo_request',
      labels: { fa: 'نسخه دمو', en: 'Demo Request' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.HEADER,
      order: 6,
      isTableColumn: true,
      defaultValue: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'email',
      labels: { fa: 'ایمیل', en: 'Email' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'applicant',
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'industry',
      labels: { fa: 'حوزه کاری', en: 'Industry' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'applicant',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'employee_count_band',
      labels: { fa: 'بازه تعداد کاربران', en: 'Employee Count Band' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'applicant',
      order: 3,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'discovery_source',
      labels: { fa: 'منبع آشنایی', en: 'Discovery Source' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'applicant',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'business_name',
      labels: { fa: 'نام تجاری', en: 'Business Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'applicant',
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'یادداشت', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'status_info',
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'provision_attempts',
      labels: { fa: 'تعداد تلاش', en: 'Provision Attempts' },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: 'status_info',
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'failure_code',
      labels: { fa: 'کد خطا', en: 'Failure Code' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'status_info',
      order: 3,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'failure_message',
      labels: { fa: 'پیام خطا', en: 'Failure Message' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'status_info',
      order: 4,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'org_id',
      labels: { fa: 'شناسه سازمان', en: 'Org Id' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'status_info',
      order: 5,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'created_at',
      labels: { fa: 'زمان ثبت', en: 'Created At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'system',
      order: 1,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'updated_at',
      labels: { fa: 'آخرین بروزرسانی', en: 'Updated At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'system',
      order: 2,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: 'applicant',
      titles: { fa: 'اطلاعات متقاضی', en: 'Applicant' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'UserOutlined',
    },
    {
      id: 'status_info',
      titles: { fa: 'وضعیت درخواست', en: 'Request Status' },
      type: BlockType.FIELD_GROUP,
      order: 2,
      icon: 'InfoCircleOutlined',
    },
    {
      id: 'system',
      titles: { fa: 'اطلاعات سیستمی', en: 'System' },
      type: BlockType.FIELD_GROUP,
      order: 3,
      icon: 'DatabaseOutlined',
    },
  ],
  relatedTabs: [],
};
