import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';
import { saasOrgRecordActions, saveSaasOrgRecord } from '../utils/saasAdminModules';

const statusOptions = [
  { value: 'draft', label: 'draft' },
  { value: 'trial', label: 'trial' },
  { value: 'active', label: 'فعال' },
  { value: 'suspended', label: 'تعلیق‌شده' },
  { value: 'failed', label: 'ناموفق' },
  { value: 'needs_admin_review', label: 'نیاز به بررسی' },
];

const provisionStateOptions = [
  { value: 'provisioned', label: 'ایجاد شده' },
  { value: 'request_pending', label: 'درخواست دمو / ایجاد نشده' },
];

const sourceKindOptions = [
  { value: 'org', label: 'سازمان' },
  { value: 'request', label: 'درخواست دمو' },
];


export const saasOrgsConfig: ModuleDefinition = {
  id: 'saas_orgs',
  titles: { fa: 'سازمان‌های SaaS', faSingular: 'سازمان SaaS', en: 'SaaS Orgs' },
  nature: ModuleNature.CRM,
  table: 'saas_admin_org_candidates_view',
  systemManaged: true,
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  // ویرایش inline از طریق __saas_admin.edit_orgs کنترل می‌شود (ModuleShow.tsx)
  formAdapter: {
    save: saveSaasOrgRecord,
  },
  recordActions: saasOrgRecordActions,
  fields: [
    {
      key: 'org_name',
      labels: { fa: 'نام سازمان', en: 'Organization Name' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'slug',
      labels: { fa: 'Slug', en: 'Slug' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      options: statusOptions,
      defaultValue: 'trial',
      nature: FieldNature.STANDARD,
    },
    {
      key: 'provision_state',
      labels: { fa: 'وضعیت ایجاد', en: 'Provision State' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      options: provisionStateOptions,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'source_kind',
      labels: { fa: 'منبع', en: 'Source Kind' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 5,
      options: sourceKindOptions,
      defaultValue: 'org',
      readonly: true,
      hideInCreateForm: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'plan_code',
      labels: { fa: 'کد پلن', en: 'Plan Code' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'subscription',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'trial_ends_at',
      labels: { fa: 'پایان trial', en: 'Trial Ends At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'subscription',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_demo',
      labels: { fa: 'دمو', en: 'Is Demo' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'subscription',
      order: 3,
      isTableColumn: true,
      defaultValue: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'is_readonly',
      labels: { fa: 'فقط خواندن', en: 'Readonly' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: 'subscription',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'owner_name',
      labels: { fa: 'نام مالک / متقاضی', en: 'Owner Name' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'contact',
      order: 1,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'owner_email',
      labels: { fa: 'ایمیل مالک / متقاضی', en: 'Owner Email' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'contact',
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'primary_contact_mobile',
      labels: { fa: 'موبایل', en: 'Mobile' },
      type: FieldType.PHONE,
      location: FieldLocation.BLOCK,
      blockId: 'contact',
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'industry',
      labels: { fa: 'حوزه کاری', en: 'Industry' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'contact',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'employee_count_band',
      labels: { fa: 'بازه تعداد کاربران', en: 'Employee Count Band' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'contact',
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'discovery_source',
      labels: { fa: 'منبع آشنایی', en: 'Discovery Source' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'contact',
      order: 6,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'resolved_host',
      labels: { fa: 'آدرس ساب‌دامین', en: 'Subdomain Host' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'system',
      order: 0,
      readonly: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'provisioning_source',
      labels: { fa: 'منبع ایجاد', en: 'Provisioning Source' },
      type: FieldType.TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'system',
      order: 1,
      nature: FieldNature.SYSTEM,
      defaultValue: 'manual_admin',
    },
    {
      key: 'provisioned_at',
      labels: { fa: 'زمان ثبت', en: 'Created At' },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: 'system',
      order: 2,
      readonly: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: 'subscription',
      titles: { fa: 'اشتراک و وضعیت', en: 'Subscription' },
      type: BlockType.FIELD_GROUP,
      order: 1,
      icon: 'RocketOutlined',
    },
    {
      id: 'contact',
      titles: { fa: 'اطلاعات تماس و متقاضی', en: 'Contact' },
      type: BlockType.FIELD_GROUP,
      order: 2,
      icon: 'UserOutlined',
    },
    {
      id: 'system',
      titles: { fa: 'اطلاعات سیستمی', en: 'System' },
      type: BlockType.FIELD_GROUP,
      order: 4,
      icon: 'DatabaseOutlined',
    },
  ],
  relatedTabs: [],
};
