import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';
import { getTodayLocalDateValue } from '../utils/defaultValues';

const RELATED_MODULE_OPTIONS = [
  { label: 'فعالیت ها', value: 'tasks' },
  { label: 'مشتریان', value: 'customers' },
  { label: 'تامین‌کنندگان', value: 'suppliers' },
  { label: 'فاکتور فروش', value: 'invoices' },
  { label: 'فاکتور خرید', value: 'purchase_invoices' },
  { label: 'عملیات نقد و بانک', value: 'cash_bank_operations' },
  { label: 'تردد کالاها', value: 'stock_transfers' },
  { label: 'فرم‌های تحویل', value: 'delivery_forms' },
  { label: 'پروژه‌ها', value: 'projects' },
  { label: 'کارکنان', value: 'employees' },
];

export const secretariatDocumentsConfig: ModuleDefinition = {
  id: 'secretariat_documents',
  titles: { fa: 'دبیرخانه', faSingular: 'نامه', en: 'Secretariat Documents' },
  nature: ModuleNature.STANDARD,
  table: 'secretariat_documents',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: '{{system_code}} - {{name}}',
    searchFields: ['name', 'system_code', 'external_number', 'indicator_number'],
  },
  fields: [
    { key: 'image_url', labels: { fa: 'تصویر / فایل اصلی', en: 'Main Image / File' }, type: FieldType.IMAGE, location: FieldLocation.HEADER, order: 0, nature: FieldNature.PREDEFINED, isTableColumn: true },
    { key: 'name', labels: { fa: 'موضوع', en: 'Subject' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, validation: { required: true }, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'شماره داخلی', en: 'Internal No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    {
      key: 'document_type',
      labels: { fa: 'نوع سند', en: 'Document Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'letter',
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
      options: [
        { label: 'نامه', value: 'letter' },
        { label: 'نامه وارده', value: 'incoming_letter' },
        { label: 'نامه صادره', value: 'outgoing_letter' },
        { label: 'ابلاغ داخلی', value: 'internal_notice' },
        { label: 'درخواست داخلی', value: 'internal_request' },
        { label: 'دستور اداری', value: 'directive' },
        { label: 'صورتجلسه', value: 'minutes' },
      ],
    },
    {
      key: 'direction',
      labels: { fa: 'جهت', en: 'Direction' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 'internal',
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
      options: [
        { label: 'وارده', value: 'incoming' },
        { label: 'صادره', value: 'outgoing' },
        { label: 'داخلی', value: 'internal' },
      ],
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 5,
      defaultValue: 'draft',
      validation: { required: true },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'ثبت شده', value: 'registered', color: 'blue' },
        { label: 'در بررسی', value: 'in_review', color: 'orange' },
        { label: 'ارجاع شده', value: 'referred', color: 'purple' },
        { label: 'پاسخ داده شده', value: 'answered', color: 'green' },
        { label: 'بایگانی', value: 'archived', color: 'gray' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
      ],
    },
    { key: 'document_date', labels: { fa: 'تاریخ نامه', en: 'Document Date' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 6, defaultValue: getTodayLocalDateValue, validation: { required: true }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'sender_profile_id', labels: { fa: 'از طرف', en: 'From' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 7, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'sender_manual', labels: { fa: 'از طرف (دستی)', en: 'From (Manual)' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 7.1, nature: FieldNature.STANDARD },
    { key: 'recipient_profile_id', labels: { fa: 'خطاب به', en: 'To' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 8, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'recipient_manual', labels: { fa: 'خطاب به (دستی)', en: 'To (Manual)' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 8.1, nature: FieldNature.STANDARD },
    { key: 'assignee_id', labels: { fa: 'مسئول پیگیری', en: 'Assignee' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 9, relationConfig: { targetModule: 'profiles', targetField: 'full_name' }, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'priority',
      labels: { fa: 'اولویت', en: 'Priority' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'tracking',
      order: 1,
      defaultValue: 'normal',
      nature: FieldNature.STANDARD,
      options: [
        { label: 'پایین', value: 'low' },
        { label: 'عادی', value: 'normal' },
        { label: 'بالا', value: 'high' },
        { label: 'فوری', value: 'urgent' },
      ],
    },
    {
      key: 'confidentiality',
      labels: { fa: 'سطح محرمانگی', en: 'Confidentiality' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'tracking',
      order: 2,
      defaultValue: 'normal',
      nature: FieldNature.STANDARD,
      options: [
        { label: 'عادی', value: 'normal' },
        { label: 'محرمانه', value: 'confidential' },
        { label: 'سری', value: 'secret' },
      ],
    },
    { key: 'external_number', labels: { fa: 'شماره طرف مقابل', en: 'External No.' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'tracking', order: 3, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'indicator_number', labels: { fa: 'اندیکاتور', en: 'Indicator No.' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'tracking', order: 4, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'registered_at', labels: { fa: 'زمان ثبت', en: 'Registered At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'tracking', order: 5, nature: FieldNature.STANDARD },
    { key: 'due_at', labels: { fa: 'مهلت پاسخ/پیگیری', en: 'Due At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'tracking', order: 6, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'customer_id', labels: { fa: 'مشتری مرتبط', en: 'Customer' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 1, relationConfig: { targetModule: 'customers', targetField: 'full_name' }, nature: FieldNature.STANDARD },
    { key: 'supplier_id', labels: { fa: 'تامین‌کننده مرتبط', en: 'Supplier' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 2, relationConfig: { targetModule: 'suppliers', targetField: 'business_name' }, nature: FieldNature.STANDARD },
    { key: 'related_document_id', labels: { fa: 'نامه مرتبط', en: 'Related Document' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 3, relationConfig: { targetModule: 'secretariat_documents', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'related_module_id', labels: { fa: 'مرتبط با بخش', en: 'Related Module' }, type: FieldType.SELECT, location: FieldLocation.BLOCK, blockId: 'relations', order: 4, options: RELATED_MODULE_OPTIONS, nature: FieldNature.STANDARD },
    { key: 'related_record_id', labels: { fa: 'رکورد مرتبط', en: 'Related Record' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 5, relationConfig: { targetModule: '', dependsOn: 'related_module_id' }, nature: FieldNature.STANDARD },
    { key: 'body', labels: { fa: 'متن نامه', en: 'Body' }, type: FieldType.SUPER_LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'content', order: 1, nature: FieldNature.STANDARD },
    { key: 'summary', labels: { fa: 'خلاصه و نتیجه', en: 'Summary' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'content', order: 2, nature: FieldNature.STANDARD },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 3, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
  ],
  blocks: [
    { id: 'tracking', titles: { fa: 'ثبت و پیگیری', en: 'Tracking' }, type: BlockType.FIELD_GROUP, order: 1, icon: 'ProfileOutlined' },
    { id: 'relations', titles: { fa: 'ارتباطات', en: 'Relations' }, type: BlockType.FIELD_GROUP, order: 2, icon: 'LinkOutlined' },
    { id: 'content', titles: { fa: 'متن و یادداشت‌ها', en: 'Content' }, type: BlockType.FIELD_GROUP, order: 3, icon: 'FileTextOutlined' },
    { id: 'process', titles: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: BlockType.FIELD_GROUP, order: 4, icon: 'DeploymentUnitOutlined' },
  ],
  relatedTabs: [],
};
