import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

const RELATED_MODULE_OPTIONS = [
  { label: 'مشتریان', value: 'customers' },
  { label: 'بازاریابی', value: 'marketing_leads' },
  { label: 'تامین‌کنندگان', value: 'suppliers' },
  { label: 'کارکنان', value: 'employees' },
];

export const smsDeliveryReportsConfig: ModuleDefinition = {
  id: 'sms_delivery_reports',
  titles: { fa: 'پیامک‌ها', faSingular: 'پیامک', en: 'SMS Messages' },
  nature: ModuleNature.STANDARD,
  table: 'sms_delivery_reports',
  systemManaged: true,
  disableCreate: true,
  disableDetailView: true,
  hideFullRecordAction: true,
  listPreviewMode: 'modal',
  quickPreview: {
    fieldKeys: [
      'title',
      'direction',
      'status',
      'sender',
      'recipient',
      'message_text',
      'message_at',
      'module_id',
      'record_id',
      'assignee_id',
      'operator_report',
      'related_task_id',
      'tags',
    ],
    editableFields: ['tags', 'operator_report', 'module_id', 'record_id', 'assignee_id', 'related_task_id'],
    relatedModuleOptions: ['customers', 'marketing_leads', 'suppliers', 'employees'],
  },
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'title',
      labels: { fa: 'عنوان', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'direction',
      labels: { fa: 'جهت', en: 'Direction' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      options: [
        { label: 'دریافتی', value: 'inbound', color: 'blue' },
        { label: 'ارسالی', value: 'outbound', color: 'green' },
      ],
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'نتیجه ارسال', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      options: [
        { label: 'در انتظار', value: 'pending', color: 'orange' },
        { label: 'ارسال شده', value: 'sent', color: 'green' },
        { label: 'ناموفق', value: 'failed', color: 'red' },
        { label: 'رد شده', value: 'skipped', color: 'gray' },
        { label: 'دریافت شده', value: 'received', color: 'blue' },
        { label: 'پردازش شده', value: 'processed', color: 'cyan' },
        { label: 'نادیده گرفته شده', value: 'ignored', color: 'gray' },
      ],
      nature: FieldNature.SYSTEM,
    },
    { key: 'sender', labels: { fa: 'فرستنده', en: 'Sender' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 4, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'recipient', labels: { fa: 'گیرنده', en: 'Recipient' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 5, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'message_text', labels: { fa: 'متن پیامک', en: 'SMS Text' }, type: FieldType.LONG_TEXT, location: FieldLocation.HEADER, order: 6, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'message_at', labels: { fa: 'زمان پیام', en: 'Message At' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 7, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'provider', labels: { fa: 'سرویس‌دهنده', en: 'Provider' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 1, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'provider_message_id', labels: { fa: 'شناسه پیام سرویس‌دهنده', en: 'Provider Message ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 2, nature: FieldNature.SYSTEM },
    { key: 'error_message', labels: { fa: 'پیام خطا', en: 'Error Message' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 3, isTableColumn: true, nature: FieldNature.SYSTEM },
    {
      key: 'module_id',
      labels: { fa: 'ماژول مخاطب', en: 'Related Module' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'details',
      order: 4,
      isTableColumn: true,
      options: RELATED_MODULE_OPTIONS,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'record_id',
      labels: { fa: 'مخاطب مرتبط', en: 'Related Record' },
      type: FieldType.RELATION,
      relationConfig: { targetModule: '', dependsOn: 'module_id' },
      location: FieldLocation.BLOCK,
      blockId: 'details',
      order: 5,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    { key: 'customer_id', labels: { fa: 'مشتری', en: 'Customer' }, type: FieldType.RELATION, relationConfig: { targetModule: 'customers', targetField: 'business_name' }, location: FieldLocation.BLOCK, blockId: 'details', order: 6, nature: FieldNature.SYSTEM },
    { key: 'assignee_id', labels: { fa: 'مسئول', en: 'Assignee' }, type: FieldType.USER, location: FieldLocation.BLOCK, blockId: 'details', order: 6.2, isTableColumn: true, nature: FieldNature.STANDARD },
    { key: 'operator_report', labels: { fa: 'گزارش اپراتور', en: 'Operator Report' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 6.4, isTableColumn: true, nature: FieldNature.STANDARD },
    { key: 'related_task_id', labels: { fa: 'وظیفه مرتبط', en: 'Related Task' }, type: FieldType.RELATION, relationConfig: { targetModule: 'tasks', targetField: 'name' }, location: FieldLocation.BLOCK, blockId: 'details', order: 6.6, nature: FieldNature.STANDARD },
    { key: 'metadata', labels: { fa: 'جزئیات سیستمی', en: 'Metadata' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'details', order: 7, nature: FieldNature.SYSTEM },
    { key: 'created_at', labels: { fa: 'زمان ایجاد', en: 'Created At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'details', order: 8, nature: FieldNature.SYSTEM },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 6, isTableColumn: true, nature: FieldNature.STANDARD },
  ],
  blocks: [
    {
      id: 'details',
      titles: { fa: 'جزئیات گزارش پیامک', en: 'SMS Report Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
};
