import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

export const smsDeliveryReportsConfig: ModuleDefinition = {
  id: 'sms_delivery_reports',
  titles: { fa: 'گزارشات ارسال پیامک', faSingular: 'گزارش ارسال پیامک', en: 'SMS Delivery Reports' },
  nature: ModuleNature.STANDARD,
  table: 'sms_delivery_reports',
  systemManaged: true,
  disableCreate: true,
  disableDetailView: true,
  hideFullRecordAction: true,
  listPreviewMode: 'modal',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'title',
      labels: { fa: 'عنوان', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'نتیجه ارسال', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      options: [
        { label: 'در انتظار', value: 'pending', color: 'orange' },
        { label: 'ارسال شده', value: 'sent', color: 'green' },
        { label: 'ناموفق', value: 'failed', color: 'red' },
        { label: 'رد شده', value: 'skipped', color: 'gray' },
      ],
      nature: FieldNature.SYSTEM,
    },
    { key: 'recipient', labels: { fa: 'گیرنده', en: 'Recipient' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 3, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'message_text', labels: { fa: 'متن پیامک', en: 'SMS Text' }, type: FieldType.LONG_TEXT, location: FieldLocation.HEADER, order: 4, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'sent_at', labels: { fa: 'زمان ارسال', en: 'Sent At' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 5, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'provider', labels: { fa: 'سرویس‌دهنده', en: 'Provider' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 1, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'provider_message_id', labels: { fa: 'شناسه پیام سرویس‌دهنده', en: 'Provider Message ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 2, nature: FieldNature.SYSTEM },
    { key: 'error_message', labels: { fa: 'پیام خطا', en: 'Error Message' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 3, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'module_id', labels: { fa: 'ماژول مرتبط', en: 'Module' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 4, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'record_id', labels: { fa: 'شناسه رکورد', en: 'Record ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 5, nature: FieldNature.SYSTEM },
    { key: 'customer_id', labels: { fa: 'مشتری', en: 'Customer' }, type: FieldType.RELATION, relationConfig: { targetModule: 'customers', targetField: 'business_name' }, location: FieldLocation.BLOCK, blockId: 'details', order: 6, nature: FieldNature.SYSTEM },
    { key: 'metadata', labels: { fa: 'جزئیات سیستمی', en: 'Metadata' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'details', order: 7, nature: FieldNature.SYSTEM },
    { key: 'created_at', labels: { fa: 'زمان ایجاد', en: 'Created At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'details', order: 8, nature: FieldNature.SYSTEM },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 6, isTableColumn: true, nature: FieldNature.STANDARD },
  ],
  blocks: [
    {
      id: 'details',
      titles: { fa: 'جزئیات گزارش پیامک', en: 'SMS Report Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
};
