import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';
import { getTodayLocalDateValue } from '../utils/defaultValues';

const RELATED_MODULE_OPTIONS = [
  { label: 'فاکتور فروش', value: 'invoices' },
  { label: 'فاکتور خرید', value: 'purchase_invoices' },
  { label: 'سفارش تولید', value: 'production_orders' },
  { label: 'فرم‌های تحویل', value: 'delivery_forms' },
  { label: 'دبیرخانه', value: 'secretariat_documents' },
  { label: 'پروژه‌ها', value: 'projects' },
  { label: 'فعالیت ها', value: 'tasks' },
];

export const stockTransfersConfig: ModuleDefinition = {
  id: 'stock_transfers',
  titles: { fa: 'تردد کالاها و حواله‌ها', faSingular: 'حواله/تردد کالا', en: 'Stock Transfers' },
  nature: ModuleNature.WAREHOUSE,
  table: 'stock_transfers',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  relationDisplay: {
    labelTemplate: '{{system_code}} - {{name}}',
    searchFields: ['name', 'system_code', 'transfer_type', 'notes'],
  },
  fields: [
    { key: 'name', labels: { fa: 'عنوان حواله', en: 'Voucher Title' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, nature: FieldNature.PREDEFINED, isKey: true, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'شماره حواله', en: 'Voucher No.' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    {
      key: 'transfer_type',
      labels: { fa: 'نوع تردد/حواله', en: 'Transfer Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: 'issue',
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      options: [
        { label: 'حواله خروج دستی', value: 'issue' },
        { label: 'رسید ورود دستی', value: 'receipt' },
        { label: 'انتقال دستی بین قفسه‌ها', value: 'transfer' },
        { label: 'برگشت دستی به انبار', value: 'return' },
        { label: 'انبارگردانی دستی', value: 'inventory_count' },
        { label: 'موجودی اول دوره', value: 'opening_balance' },
        { label: 'ضایعات دستی', value: 'waste' },
        { label: 'تولید خودکار', value: 'production' },
        { label: 'مرحله تولید', value: 'production_stage' },
        { label: 'فاکتور فروش خودکار', value: 'sales_invoice' },
        { label: 'فاکتور خرید خودکار', value: 'purchase_invoice' },
      ],
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت حواله', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 4,
      defaultValue: 'draft',
      validation: { required: true },
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'در انتظار تایید', value: 'pending_approval', color: 'orange' },
        { label: 'تایید شده', value: 'approved', color: 'blue' },
        { label: 'صادر شده', value: 'issued', color: 'purple' },
        { label: 'دریافت شده', value: 'received', color: 'green' },
        { label: 'بسته شده', value: 'closed', color: 'gray' },
        { label: 'لغو شده', value: 'canceled', color: 'red' },
      ],
    },
    { key: 'transfer_date', labels: { fa: 'تاریخ حواله', en: 'Transfer Date' }, type: FieldType.DATE, location: FieldLocation.HEADER, order: 5, defaultValue: getTodayLocalDateValue, nature: FieldNature.STANDARD, isTableColumn: true },
    {
      key: 'product_id',
      labels: { fa: 'محصول', en: 'Product' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 6,
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
      relationConfig: { targetModule: 'products', targetField: 'name' },
    },
    { key: 'delivered_qty', labels: { fa: 'مقدار اصلی', en: 'Delivered Qty' }, type: FieldType.NUMBER, location: FieldLocation.HEADER, order: 7, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'required_qty', labels: { fa: 'مقدار فرعی/درخواستی', en: 'Required Qty' }, type: FieldType.NUMBER, location: FieldLocation.HEADER, order: 8, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'from_shelf_id', labels: { fa: 'قفسه برداشت', en: 'From Shelf' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 9, nature: FieldNature.PREDEFINED, isTableColumn: true, relationConfig: { targetModule: 'shelves', targetField: 'name' } },
    { key: 'to_shelf_id', labels: { fa: 'قفسه ورود', en: 'To Shelf' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 10, nature: FieldNature.PREDEFINED, isTableColumn: true, relationConfig: { targetModule: 'shelves', targetField: 'name' } },
    { key: 'source_warehouse_id', labels: { fa: 'انبار مبدا', en: 'Source Warehouse' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'warehouse', order: 1, nature: FieldNature.STANDARD, relationConfig: { targetModule: 'warehouses', targetField: 'name' } },
    { key: 'target_warehouse_id', labels: { fa: 'انبار مقصد', en: 'Target Warehouse' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'warehouse', order: 2, nature: FieldNature.STANDARD, relationConfig: { targetModule: 'warehouses', targetField: 'name' } },
    { key: 'sender_id', labels: { fa: 'تحویل‌دهنده', en: 'Sender' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'people', order: 1, nature: FieldNature.STANDARD, isTableColumn: true, relationConfig: { targetModule: 'profiles', targetField: 'full_name' } },
    { key: 'receiver_id', labels: { fa: 'تحویل‌گیرنده', en: 'Receiver' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'people', order: 2, nature: FieldNature.STANDARD, isTableColumn: true, relationConfig: { targetModule: 'profiles', targetField: 'full_name' } },
    { key: 'assignee_id', labels: { fa: 'مسئول عملیات', en: 'Assignee' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'people', order: 3, nature: FieldNature.STANDARD, isTableColumn: true, relationConfig: { targetModule: 'profiles', targetField: 'full_name' } },
    { key: 'delivery_form_id', labels: { fa: 'فرم تحویل مرتبط', en: 'Delivery Form' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 1, nature: FieldNature.STANDARD, relationConfig: { targetModule: 'delivery_forms', targetField: 'name' } },
    { key: 'invoice_id', labels: { fa: 'فاکتور فروش مرتبط', en: 'Related Invoice' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 2, nature: FieldNature.STANDARD, isTableColumn: true, relationConfig: { targetModule: 'invoices', targetField: 'name' } },
    { key: 'purchase_invoice_id', labels: { fa: 'فاکتور خرید مرتبط', en: 'Related Purchase Invoice' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 3, nature: FieldNature.STANDARD, isTableColumn: true, relationConfig: { targetModule: 'purchase_invoices', targetField: 'name' } },
    { key: 'production_order_id', labels: { fa: 'سفارش تولید مرتبط', en: 'Related Production Order' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 4, nature: FieldNature.STANDARD, isTableColumn: true, relationConfig: { targetModule: 'production_orders', targetField: 'name' } },
    { key: 'related_module_id', labels: { fa: 'مرتبط با بخش', en: 'Related Module' }, type: FieldType.SELECT, location: FieldLocation.BLOCK, blockId: 'relations', order: 5, options: RELATED_MODULE_OPTIONS, nature: FieldNature.STANDARD },
    { key: 'related_record_id', labels: { fa: 'رکورد مرتبط', en: 'Related Record' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'relations', order: 6, relationConfig: { targetModule: '', dependsOn: 'related_module_id' }, nature: FieldNature.STANDARD },
    { key: 'notes', labels: { fa: 'یادداشت‌ها', en: 'Notes' }, type: FieldType.LONG_TEXT, location: FieldLocation.BLOCK, blockId: 'notes', order: 1, nature: FieldNature.STANDARD },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.BLOCK, blockId: 'notes', order: 2, nature: FieldNature.STANDARD },
    { key: 'process_template_id', labels: { fa: 'الگوی فرآیند اجرا', en: 'Execution Template' }, type: FieldType.RELATION, location: FieldLocation.BLOCK, blockId: 'process', order: 1, relationConfig: { targetModule: 'process_templates', targetField: 'name' }, nature: FieldNature.STANDARD },
    { key: 'execution_process_draft', labels: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'process', order: 2, nature: FieldNature.STANDARD },
    { key: 'inventory_applied_at', labels: { fa: 'زمان اثر روی موجودی', en: 'Inventory Applied At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'system', order: 1, readonly: true, nature: FieldNature.SYSTEM, hideInCreateForm: true },
    { key: 'created_at', labels: { fa: 'زمان ثبت', en: 'Created At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'system', order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
  ],
  blocks: [
    { id: 'warehouse', titles: { fa: 'انبار و قفسه', en: 'Warehouse' }, type: BlockType.FIELD_GROUP, order: 1, icon: 'BankOutlined' },
    { id: 'people', titles: { fa: 'تحویل و مسئولیت', en: 'People' }, type: BlockType.FIELD_GROUP, order: 2, icon: 'TeamOutlined' },
    { id: 'relations', titles: { fa: 'ارتباطات', en: 'Relations' }, type: BlockType.FIELD_GROUP, order: 3, icon: 'LinkOutlined' },
    { id: 'notes', titles: { fa: 'یادداشت‌ها', en: 'Notes' }, type: BlockType.FIELD_GROUP, order: 4, icon: 'FileTextOutlined' },
    { id: 'process', titles: { fa: 'فرآیند اجرا', en: 'Execution Process' }, type: BlockType.FIELD_GROUP, order: 5, icon: 'DeploymentUnitOutlined' },
    { id: 'system', titles: { fa: 'اطلاعات سیستمی', en: 'System' }, type: BlockType.FIELD_GROUP, order: 6, icon: 'DatabaseOutlined', hideInCreateForm: true },
  ],
  relatedTabs: [],
};
