import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const stockTransfersConfig: ModuleDefinition = {
  id: 'stock_transfers',
  titles: { fa: 'تردد کالاها', en: 'Stock Transfers' },
  nature: ModuleNature.WAREHOUSE,
  table: 'stock_transfers',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'transfer_type',
      labels: { fa: 'نوع تردد', en: 'Transfer Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 1,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      options: [
        { label: 'تولید', value: 'production' },
        { label: 'مرحله تولید', value: 'production_stage' },
        { label: 'فاکتور فروش', value: 'sales_invoice' },
        { label: 'فاکتور خرید', value: 'purchase_invoice' },
        { label: 'انبارگردانی', value: 'inventory_count' },
        { label: 'موجودی اول دوره', value: 'opening_balance' },
        { label: 'ضایعات', value: 'waste' },
      ],
    },
    {
      key: 'product_id',
      labels: { fa: 'محصول', en: 'Product' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 2,
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
      relationConfig: { targetModule: 'products', targetField: 'name' },
    },
    {
      key: 'delivered_qty',
      labels: { fa: 'مقدار اصلی', en: 'Delivered Qty' },
      type: FieldType.NUMBER,
      location: FieldLocation.HEADER,
      order: 3,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'required_qty',
      labels: { fa: 'مقدار فرعی', en: 'Required Qty' },
      type: FieldType.NUMBER,
      location: FieldLocation.HEADER,
      order: 4,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: 'from_shelf_id',
      labels: { fa: 'قفسه برداشت', en: 'From Shelf' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 5,
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
      relationConfig: { targetModule: 'shelves', targetField: 'name' },
    },
    {
      key: 'to_shelf_id',
      labels: { fa: 'قفسه ورود', en: 'To Shelf' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 6,
      nature: FieldNature.PREDEFINED,
      isTableColumn: true,
      relationConfig: { targetModule: 'shelves', targetField: 'name' },
    },
    {
      key: 'invoice_id',
      labels: { fa: 'فاکتور فروش مرتبط', en: 'Related Invoice' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'general',
      order: 7,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      relationConfig: { targetModule: 'invoices', targetField: 'name' },
    },
    {
      key: 'production_order_id',
      labels: { fa: 'سفارش تولید مرتبط', en: 'Related Production Order' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'general',
      order: 8,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      relationConfig: { targetModule: 'production_orders', targetField: 'name' },
    },
    {
      key: 'sender_id',
      labels: { fa: 'تحویل‌دهنده', en: 'Sender' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'general',
      order: 9,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
    },
    {
      key: 'receiver_id',
      labels: { fa: 'تحویل‌گیرنده', en: 'Receiver' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'general',
      order: 10,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
      relationConfig: { targetModule: 'profiles', targetField: 'full_name' },
    },
    {
      key: 'created_at',
      labels: { fa: 'زمان ثبت', en: 'Created At' },
      type: FieldType.DATETIME,
      location: FieldLocation.HEADER,
      order: 11,
      readonly: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
  ],
  blocks: [
    {
      id: 'general',
      titles: { fa: 'جزئیات تردد کالا', en: 'Stock Transfer Details' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};

