import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from "../types";

export const surveysModule: ModuleDefinition = {
  id: "surveys",
  titles: { fa: "نظرسنجی‌ها", faSingular: "نظرسنجی", en: "Surveys" },
  nature: ModuleNature.STANDARD,
  table: "surveys",
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: "title",
      labels: { fa: "عنوان پاسخ", en: "Submission Title" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: "status",
      labels: { fa: "وضعیت", en: "Status" },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      defaultValue: "new",
      isTableColumn: true,
      options: [
        { label: "جدید", value: "new", color: "blue" },
        { label: "بررسی شد", value: "reviewed", color: "gold" },
        { label: "نیازمند پیگیری", value: "follow_up", color: "orange" },
        { label: "بسته شده", value: "closed", color: "green" },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: "survey_type",
      labels: { fa: "نوع نظرسنجی", en: "Survey Type" },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      defaultValue: "general",
      isTableColumn: true,
      options: [
        { label: "عمومی", value: "general" },
        { label: "خدمات", value: "service" },
        { label: "محصول", value: "product" },
        { label: "رویداد", value: "event" },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: "respondent_name",
      labels: { fa: "نام پاسخ‌دهنده", en: "Respondent Name" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "respondent_phone",
      labels: { fa: "شماره تماس", en: "Respondent Phone" },
      type: FieldType.PHONE,
      location: FieldLocation.HEADER,
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: "respondent_email",
      labels: { fa: "ایمیل", en: "Respondent Email" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 6,
      nature: FieldNature.STANDARD,
    },
    {
      key: "channel",
      labels: { fa: "کانال دریافت", en: "Channel" },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 7,
      defaultValue: "web_form",
      isTableColumn: true,
      options: [
        { label: "وب‌فرم", value: "web_form" },
        { label: "حضوری", value: "in_person" },
        { label: "تلفنی", value: "phone" },
        { label: "پیام‌رسان", value: "messenger" },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: "overall_experience",
      labels: { fa: "ارزیابی کلی", en: "Overall Experience" },
      type: FieldType.STATUS,
      location: FieldLocation.BLOCK,
      blockId: "evaluation",
      order: 1,
      validation: { required: true },
      isTableColumn: true,
      options: [
        { label: "خیلی ضعیف", value: "very_bad", color: "red" },
        { label: "ضعیف", value: "bad", color: "volcano" },
        { label: "متوسط", value: "average", color: "gold" },
        { label: "خوب", value: "good", color: "blue" },
        { label: "عالی", value: "excellent", color: "green" },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: "recommendation_score",
      labels: { fa: "امتیاز احتمال معرفی", en: "Recommendation Score" },
      type: FieldType.NUMBER,
      location: FieldLocation.BLOCK,
      blockId: "evaluation",
      order: 2,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "favorite_aspects",
      labels: { fa: "نقاط قوت", en: "Favorite Aspects" },
      type: FieldType.MULTI_SELECT,
      location: FieldLocation.BLOCK,
      blockId: "evaluation",
      order: 3,
      options: [
        { label: "کیفیت خدمت", value: "service_quality" },
        { label: "رفتار تیم", value: "team_behavior" },
        { label: "سرعت انجام", value: "speed" },
        { label: "قیمت", value: "pricing" },
        { label: "فضای کسب‌وکار", value: "environment" },
        { label: "پشتیبانی", value: "support" },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: "improvement_areas",
      labels: { fa: "زمینه‌های بهبود", en: "Improvement Areas" },
      type: FieldType.MULTI_SELECT,
      location: FieldLocation.BLOCK,
      blockId: "evaluation",
      order: 4,
      options: [
        { label: "سرعت پاسخ‌گویی", value: "response_time" },
        { label: "کیفیت اجرا", value: "execution_quality" },
        { label: "شفافیت قیمت", value: "price_clarity" },
        { label: "تنوع خدمات", value: "service_variety" },
        { label: "پیگیری بعد از فروش", value: "after_sales" },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: "visit_datetime",
      labels: { fa: "تاریخ و زمان تجربه", en: "Visit Datetime" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "details",
      order: 1,
      nature: FieldNature.STANDARD,
      isTableColumn: true,
    },
    {
      key: "branch_location",
      labels: { fa: "موقعیت شعبه / محل تجربه", en: "Branch Location" },
      type: FieldType.LOCATION,
      location: FieldLocation.BLOCK,
      blockId: "details",
      order: 2,
      nature: FieldNature.STANDARD,
    },
    {
      key: "follow_up_consent",
      labels: { fa: "تمایل به پیگیری", en: "Follow Up Consent" },
      type: FieldType.CHECKBOX,
      location: FieldLocation.BLOCK,
      blockId: "details",
      order: 3,
      defaultValue: false,
      nature: FieldNature.STANDARD,
    },
    {
      key: "comments",
      labels: { fa: "نظر و توضیحات", en: "Comments" },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: "details",
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: "created_at",
      labels: { fa: "زمان ثبت", en: "Created At" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "details",
      order: 20,
      readonly: true,
      hideInCreateForm: true,
      nature: FieldNature.SYSTEM,
      isTableColumn: true,
    },
  ],
  blocks: [
    {
      id: "evaluation",
      titles: { fa: "ارزیابی", en: "Evaluation" },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
    {
      id: "details",
      titles: { fa: "جزئیات تکمیلی", en: "Additional Details" },
      type: BlockType.FIELD_GROUP,
      order: 2,
    },
  ],
  relatedTabs: [],
};
