import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from '../types';

const RELATED_MODULE_OPTIONS = [
  { label: 'کاربران', value: 'profiles' },
  { label: 'کارکنان', value: 'employees' },
  { label: 'مشتریان', value: 'customers' },
  { label: 'تامین‌کنندگان', value: 'suppliers' },
  { label: 'بازاریابی', value: 'marketing_leads' },
];

export const voipCallReportsConfig: ModuleDefinition = {
  id: 'voip_call_reports',
  titles: { fa: 'گزارش تماس‌های VoIP', faSingular: 'گزارش تماس VoIP', en: 'VoIP Call Reports' },
  nature: ModuleNature.STANDARD,
  table: 'voip_call_logs',
  systemManaged: true,
  disableCreate: true,
  disableDetailView: true,
  hideFullRecordAction: true,
  listPreviewMode: 'modal',
  defaultSorters: [{ field: 'started_at', order: 'desc' }],
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  quickPreview: {
    fieldKeys: [
      'title',
      'direction',
      'status',
      'source_number',
      'destination_number',
      'extension',
      'started_at',
      'ended_at',
      'wait_seconds',
      'talk_seconds',
      'provider',
      'operator_code',
      'trunk',
      'phone_match_status',
      'module_id',
      'record_id',
      'related_module_id',
      'related_record_id',
      'assignee_id',
      'operator_report',
      'related_task_id',
      'recording_url',
      'tags',
    ],
    editableFields: ['tags', 'operator_report', 'module_id', 'record_id', 'assignee_id', 'related_task_id'],
    relatedModuleOptions: ['profiles', 'employees', 'customers', 'suppliers', 'marketing_leads'],
    audioField: 'recording_url',
  },
  fields: [
    {
      key: 'phone_match_status',
      labels: { fa: 'وضعیت تطبیق شماره', en: 'Phone Match' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 8.2,
      isTableColumn: true,
      options: [
        { label: 'تطبیق قطعی', value: 'matched', color: 'green' },
        { label: 'نیاز به انتخاب مخاطب', value: 'ambiguous', color: 'orange' },
        { label: 'شماره ناشناس', value: 'unknown', color: 'gray' },
        { label: 'تطبیق دستی', value: 'manual', color: 'blue' },
      ],
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'title',
      labels: { fa: 'عنوان', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'direction',
      labels: { fa: 'نوع تماس', en: 'Direction' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      options: [
        { label: 'ورودی', value: 'incoming', color: 'green' },
        { label: 'خروجی', value: 'outgoing', color: 'blue' },
        { label: 'داخلی', value: 'internal', color: 'cyan' },
        { label: 'نامشخص', value: 'unknown', color: 'gray' },
      ],
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      options: [
        { label: 'پاسخ داده شده', value: 'answered', color: 'green' },
        { label: 'بی‌پاسخ', value: 'missed', color: 'red' },
        { label: 'ناموفق', value: 'failed', color: 'red' },
        { label: 'در جریان', value: 'ringing', color: 'orange' },
        { label: 'پایان یافته', value: 'completed', color: 'blue' },
        { label: 'نامشخص', value: 'unknown', color: 'gray' },
      ],
      nature: FieldNature.SYSTEM,
    },
    { key: 'source_number', labels: { fa: 'شماره مبدا', en: 'Source' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 4, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'destination_number', labels: { fa: 'شماره مقصد', en: 'Destination' }, type: FieldType.PHONE, location: FieldLocation.HEADER, order: 5, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'extension', labels: { fa: 'داخلی', en: 'Extension' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 6, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'started_at', labels: { fa: 'شروع تماس', en: 'Started At' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 7, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'talk_seconds', labels: { fa: 'مدت مکالمه (ثانیه)', en: 'Talk Seconds' }, type: FieldType.NUMBER, location: FieldLocation.HEADER, order: 8, isTableColumn: true, nature: FieldNature.SYSTEM },
    { key: 'wait_seconds', labels: { fa: 'زمان انتظار (ثانیه)', en: 'Wait Seconds' }, type: FieldType.NUMBER, location: FieldLocation.BLOCK, blockId: 'details', order: 1, nature: FieldNature.SYSTEM },
    { key: 'ended_at', labels: { fa: 'پایان تماس', en: 'Ended At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'details', order: 2, nature: FieldNature.SYSTEM },
    { key: 'provider', labels: { fa: 'سرویس‌دهنده', en: 'Provider' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 3, nature: FieldNature.SYSTEM },
    { key: 'service_id', labels: { fa: 'شناسه سرویس', en: 'Service ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 4, nature: FieldNature.SYSTEM },
    { key: 'operator_code', labels: { fa: 'کد اپراتور', en: 'Operator Code' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 5, nature: FieldNature.SYSTEM },
    { key: 'trunk', labels: { fa: 'ترانک', en: 'Trunk' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 6, nature: FieldNature.SYSTEM },
    { key: 'call_id', labels: { fa: 'شناسه تماس', en: 'Call ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 7, nature: FieldNature.SYSTEM },
    { key: 'object_id', labels: { fa: 'شناسه آبجکت', en: 'Object ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 8, nature: FieldNature.SYSTEM },
    { key: 'file_id', labels: { fa: 'شناسه فایل صوت', en: 'File ID' }, type: FieldType.TEXT, location: FieldLocation.BLOCK, blockId: 'details', order: 9, nature: FieldNature.SYSTEM },
    { key: 'recording_url', labels: { fa: 'فایل صوت تماس', en: 'Recording' }, type: FieldType.LINK, location: FieldLocation.BLOCK, blockId: 'details', order: 10, nature: FieldNature.SYSTEM },
    {
      key: 'module_id',
      labels: { fa: 'ماژول مخاطب', en: 'Related Module' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'operations',
      order: 1,
      isTableColumn: true,
      options: RELATED_MODULE_OPTIONS,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'record_id',
      labels: { fa: 'مخاطب مرتبط', en: 'Related Record' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'operations',
      order: 2,
      isTableColumn: true,
      relationConfig: { targetModule: '', dependsOn: 'module_id' },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'related_module_id',
      labels: { fa: 'ماژول رکورد مبدا', en: 'Related Source Module' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'operations',
      order: 2.2,
      options: RELATED_MODULE_OPTIONS,
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'related_record_id',
      labels: { fa: 'رکورد مبدا', en: 'Related Source Record' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'operations',
      order: 2.4,
      relationConfig: { targetModule: '', dependsOn: 'related_module_id' },
      nature: FieldNature.SYSTEM,
    },
    {
      key: 'assignee_id',
      labels: { fa: 'مسئول', en: 'Assignee' },
      type: FieldType.USER,
      location: FieldLocation.BLOCK,
      blockId: 'operations',
      order: 3,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'operator_report',
      labels: { fa: 'گزارش اپراتور', en: 'Operator Report' },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: 'operations',
      order: 4,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'related_task_id',
      labels: { fa: 'وظیفه مرتبط', en: 'Related Task' },
      type: FieldType.RELATION,
      location: FieldLocation.BLOCK,
      blockId: 'operations',
      order: 5,
      relationConfig: { targetModule: 'tasks', targetField: 'name' },
      nature: FieldNature.STANDARD,
    },
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 9, nature: FieldNature.STANDARD, isTableColumn: true },
    { key: 'metadata', labels: { fa: 'جزئیات سیستمی', en: 'Metadata' }, type: FieldType.JSON, location: FieldLocation.BLOCK, blockId: 'details', order: 11, nature: FieldNature.SYSTEM },
    { key: 'created_at', labels: { fa: 'زمان ثبت', en: 'Created At' }, type: FieldType.DATETIME, location: FieldLocation.BLOCK, blockId: 'details', order: 12, nature: FieldNature.SYSTEM },
  ],
  blocks: [
    { id: 'details', titles: { fa: 'جزئیات تماس', en: 'Call Details' }, type: BlockType.FIELD_GROUP, order: 1 },
    { id: 'operations', titles: { fa: 'پیگیری و ارتباط', en: 'Follow-up' }, type: BlockType.FIELD_GROUP, order: 2 },
  ],
};
