import {
  BlockType,
  FieldLocation,
  FieldNature,
  FieldType,
  ModuleDefinition,
  ModuleNature,
  ViewMode,
} from "../types";

export const webFormsConfig: ModuleDefinition = {
  id: "web_forms",
  titles: { fa: "وب فرم‌ها", faSingular: "وب فرم", en: "Web Forms" },
  nature: ModuleNature.STANDARD,
  table: "web_forms",
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: "name",
      labels: { fa: "نام فرم", en: "Name" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.PREDEFINED,
    },
    {
      key: "route_slug",
      labels: { fa: "اسلاگ", en: "Slug" },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 2,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: "target_module_id",
      labels: { fa: "بخش مقصد", en: "Target Module" },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 3,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: "access_scope",
      labels: { fa: "نوع دسترسی", en: "Access Scope" },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 4,
      isTableColumn: true,
      defaultValue: "public",
      options: [
        { label: "عمومی", value: "public" },
        { label: "داخلی", value: "internal" },
      ],
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: "is_active",
      labels: { fa: "فعال", en: "Active" },
      type: FieldType.CHECKBOX,
      location: FieldLocation.HEADER,
      order: 5,
      isTableColumn: true,
      defaultValue: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: "description",
      labels: { fa: "توضیحات", en: "Description" },
      type: FieldType.LONG_TEXT,
      location: FieldLocation.BLOCK,
      blockId: "web_form_info",
      order: 1,
      nature: FieldNature.STANDARD,
    },
    {
      key: "updated_at",
      labels: { fa: "آخرین بروزرسانی", en: "Updated At" },
      type: FieldType.DATETIME,
      location: FieldLocation.BLOCK,
      blockId: "web_form_info",
      order: 2,
      isTableColumn: true,
      readonly: true,
      hideInCreateForm: true,
      nature: FieldNature.SYSTEM,
    },
  ],
  blocks: [
    {
      id: "web_form_info",
      titles: { fa: "اطلاعات وب فرم", en: "Web Form Info" },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
