import { BlockType, FieldLocation, FieldNature, FieldType, ModuleDefinition, ModuleNature, ViewMode } from '../types';

export const workSchedulesModule: ModuleDefinition = {
  id: 'work_schedules',
  titles: { fa: 'برنامه حضور', faSingular: 'برنامه حضور', en: 'Work Schedules' },
  nature: ModuleNature.STANDARD,
  table: 'work_schedules',
  supportedViewModes: [ViewMode.LIST, ViewMode.GRID],
  defaultViewMode: ViewMode.LIST,
  fields: [
    {
      key: 'title',
      labels: { fa: 'عنوان برنامه', en: 'Title' },
      type: FieldType.TEXT,
      location: FieldLocation.HEADER,
      order: 1,
      isKey: true,
      isTableColumn: true,
      validation: { required: true },
      nature: FieldNature.STANDARD,
    },
    {
      key: 'status',
      labels: { fa: 'وضعیت', en: 'Status' },
      type: FieldType.STATUS,
      location: FieldLocation.HEADER,
      order: 1.5,
      defaultValue: 'draft',
      isTableColumn: true,
      options: [
        { label: 'پیش‌نویس', value: 'draft', color: 'default' },
        { label: 'فعال', value: 'active', color: 'green' },
        { label: 'منقضی', value: 'expired', color: 'red' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'effective_from',
      labels: { fa: 'از تاریخ', en: 'Effective From' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 1.6,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'effective_to',
      labels: { fa: 'تا تاریخ', en: 'Effective To' },
      type: FieldType.DATE,
      location: FieldLocation.HEADER,
      order: 1.7,
      isTableColumn: true,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'schedule_type',
      labels: { fa: 'نوع برنامه', en: 'Schedule Type' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 2,
      defaultValue: 'fixed',
      isTableColumn: true,
      options: [
        { label: 'ثابت', value: 'fixed' },
        { label: 'شناور', value: 'flexible' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'start_time',
      labels: { fa: 'ساعت شروع', en: 'Start Time' },
      type: FieldType.TIME,
      blockId: 'timing',
      order: 4,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'end_time',
      labels: { fa: 'ساعت پایان', en: 'End Time' },
      type: FieldType.TIME,
      blockId: 'timing',
      order: 5,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'flexible_start_time',
      labels: { fa: 'شروع بازه مجاز', en: 'Flexible Start Time' },
      type: FieldType.TIME,
      blockId: 'timing',
      order: 6,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'flexible_end_time',
      labels: { fa: 'پایان بازه مجاز', en: 'Flexible End Time' },
      type: FieldType.TIME,
      blockId: 'timing',
      order: 7,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'expected_daily_minutes',
      labels: { fa: 'دقایق کار روزانه', en: 'Expected Daily Minutes' },
      type: FieldType.NUMBER,
      blockId: 'timing',
      order: 8,
      defaultValue: 480,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'weekly_days',
      labels: { fa: 'روزهای کاری', en: 'Weekly Days' },
      type: FieldType.MULTI_SELECT,
      blockId: 'timing',
      order: 9,
      options: [
        { label: 'شنبه', value: 'sat' },
        { label: 'یکشنبه', value: 'sun' },
        { label: 'دوشنبه', value: 'mon' },
        { label: 'سه‌شنبه', value: 'tue' },
        { label: 'چهارشنبه', value: 'wed' },
        { label: 'پنجشنبه', value: 'thu' },
        { label: 'جمعه', value: 'fri' },
      ],
      nature: FieldNature.STANDARD,
    },
    {
      key: 'notes',
      labels: { fa: 'توضیحات', en: 'Notes' },
      type: FieldType.LONG_TEXT,
      blockId: 'timing',
      order: 10,
      nature: FieldNature.STANDARD,
    },
  
    { key: 'tags', labels: { fa: 'برچسب‌ها', en: 'Tags' }, type: FieldType.TAGS, location: FieldLocation.HEADER, order: 2.1, nature: FieldNature.STANDARD, isTableColumn: true },
],
  blocks: [
    {
      id: 'timing',
      titles: { fa: 'تنظیمات برنامه حضور', en: 'Schedule Settings' },
      type: BlockType.FIELD_GROUP,
      order: 1,
    },
  ],
  relatedTabs: [],
};
