const normalizeText = (value: unknown) => String(value || '').trim();

type CashBankNavigationState = {
  focusBlockId?: string;
  focusRowKey?: string;
  cashBankOperationId?: string;
};

export type ResolvedCashBankSourceNavigation = {
  moduleId: string;
  recordId: string;
  state: CashBankNavigationState;
};

const getCashBankMetadata = (record: any): Record<string, any> => (
  record?.metadata && typeof record.metadata === 'object'
    ? record.metadata
    : {}
);

export const isAutoGeneratedCashBankRecord = (record: any) => {
  const metadata = getCashBankMetadata(record);
  return metadata.is_auto_generated === true
    || (!!normalizeText(metadata.source_table) && !!normalizeText(metadata.source_record_id));
};

export const resolveCashBankSourceNavigation = (record: any): ResolvedCashBankSourceNavigation | null => {
  if (!record || typeof record !== 'object') return null;

  const metadata = getCashBankMetadata(record);
  const sourceTable = normalizeText(metadata.source_table);
  const sourceRecordId = normalizeText(metadata.source_record_id);
  const sourceBlockId = normalizeText(metadata.source_block_id) || 'payments';
  const sourceRowKey = normalizeText(metadata.source_row_key);
  const cashBankOperationId = normalizeText(record?.id);

  const buildResult = (moduleId: string, recordId: string, includeFocus = true): ResolvedCashBankSourceNavigation | null => {
    const normalizedModuleId = normalizeText(moduleId);
    const normalizedRecordId = normalizeText(recordId);
    if (!normalizedModuleId || !normalizedRecordId) return null;
    return {
      moduleId: normalizedModuleId,
      recordId: normalizedRecordId,
      state: {
        focusBlockId: includeFocus ? sourceBlockId || 'payments' : undefined,
        focusRowKey: includeFocus && sourceRowKey ? sourceRowKey : undefined,
        cashBankOperationId: cashBankOperationId || undefined,
      },
    };
  };

  if (sourceTable && sourceRecordId) {
    return buildResult(sourceTable, sourceRecordId, true);
  }

  return (
    buildResult('invoices', record?.sales_invoice_id, false)
    || buildResult('purchase_invoices', record?.purchase_invoice_id, false)
    || buildResult('expense_documents', record?.expense_document_id, false)
    || buildResult('employee_advances', record?.employee_advance_id, false)
    || buildResult('payroll_slips', record?.payroll_slip_id, false)
  );
};
