import { supabase as sharedSupabase } from '../supabaseClient';
import { syncRecordTags } from './recordTags';
import { runSelectWithCompatibleColumns } from './selectCompat';
import { runWriteWithCompatiblePayload } from './writeCompat';
import {
  OPERATIONAL_CASH_BANK_SOURCE_MODULES,
  buildCashBankOperationPayloadFromPaymentRow,
  buildOperationMetadata,
  buildSourceOperationKey,
  collectPaymentAccountIds,
  fetchAllOperationalRows,
  fetchTreasuryAccountModuleMap,
  getOperationalPaymentRowKeyCandidates,
  normalizeOperationalText,
  parseCashBankMetadata,
  parseOperationalPayments,
  normalizeRowTags,
  resolveOperationalPaymentRowKey,
} from './operationalCashBankSources';

type BackfillSupabaseClient = typeof sharedSupabase;

type BackfillSummary = {
  inserted: number;
  updated: number;
  canceled: number;
  sourceRowsUpdated: number;
  sourceRecordsUpdated: number;
};

const createLocalRowKey = () => {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `row_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
};

const CASH_BANK_OPERATION_FETCH_COLUMNS = [
  'id',
  'metadata',
  'status',
  'operation_type',
  'payment_type',
  'operation_date',
  'amount',
  'bank_account_id',
  'cash_box_id',
  'petty_fund_id',
  'payment_bank_account_id',
  'payment_cash_box_id',
  'payment_petty_fund_id',
  'receipt_bank_account_id',
  'receipt_cash_box_id',
  'receipt_petty_fund_id',
  'customer_id',
  'supplier_id',
  'employee_id',
  'assignee_id',
  'assignee_type',
  'assignee_role_id',
  'image_url',
  'description',
  'attachment_url',
  'barter_id',
  'cheque_id',
  'sales_invoice_id',
  'purchase_invoice_id',
  'expense_document_id',
  'employee_advance_id',
  'payroll_slip_id',
  'tags',
] as const;

const fetchExistingCashBankOperationRows = async (supabase: BackfillSupabaseClient) => {
  const rows: any[] = [];
  let from = 0;

  while (true) {
    const to = from + 199;
    const result = await runSelectWithCompatibleColumns<any[]>({
      cacheKey: 'cash-bank-backfill:existing-operations',
      columns: CASH_BANK_OPERATION_FETCH_COLUMNS,
      execute: (selectExpr) =>
        supabase
          .from('cash_bank_operations')
          .select(selectExpr)
          .range(from, to),
    });
    if (result.error) throw result.error;
    const batch = Array.isArray(result.data) ? result.data : [];
    rows.push(...batch);
    if (batch.length < 200) break;
    from += 200;
  }

  return rows;
};

const fetchExistingAutoGeneratedOperations = async (supabase: BackfillSupabaseClient) => {
  const rows = await fetchExistingCashBankOperationRows(supabase);
  const map = new Map<string, any>();
  const byId = new Map<string, any>();

  rows.forEach((row: any) => {
    const rowId = normalizeOperationalText(row?.id);
    if (rowId) byId.set(rowId, row);
    const metadata = parseCashBankMetadata(row?.metadata);
    if (!metadata || metadata.is_auto_generated !== true) return;
    const sourceTable = normalizeOperationalText(metadata.source_table);
    const sourceRecordId = normalizeOperationalText(metadata.source_record_id);
    const sourceRowKey = normalizeOperationalText(metadata.source_row_key);
    if (!sourceTable || !sourceRecordId || !sourceRowKey) return;
    map.set(buildSourceOperationKey(sourceTable, sourceRecordId, sourceRowKey), { ...row, metadata });
  });

  return { bySourceKey: map, byId };
};

const OPERATION_COMPARE_KEYS = [
  'operation_type',
  'payment_type',
  'status',
  'operation_date',
  'amount',
  'bank_account_id',
  'cash_box_id',
  'petty_fund_id',
  'payment_bank_account_id',
  'payment_cash_box_id',
  'payment_petty_fund_id',
  'receipt_bank_account_id',
  'receipt_cash_box_id',
  'receipt_petty_fund_id',
  'customer_id',
  'supplier_id',
  'employee_id',
  'assignee_id',
  'assignee_type',
  'assignee_role_id',
  'image_url',
  'description',
  'attachment_url',
  'tags',
  'barter_id',
  'cheque_id',
  'sales_invoice_id',
  'purchase_invoice_id',
  'expense_document_id',
  'employee_advance_id',
  'payroll_slip_id',
] as const;

const sameValue = (left: any, right: any) => {
  if (left === right) return true;
  if (left === null || left === undefined || left === '') {
    return right === null || right === undefined || right === '';
  }
  if (right === null || right === undefined || right === '') return false;
  if (typeof left === 'number' || typeof right === 'number') {
    return Number(left) === Number(right);
  }
  if (typeof left === 'object' || typeof right === 'object') {
    try {
      return JSON.stringify(left ?? null) === JSON.stringify(right ?? null);
    } catch {
      return false;
    }
  }
  return String(left) === String(right);
};

const shouldUpdateOperation = (existingRow: any, nextPayload: Record<string, any>) =>
  OPERATION_COMPARE_KEYS.some((key) => !sameValue(existingRow?.[key], nextPayload[key]));

export const backfillOperationalCashBankOperations = async (
  supabase: BackfillSupabaseClient = sharedSupabase,
): Promise<BackfillSummary> => {
  void supabase;
  return {
    inserted: 0,
    updated: 0,
    canceled: 0,
    sourceRowsUpdated: 0,
    sourceRecordsUpdated: 0,
  };

  const existingOperations = await fetchExistingAutoGeneratedOperations(supabase);
  const nowIso = new Date().toISOString();
  const summary: BackfillSummary = {
    inserted: 0,
    updated: 0,
    canceled: 0,
    sourceRowsUpdated: 0,
    sourceRecordsUpdated: 0,
  };
  const activeSourceKeys = new Set<string>();

  for (const source of OPERATIONAL_CASH_BANK_SOURCE_MODULES) {
    const records = await fetchAllOperationalRows(supabase, source.table, source.selectFields.join(','));
    const accountModuleById = await fetchTreasuryAccountModuleMap(
      supabase,
      collectPaymentAccountIds(records, source.accountField),
    );

    for (const record of records) {
      const recordId = normalizeOperationalText(record?.id);
      if (!recordId) continue;
      const payments = parseOperationalPayments(record?.payments);
      if (payments.length === 0) continue;

      const nextPayments = payments.map((row) => ({ ...row }));
      const inserts: Record<string, any>[] = [];
      const insertTargets: number[] = [];
      let sourceChanged = false;

      for (let index = 0; index < nextPayments.length; index += 1) {
        const row = nextPayments[index];
        if (source.moduleId === 'payroll_slips' && normalizeOperationalText(row?.employee_advance_id)) {
          continue;
        }
        let rowKey = resolveOperationalPaymentRowKey(row, index);
        if (!rowKey) {
          rowKey = createLocalRowKey();
          row.row_key = rowKey;
          sourceChanged = true;
          summary.sourceRowsUpdated += 1;
        }

        const sourceKey = buildSourceOperationKey(source.moduleId, recordId, rowKey);
        const sourceKeyCandidates = getOperationalPaymentRowKeyCandidates(row, index)
          .map((candidate) => buildSourceOperationKey(source.moduleId, recordId, candidate));
        const existingOperation =
          sourceKeyCandidates.map((candidate) => existingOperations.bySourceKey.get(candidate)).find(Boolean)
          ||
          existingOperations.bySourceKey.get(sourceKey)
          || existingOperations.byId.get(normalizeOperationalText(row?._cash_bank_operation_id));
        if (existingOperation && normalizeOperationalText(row?._cash_bank_operation_id) !== existingOperation.id) {
          row._cash_bank_operation_id = existingOperation.id;
          sourceChanged = true;
          summary.sourceRowsUpdated += 1;
        }

        const { payload, paymentType, amount, status, rowTags } = buildCashBankOperationPayloadFromPaymentRow({
          source,
          record,
          row,
          rowKey,
          accountModuleById,
          nowIso,
        });

        if (!paymentType || amount <= 0 || status === 'canceled') {
          if (existingOperation && normalizeOperationalText(existingOperation?.status) !== 'canceled') {
            const cancelPayload = {
              status: 'canceled',
              metadata: buildOperationMetadata(source.moduleId, recordId, rowKey),
              updated_at: nowIso,
            };
            const cancelResult = await runWriteWithCompatiblePayload<null>({
              cacheKey: 'cash-bank-backfill:cancel',
              payload: cancelPayload,
              execute: (compatiblePayload) =>
                supabase
                  .from('cash_bank_operations')
                  .update(compatiblePayload)
                  .eq('id', existingOperation.id),
            });
            if (cancelResult.error) throw cancelResult.error;
            summary.canceled += 1;
          }
          continue;
        }

        activeSourceKeys.add(sourceKey);

        if (existingOperation) {
          if (shouldUpdateOperation(existingOperation, payload)) {
            const updateResult = await runWriteWithCompatiblePayload<null>({
              cacheKey: 'cash-bank-backfill:update',
              payload,
              execute: (compatiblePayload) =>
                supabase
                  .from('cash_bank_operations')
                  .update(compatiblePayload)
                  .eq('id', existingOperation.id),
            });
            if (updateResult.error) throw updateResult.error;
            summary.updated += 1;
          }
          await syncRecordTags(supabase, 'cash_bank_operations', existingOperation.id, rowTags);
          existingOperations.bySourceKey.set(sourceKey, {
            ...existingOperation,
            ...payload,
            id: existingOperation.id,
            metadata: payload.metadata,
          });
          continue;
        }

        inserts.push(payload);
        insertTargets.push(index);
      }

      if (inserts.length > 0) {
        const insertedRows: any[] = [];
        for (let insertIndex = 0; insertIndex < inserts.length; insertIndex += 1) {
          const insertPayload = inserts[insertIndex];
          const insertResult = await runWriteWithCompatiblePayload<any>({
            cacheKey: 'cash-bank-backfill:insert',
            payload: insertPayload,
            execute: (compatiblePayload) =>
              supabase
                .from('cash_bank_operations')
                .insert(compatiblePayload)
                .select('id')
                .single(),
          });
          if (insertResult.error) throw insertResult.error;
          insertedRows.push({
            ...(insertResult.data || {}),
            metadata: insertResult.payload?.metadata ?? insertPayload?.metadata ?? null,
          });
        }

        for (let insertedIndex = 0; insertedIndex < (insertedRows || []).length; insertedIndex += 1) {
          const insertedRow: any = (insertedRows || [])[insertedIndex];
          const paymentIndex = insertTargets[insertedIndex];
          if (paymentIndex === undefined) continue;
          const insertedId = normalizeOperationalText(insertedRow?.id);
          if (!insertedId) continue;
          const paymentRow = nextPayments[paymentIndex];
          paymentRow._cash_bank_operation_id = insertedId;
          sourceChanged = true;
          summary.sourceRowsUpdated += 1;
          summary.inserted += 1;
          await syncRecordTags(supabase, 'cash_bank_operations', insertedId, normalizeRowTags(paymentRow?.tags));

          const metadata = parseCashBankMetadata(insertedRow?.metadata);
          const sourceTable = normalizeOperationalText(metadata?.source_table) || source.moduleId;
          const sourceRecordId = normalizeOperationalText(metadata?.source_record_id) || recordId;
          const sourceRowKey = normalizeOperationalText(metadata?.source_row_key || paymentRow?.row_key);
          if (sourceRowKey) {
            existingOperations.bySourceKey.set(buildSourceOperationKey(sourceTable, sourceRecordId, sourceRowKey), {
              id: insertedId,
              status: 'pending',
              metadata,
            });
            activeSourceKeys.add(buildSourceOperationKey(sourceTable, sourceRecordId, sourceRowKey));
          }
          existingOperations.byId.set(insertedId, insertedRow);
        }
      }

      if (sourceChanged) {
        const { error: updateSourceError } = await supabase
          .from(source.table)
          .update({
            payments: nextPayments,
            updated_at: nowIso,
          })
          .eq('id', recordId);
        if (updateSourceError) throw updateSourceError;
        summary.sourceRecordsUpdated += 1;
      }
    }
  }

  for (const [sourceKey, existingOperation] of existingOperations.bySourceKey.entries()) {
    if (activeSourceKeys.has(sourceKey)) continue;
    if (normalizeOperationalText(existingOperation?.status) === 'canceled') continue;
    const metadata = parseCashBankMetadata(existingOperation?.metadata);
    const rowKey = normalizeOperationalText(metadata?.source_row_key);
    const sourceTable = normalizeOperationalText(metadata?.source_table);
    const sourceRecordId = normalizeOperationalText(metadata?.source_record_id);
    const cancelPayload = {
      status: 'canceled',
      metadata: buildOperationMetadata(sourceTable, sourceRecordId, rowKey),
      updated_at: nowIso,
    };
    const cancelResult = await runWriteWithCompatiblePayload<null>({
      cacheKey: 'cash-bank-backfill:cancel',
      payload: cancelPayload,
      execute: (compatiblePayload) =>
        supabase
          .from('cash_bank_operations')
          .update(compatiblePayload)
          .eq('id', existingOperation.id),
    });
    if (cancelResult.error) throw cancelResult.error;
    summary.canceled += 1;
  }

  return summary;
};
