import { useEffect, useMemo, useState } from 'react';
import { Alert, ConfigProvider, Spin, Tag, theme as antdTheme } from 'antd';
import { CalendarOutlined, CheckCircleOutlined, ProjectOutlined } from '@ant-design/icons';
import { useParams } from 'react-router-dom';
import DateObject from 'react-date-object';
import persian from 'react-date-object/calendars/persian';
import persian_fa from 'react-date-object/locales/persian_fa';
import gregorian from 'react-date-object/calendars/gregorian';
import gregorian_en from 'react-date-object/locales/gregorian_en';
import { supabasePublic } from '../supabaseClient';
import { usePublicTimeTheme } from '../components/public/PublicThemeBoundary';

const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const toPersian = (date: Date) => new DateObject({ date, calendar: gregorian, locale: gregorian_en }).convert(persian, persian_fa);
const toGregorian = (date: DateObject) => new DateObject(date).convert(gregorian, gregorian_en).toDate();
const addDays = (date: Date, amount: number) => { const next = new Date(date); next.setDate(next.getDate() + amount); next.setHours(12, 0, 0, 0); return next; };
const asDate = (value: any) => { const date = value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date : null; };

export default function OnlineContentCalendarPublicPage() {
  const { token } = useParams<{ token: string }>();
  const isDark = usePublicTimeTheme();
  const [payload, setPayload] = useState<any>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [anchor, setAnchor] = useState(new Date());
  useEffect(() => { let active = true; void supabasePublic.rpc('get_public_content_calendar', { p_token: String(token || '').trim() }).then(({ data, error: rpcError }) => { if (!active) return; if (rpcError || data?.error) throw rpcError || new Error('تقویم پیدا نشد یا لینک آن غیرفعال است.'); setPayload(data); }).catch((reason) => active && setError(String(reason?.message || 'بارگذاری تقویم ناموفق بود.'))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [token]);
  const days = useMemo(() => { const p = toPersian(anchor); const first = toGregorian(new DateObject({ year: p.year, month: p.month.number, day: 1, calendar: persian, locale: persian_fa })); const start = addDays(first, -((first.getDay() + 1) % 7)); return Array.from({ length: 42 }, (_, i) => { const date = addDays(start, i); const j = toPersian(date); return { date, key: dateKey(date), day: j.format('D'), inMonth: j.year === p.year && j.month.number === p.month.number, today: dateKey(date) === dateKey(new Date()) }; }); }, [anchor]);
  const events = useMemo(() => { const map = new Map<string, any[]>(); [...(payload?.projects || []).map((row: any) => ({ ...row, kind: 'project' })), ...(payload?.tasks || []).map((row: any) => ({ ...row, kind: 'task' }))].forEach((row: any) => { const date = asDate(row.due_date || row.start_date || row.completed_at); if (date) map.set(dateKey(date), [...(map.get(dateKey(date)) || []), row]); }); return map; }, [payload]);
  const calendar = payload?.calendar || {}; const company = payload?.company?.company_settings || {}; const branding = payload?.company?.branding_settings || {}; const name = company?.trade_name || company?.company_name || 'سازمان';
  const themeConfig = { algorithm: isDark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm, token: { colorPrimary: '#2563eb', fontFamily: 'Peyda, Tahoma, Arial, sans-serif' } };
  if (loading) return <ConfigProvider direction="rtl" theme={themeConfig}><div className="flex min-h-screen items-center justify-center"><Spin size="large" /></div></ConfigProvider>;
  if (error) return <ConfigProvider direction="rtl" theme={themeConfig}><div dir="rtl" className="mx-auto mt-16 max-w-lg px-4"><Alert type="error" showIcon message="تقویم در دسترس نیست" description={error} /></div></ConfigProvider>;
  return <ConfigProvider direction="rtl" theme={themeConfig}><main dir="rtl" className="min-h-screen bg-slate-100 p-3 text-slate-800 dark:bg-slate-950 dark:text-slate-100 sm:p-8"><section className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-white shadow-2xl dark:bg-slate-900"><header className="bg-gradient-to-bl from-blue-800 via-blue-600 to-sky-400 px-6 py-8 text-white sm:px-10"><div className="text-sm text-white/75">{name}</div><h1 className="mt-2 text-2xl font-black sm:text-4xl"><CalendarOutlined className="ml-2" />{calendar.name || 'تقویم محتوایی آنلاین'}</h1>{calendar.description ? <p className="mt-3 max-w-3xl text-sm text-white/90">{calendar.description}</p> : null}</header><div className="p-3 sm:p-6"><div className="mb-4 flex items-center justify-between"><button className="rounded-lg px-3 py-1 hover:bg-slate-100 dark:hover:bg-slate-800" onClick={() => setAnchor(toGregorian(toPersian(anchor).add(-1, 'month')))}>ماه قبل</button><div className="font-black">{toPersian(anchor).format('MMMM YYYY')}</div><button className="rounded-lg px-3 py-1 hover:bg-slate-100 dark:hover:bg-slate-800" onClick={() => setAnchor(toGregorian(toPersian(anchor).add(1, 'month')))}>ماه بعد</button></div><div className="grid grid-cols-7 gap-1 text-center text-xs text-slate-500">{['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'].map(x => <div key={x}>{x}</div>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{days.map(day => <div key={day.key} className={`min-h-[104px] rounded-xl border p-1.5 text-right ${day.inMonth ? 'bg-white dark:bg-slate-800' : 'opacity-35'} ${day.today ? 'border-blue-500 bg-blue-50 ring-2 ring-blue-400/60 dark:bg-blue-950/40' : 'border-slate-100 dark:border-slate-700'}`}><div className="flex justify-between"><b>{day.day}</b>{day.today ? <span className="rounded-full bg-blue-600 px-2 py-0.5 text-[10px] font-black text-white shadow">امروز</span> : null}</div><div className="mt-1 space-y-1">{(events.get(day.key) || []).slice(0, 3).map((row: any, i: number) => <div key={`${row.kind}-${row.id}-${i}`} className="rounded-md border-r-4 border-blue-500 bg-slate-50 p-1 text-[10px] dark:bg-slate-700"><div className="truncate font-bold">{row.kind === 'task' ? <CheckCircleOutlined className="ml-1" /> : <ProjectOutlined className="ml-1" />}{row.name || 'بدون عنوان'}</div>{row.kind === 'task' && row.content_type ? <Tag className="!m-0 !mt-1" color="blue">{row.content_type}</Tag> : null}</div>)}</div></div>)}</div></div></section></main></ConfigProvider>;
}
